import {
  noGiantComponent,
  noNestedComponentDefinition,
  noRenderInRender,
} from "./rules/architecture.js";
import {
  noBarrelImport,
  noFullLodashImport,
  noMoment,
  noUndeferredThirdParty,
  preferDynamicImport,
  useLazyMotion,
} from "./rules/bundle-size.js";
import { clientPassiveEventListeners } from "./rules/client.js";
import {
  noDarkModeGlow,
  noDisabledZoom,
  noGradientText,
  noGrayOnColoredBackground,
  noInlineBounceEasing,
  noInlineExhaustiveStyle,
  noJustifiedText,
  noLayoutTransitionInline,
  noLongTransitionDuration,
  noOutlineNone,
  noPureBlackBackground,
  noSideTabBorder,
  noTinyText,
  noWideLetterSpacing,
  noZIndex9999,
} from "./rules/design.js";
import {
  noArrayIndexAsKey,
  noPreventDefault,
  renderingConditionalRender,
} from "./rules/correctness.js";
import {
  asyncParallel,
  jsBatchDomCss,
  jsCacheStorage,
  jsCombineIterations,
  jsEarlyExit,
  jsHoistRegexp,
  jsIndexMaps,
  jsMinMaxLoop,
  jsSetMapLookups,
  jsTosortedImmutable,
  jsFlatmapFilter,
} from "./rules/js-performance.js";
import {
  nextjsAsyncClientComponent,
  nextjsImageMissingSizes,
  nextjsInlineScriptMissingId,
  nextjsMissingMetadata,
  nextjsNoAElement,
  nextjsNoClientFetchForServerData,
  nextjsNoClientSideRedirect,
  nextjsNoCssLink,
  nextjsNoFontLink,
  nextjsNoHeadImport,
  nextjsNoImgElement,
  nextjsNoNativeScript,
  nextjsNoPolyfillScript,
  nextjsNoRedirectInTryCatch,
  nextjsNoSideEffectInGetHandler,
  nextjsNoUseSearchParamsWithoutSuspense,
} from "./rules/nextjs.js";
import {
  noGlobalCssVariableAnimation,
  noLargeAnimatedBlur,
  noLayoutPropertyAnimation,
  noPermanentWillChange,
  noScaleFromZero,
  noTransitionAll,
  noUsememoSimpleExpression,
  renderingAnimateSvgWrapper,
  noInlinePropOnMemoComponent,
  renderingHydrationNoFlicker,
  renderingScriptDeferAsync,
  rerenderMemoWithDefaultValue,
} from "./rules/performance.js";
import {
  rnNoRawText,
  rnNoDeprecatedModules,
  rnNoLegacyExpoPackages,
  rnNoDimensionsGet,
  rnNoInlineFlatlistRenderitem,
  rnNoLegacyShadowStyles,
  rnPreferReanimated,
  rnNoSingleElementStyleArray,
} from "./rules/react-native.js";
import {
  queryMutationMissingInvalidation,
  queryNoQueryInEffect,
  queryNoRestDestructuring,
  queryNoUseQueryForMutation,
  queryNoVoidQueryFn,
  queryStableQueryClient,
} from "./rules/tanstack-query.js";
import { noEval, noSecretsInClientCode } from "./rules/security.js";
import { serverAfterNonblocking, serverAuthActions } from "./rules/server.js";
import {
  tanstackStartGetMutation,
  tanstackStartLoaderParallelFetch,
  tanstackStartMissingHeadContent,
  tanstackStartNoAnchorElement,
  tanstackStartNoDirectFetchInLoader,
  tanstackStartNoDynamicServerFnImport,
  tanstackStartNoNavigateInRender,
  tanstackStartNoSecretsInLoader,
  tanstackStartNoUseEffectFetch,
  tanstackStartNoUseServerInHandler,
  tanstackStartRedirectInTryCatch,
  tanstackStartRoutePropertyOrder,
  tanstackStartServerFnMethodOrder,
  tanstackStartServerFnValidateInput,
} from "./rules/tanstack-start.js";
import {
  noCascadingSetState,
  noDerivedStateEffect,
  noDerivedUseState,
  noEffectEventHandler,
  noFetchInEffect,
  preferUseReducer,
  rerenderDependencies,
  rerenderFunctionalSetstate,
  rerenderLazyStateInit,
} from "./rules/state-and-effects.js";
import type { RulePlugin } from "./types.js";

const plugin: RulePlugin = {
  meta: { name: "react-doctor" },
  rules: {
    "no-derived-state-effect": noDerivedStateEffect,
    "no-fetch-in-effect": noFetchInEffect,
    "no-cascading-set-state": noCascadingSetState,
    "no-effect-event-handler": noEffectEventHandler,
    "no-derived-useState": noDerivedUseState,
    "prefer-useReducer": preferUseReducer,
    "rerender-lazy-state-init": rerenderLazyStateInit,
    "rerender-functional-setstate": rerenderFunctionalSetstate,
    "rerender-dependencies": rerenderDependencies,

    "no-giant-component": noGiantComponent,
    "no-render-in-render": noRenderInRender,
    "no-nested-component-definition": noNestedComponentDefinition,

    "no-usememo-simple-expression": noUsememoSimpleExpression,
    "no-layout-property-animation": noLayoutPropertyAnimation,
    "rerender-memo-with-default-value": rerenderMemoWithDefaultValue,
    "rendering-animate-svg-wrapper": renderingAnimateSvgWrapper,
    "no-inline-prop-on-memo-component": noInlinePropOnMemoComponent,
    "rendering-hydration-no-flicker": renderingHydrationNoFlicker,
    "rendering-script-defer-async": renderingScriptDeferAsync,

    "no-transition-all": noTransitionAll,
    "no-global-css-variable-animation": noGlobalCssVariableAnimation,
    "no-large-animated-blur": noLargeAnimatedBlur,
    "no-scale-from-zero": noScaleFromZero,
    "no-permanent-will-change": noPermanentWillChange,

    "no-eval": noEval,
    "no-secrets-in-client-code": noSecretsInClientCode,

    "no-barrel-import": noBarrelImport,
    "no-full-lodash-import": noFullLodashImport,
    "no-moment": noMoment,
    "prefer-dynamic-import": preferDynamicImport,
    "use-lazy-motion": useLazyMotion,
    "no-undeferred-third-party": noUndeferredThirdParty,

    "no-array-index-as-key": noArrayIndexAsKey,
    "rendering-conditional-render": renderingConditionalRender,
    "no-prevent-default": noPreventDefault,

    "nextjs-no-img-element": nextjsNoImgElement,
    "nextjs-async-client-component": nextjsAsyncClientComponent,
    "nextjs-no-a-element": nextjsNoAElement,
    "nextjs-no-use-search-params-without-suspense": nextjsNoUseSearchParamsWithoutSuspense,
    "nextjs-no-client-fetch-for-server-data": nextjsNoClientFetchForServerData,
    "nextjs-missing-metadata": nextjsMissingMetadata,
    "nextjs-no-client-side-redirect": nextjsNoClientSideRedirect,
    "nextjs-no-redirect-in-try-catch": nextjsNoRedirectInTryCatch,
    "nextjs-image-missing-sizes": nextjsImageMissingSizes,
    "nextjs-no-native-script": nextjsNoNativeScript,
    "nextjs-inline-script-missing-id": nextjsInlineScriptMissingId,
    "nextjs-no-font-link": nextjsNoFontLink,
    "nextjs-no-css-link": nextjsNoCssLink,
    "nextjs-no-polyfill-script": nextjsNoPolyfillScript,
    "nextjs-no-head-import": nextjsNoHeadImport,
    "nextjs-no-side-effect-in-get-handler": nextjsNoSideEffectInGetHandler,

    "server-auth-actions": serverAuthActions,
    "server-after-nonblocking": serverAfterNonblocking,

    "client-passive-event-listeners": clientPassiveEventListeners,

    "js-combine-iterations": jsCombineIterations,
    "js-tosorted-immutable": jsTosortedImmutable,
    "js-hoist-regexp": jsHoistRegexp,
    "js-min-max-loop": jsMinMaxLoop,
    "js-set-map-lookups": jsSetMapLookups,
    "js-batch-dom-css": jsBatchDomCss,
    "js-index-maps": jsIndexMaps,
    "js-cache-storage": jsCacheStorage,
    "js-early-exit": jsEarlyExit,
    "js-flatmap-filter": jsFlatmapFilter,
    "async-parallel": asyncParallel,

    "rn-no-raw-text": rnNoRawText,
    "rn-no-deprecated-modules": rnNoDeprecatedModules,
    "rn-no-legacy-expo-packages": rnNoLegacyExpoPackages,
    "rn-no-dimensions-get": rnNoDimensionsGet,
    "rn-no-inline-flatlist-renderitem": rnNoInlineFlatlistRenderitem,
    "rn-no-legacy-shadow-styles": rnNoLegacyShadowStyles,
    "rn-prefer-reanimated": rnPreferReanimated,
    "rn-no-single-element-style-array": rnNoSingleElementStyleArray,

    "tanstack-start-route-property-order": tanstackStartRoutePropertyOrder,
    "tanstack-start-no-direct-fetch-in-loader": tanstackStartNoDirectFetchInLoader,
    "tanstack-start-server-fn-validate-input": tanstackStartServerFnValidateInput,
    "tanstack-start-no-useeffect-fetch": tanstackStartNoUseEffectFetch,
    "tanstack-start-missing-head-content": tanstackStartMissingHeadContent,
    "tanstack-start-no-anchor-element": tanstackStartNoAnchorElement,
    "tanstack-start-server-fn-method-order": tanstackStartServerFnMethodOrder,
    "tanstack-start-no-navigate-in-render": tanstackStartNoNavigateInRender,
    "tanstack-start-no-dynamic-server-fn-import": tanstackStartNoDynamicServerFnImport,
    "tanstack-start-no-use-server-in-handler": tanstackStartNoUseServerInHandler,
    "tanstack-start-no-secrets-in-loader": tanstackStartNoSecretsInLoader,
    "tanstack-start-get-mutation": tanstackStartGetMutation,
    "tanstack-start-redirect-in-try-catch": tanstackStartRedirectInTryCatch,
    "tanstack-start-loader-parallel-fetch": tanstackStartLoaderParallelFetch,

    "query-stable-query-client": queryStableQueryClient,
    "query-no-rest-destructuring": queryNoRestDestructuring,
    "query-no-void-query-fn": queryNoVoidQueryFn,
    "query-no-query-in-effect": queryNoQueryInEffect,
    "query-mutation-missing-invalidation": queryMutationMissingInvalidation,
    "query-no-usequery-for-mutation": queryNoUseQueryForMutation,

    "no-inline-bounce-easing": noInlineBounceEasing,
    "no-z-index-9999": noZIndex9999,
    "no-inline-exhaustive-style": noInlineExhaustiveStyle,
    "no-side-tab-border": noSideTabBorder,
    "no-pure-black-background": noPureBlackBackground,
    "no-gradient-text": noGradientText,
    "no-dark-mode-glow": noDarkModeGlow,
    "no-justified-text": noJustifiedText,
    "no-tiny-text": noTinyText,
    "no-wide-letter-spacing": noWideLetterSpacing,
    "no-gray-on-colored-background": noGrayOnColoredBackground,
    "no-layout-transition-inline": noLayoutTransitionInline,
    "no-disabled-zoom": noDisabledZoom,
    "no-outline-none": noOutlineNone,
    "no-long-transition-duration": noLongTransitionDuration,
  },
};

export default plugin;
