export const PROMPT_PROBE_OBSERVATION_WINDOW_MS = 750;
export const PROMPT_PROBE_STARTUP_TIMEOUT_MS = 10_000;
export const PROMPT_PROBE_SLOW_START_MS = 1_500;
export const TEMPORARY_DIRECTORY_REMOVE_MAX_RETRIES = 10;
