import { execFileSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { afterEach, describe, expect, it } from "vite-plus/test";
import type { JsonReport } from "@react-doctor/core";
import type { Diagnostic, JsonReportProjectEntry, ProjectInfo } from "@react-doctor/core";

const REPOSITORY_ROOT = path.resolve(import.meta.dirname, "..", "..", "..");
const RENDER_SCRIPT_PATH = path.join(REPOSITORY_ROOT, "scripts/render-github-action-comment.mjs");

const tempDirectories: string[] = [];

const setupTempDirectory = (): string => {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), "react-doctor-comment-"));
  tempDirectories.push(directory);
  return directory;
};

const buildProject = (overrides: Partial<ProjectInfo> = {}): ProjectInfo => ({
  rootDirectory: "/repo",
  projectName: "web",
  reactVersion: "^19.0.0",
  reactMajorVersion: 19,
  tailwindVersion: null,
  framework: "unknown",
  hasTypeScript: true,
  hasReactCompiler: false,
  hasTanStackQuery: false,
  preactVersion: null,
  preactMajorVersion: null,
  hasReactNativeWorkspace: false,
  hasReanimated: false,
  sourceFileCount: 2,
  ...overrides,
});

const buildProjectEntry = (
  diagnostics: Diagnostic[],
  overrides: Partial<JsonReportProjectEntry> = {},
): JsonReportProjectEntry => ({
  directory: "/repo",
  project: buildProject(),
  diagnostics,
  score: { score: 81, label: "Good" },
  skippedChecks: [],
  elapsedMilliseconds: 123,
  ...overrides,
});

const buildDiagnostics = (): Diagnostic[] => [
  {
    plugin: "react-doctor",
    rule: "no-derived-state",
    severity: "error",
    category: "correctness",
    message: "Avoid derived state",
    help: "Store source state instead.",
    filePath: "src/App.tsx",
    line: 10,
    column: 3,
  },
  {
    plugin: "react-doctor",
    rule: "no-derived-state",
    severity: "error",
    category: "correctness",
    message: "Avoid derived state",
    help: "Store source state instead.",
    filePath: "src/Profile.tsx",
    line: 4,
    column: 8,
  },
];

const buildReport = (overrides: Partial<JsonReport> = {}): JsonReport => {
  const diagnostics = buildDiagnostics();
  return {
    schemaVersion: 1,
    version: "0.0.0-test",
    ok: true,
    directory: "/repo",
    mode: "diff",
    diff: {
      baseBranch: "main",
      currentBranch: "feature",
      changedFileCount: 2,
      isCurrentChanges: false,
    },
    projects: [buildProjectEntry(diagnostics)],
    diagnostics,
    summary: {
      errorCount: 2,
      warningCount: 0,
      affectedFileCount: 2,
      totalDiagnosticCount: 2,
      score: 81,
      scoreLabel: "Good",
    },
    elapsedMilliseconds: 123,
    error: null,
    ...overrides,
  };
};

const runRenderer = (report: JsonReport) => {
  const tempDirectory = setupTempDirectory();
  const reportPath = path.join(tempDirectory, "report.json");
  const commentPath = path.join(tempDirectory, "comment.md");
  const outputPath = path.join(tempDirectory, "outputs.txt");
  fs.writeFileSync(reportPath, `${JSON.stringify(report)}\n`);

  execFileSync(process.execPath, [RENDER_SCRIPT_PATH, reportPath, commentPath], {
    env: {
      ...process.env,
      GITHUB_OUTPUT: outputPath,
      GITHUB_RUN_URL: "https://github.com/millionco/react-doctor/actions/runs/123",
    },
  });

  return {
    comment: fs.readFileSync(commentPath, "utf8"),
    outputs: fs.readFileSync(outputPath, "utf8"),
  };
};

describe("render-github-action-comment", () => {
  afterEach(() => {
    for (const directory of tempDirectories.splice(0)) {
      fs.rmSync(directory, { recursive: true, force: true });
    }
  });

  it("renders a sticky markdown summary and action outputs from a JSON report", () => {
    const { comment, outputs } = runRenderer(buildReport());

    expect(comment).toContain("<!-- react-doctor:summary -->");
    expect(comment).toContain("react-doctor-og-banner.svg");
    expect(comment).toContain('<a href="https://react.doctor">');
    expect(comment).toContain('alt="React Doctor"');
    expect(comment).toContain(
      "| 81 / 100 (Good) | 2 | 2 | 0 | 2 | 2 files changed on `feature` vs. `main` |",
    );
    expect(comment).toContain("`react-doctor/no-derived-state`");
    expect(comment).toContain("[View workflow run]");
    expect(comment).toContain("Generated by [React Doctor]");
    expect(comment).toContain("founders@million.dev");
    expect(outputs).toContain("score=81");
    expect(outputs).toContain("total-issues=2");
    expect(outputs).toContain("error-count=2");
    expect(outputs).toContain("affected-files=2");
  });

  it("renders completed scans with no findings as a clean result", () => {
    const { comment } = runRenderer(
      buildReport({
        diagnostics: [],
        projects: [buildProjectEntry([], { diagnostics: [] })],
        summary: {
          errorCount: 0,
          warningCount: 0,
          affectedFileCount: 0,
          totalDiagnosticCount: 0,
          score: 100,
          scoreLabel: "Great",
        },
      }),
    );

    expect(comment).toContain("No React Doctor issues found in this scan.");
    expect(comment).toContain(
      "| 100 / 100 (Great) | 0 | 0 | 0 | 0 | 2 files changed on `feature` vs. `main` |",
    );
  });

  it("renders no-scan diff reports without a metrics table", () => {
    const { comment, outputs } = runRenderer(
      buildReport({
        projects: [],
        diagnostics: [],
        summary: {
          errorCount: 0,
          warningCount: 0,
          affectedFileCount: 0,
          totalDiagnosticCount: 0,
          score: null,
          scoreLabel: null,
        },
      }),
    );

    expect(comment).toContain(
      "React Doctor found 2 files changed in this pull request, but none matched the files covered by its enabled checks.",
    );
    expect(comment).toContain("Scope: 2 files changed on `feature` vs. `main`.");
    expect(comment).not.toContain(
      "| Score | Issues | Errors | Warnings | Affected Files | Scope |",
    );
    expect(outputs).toContain("score=");
  });

  it("renders incomplete checks as an explicit caveat", () => {
    const { comment } = runRenderer(
      buildReport({
        diagnostics: [],
        projects: [
          buildProjectEntry([], {
            diagnostics: [],
            score: null,
            skippedChecks: ["lint"],
            skippedCheckReasons: {
              lint: "oxlint did not return within 300s.",
            },
          }),
        ],
        summary: {
          errorCount: 0,
          warningCount: 0,
          affectedFileCount: 0,
          totalDiagnosticCount: 0,
          score: null,
          scoreLabel: null,
        },
      }),
    );

    expect(comment).toContain(
      "No React Doctor issues were found, but some checks were incomplete.",
    );
    expect(comment).toContain("### Incomplete Checks");
    expect(comment).toContain("`lint`: oxlint did not return within 300s.");
  });

  it("renders partial-check reasons even without a skipped check entry", () => {
    const { comment } = runRenderer(
      buildReport({
        projects: [
          buildProjectEntry(buildDiagnostics(), {
            skippedCheckReasons: {
              "lint:partial": "1 file exceeded the oxlint budget.",
            },
          }),
        ],
      }),
    );

    expect(comment).toContain("### Incomplete Checks");
    expect(comment).toContain("`lint:partial`: 1 file exceeded the oxlint budget.");
  });

  it("renders scan errors instead of pretending the run succeeded", () => {
    const { comment, outputs } = runRenderer(
      buildReport({
        ok: false,
        mode: "full",
        diff: null,
        diagnostics: [],
        summary: {
          errorCount: 0,
          warningCount: 0,
          affectedFileCount: 0,
          totalDiagnosticCount: 0,
          score: null,
          scoreLabel: null,
        },
        error: {
          name: "ReactDoctorActionError",
          message: "react-doctor exited with status 1 before producing a JSON report.",
          chain: [],
        },
      }),
    );

    expect(comment).toContain("React Doctor could not complete this scan.");
    expect(comment).toContain("react-doctor-og-banner.svg");
    expect(comment).toContain("react-doctor exited with status 1");
    expect(comment).toContain("[Report this bug]");
    expect(comment).toContain("issues/new?");
    expect(comment).toContain("React+Doctor+Action+failed");
    expect(comment).toContain("Generated by [React Doctor]");
    expect(comment).toContain("founders@million.dev");
    expect(outputs).toContain("score=");
    expect(outputs).toContain("total-issues=0");
  });
});
