// GENERATED FILE — do not edit by hand. Run `pnpm gen` to regenerate.

import { rnAnimateLayoutProperty } from "./../rules/react-native/rn-animate-layout-property.js";
import { rnAnimationReactionAsDerived } from "./../rules/react-native/rn-animation-reaction-as-derived.js";
import { rnBottomSheetPreferNative } from "./../rules/react-native/rn-bottom-sheet-prefer-native.js";
import { rnListCallbackPerRow } from "./../rules/react-native/rn-list-callback-per-row.js";
import { rnListDataMapped } from "./../rules/react-native/rn-list-data-mapped.js";
import { rnListRecyclableWithoutTypes } from "./../rules/react-native/rn-list-recyclable-without-types.js";
import { rnNoDeprecatedModules } from "./../rules/react-native/rn-no-deprecated-modules.js";
import { rnNoDimensionsGet } from "./../rules/react-native/rn-no-dimensions-get.js";
import { rnNoInlineFlatlistRenderitem } from "./../rules/react-native/rn-no-inline-flatlist-renderitem.js";
import { rnNoInlineObjectInListItem } from "./../rules/react-native/rn-no-inline-object-in-list-item.js";
import { rnNoLegacyExpoPackages } from "./../rules/react-native/rn-no-legacy-expo-packages.js";
import { rnNoLegacyShadowStyles } from "./../rules/react-native/rn-no-legacy-shadow-styles.js";
import { rnNoNonNativeNavigator } from "./../rules/react-native/rn-no-non-native-navigator.js";
import { rnNoRawText } from "./../rules/react-native/rn-no-raw-text.js";
import { rnNoScrollState } from "./../rules/react-native/rn-no-scroll-state.js";
import { rnNoScrollviewMappedList } from "./../rules/react-native/rn-no-scrollview-mapped-list.js";
import { rnNoSingleElementStyleArray } from "./../rules/react-native/rn-no-single-element-style-array.js";
import { rnPreferContentInsetAdjustment } from "./../rules/react-native/rn-prefer-content-inset-adjustment.js";
import { rnPreferExpoImage } from "./../rules/react-native/rn-prefer-expo-image.js";
import { rnPreferPressable } from "./../rules/react-native/rn-prefer-pressable.js";
import { rnPreferReanimated } from "./../rules/react-native/rn-prefer-reanimated.js";
import { rnPressableSharedValueMutation } from "./../rules/react-native/rn-pressable-shared-value-mutation.js";
import { rnScrollviewDynamicPadding } from "./../rules/react-native/rn-scrollview-dynamic-padding.js";
import { rnStylePreferBoxShadow } from "./../rules/react-native/rn-style-prefer-box-shadow.js";

export const ReactNativeRuleEntries = [
  {
    key: "react-doctor/rn-animate-layout-property",
    id: "rn-animate-layout-property",
    source: "react-doctor",
    originallyExternal: false,
    framework: "react-native",
    category: "React Native",
    severity: "error",
    rule: {
      ...rnAnimateLayoutProperty,
      framework: "react-native",
      category: "React Native",
      requires: [...new Set(["react-native", ...(rnAnimateLayoutProperty.requires ?? [])])],
      tags: [...new Set(["react-native", ...(rnAnimateLayoutProperty.tags ?? [])])],
    },
  },
  {
    key: "react-doctor/rn-animation-reaction-as-derived",
    id: "rn-animation-reaction-as-derived",
    source: "react-doctor",
    originallyExternal: false,
    framework: "react-native",
    category: "React Native",
    severity: "warn",
    rule: {
      ...rnAnimationReactionAsDerived,
      framework: "react-native",
      category: "React Native",
      requires: [...new Set(["react-native", ...(rnAnimationReactionAsDerived.requires ?? [])])],
      tags: [...new Set(["react-native", ...(rnAnimationReactionAsDerived.tags ?? [])])],
    },
  },
  {
    key: "react-doctor/rn-bottom-sheet-prefer-native",
    id: "rn-bottom-sheet-prefer-native",
    source: "react-doctor",
    originallyExternal: false,
    framework: "react-native",
    category: "React Native",
    severity: "warn",
    rule: {
      ...rnBottomSheetPreferNative,
      framework: "react-native",
      category: "React Native",
      requires: [...new Set(["react-native", ...(rnBottomSheetPreferNative.requires ?? [])])],
      tags: [...new Set(["react-native", ...(rnBottomSheetPreferNative.tags ?? [])])],
    },
  },
  {
    key: "react-doctor/rn-list-callback-per-row",
    id: "rn-list-callback-per-row",
    source: "react-doctor",
    originallyExternal: false,
    framework: "react-native",
    category: "React Native",
    severity: "warn",
    rule: {
      ...rnListCallbackPerRow,
      framework: "react-native",
      category: "React Native",
      requires: [...new Set(["react-native", ...(rnListCallbackPerRow.requires ?? [])])],
      tags: [...new Set(["react-native", ...(rnListCallbackPerRow.tags ?? [])])],
    },
  },
  {
    key: "react-doctor/rn-list-data-mapped",
    id: "rn-list-data-mapped",
    source: "react-doctor",
    originallyExternal: false,
    framework: "react-native",
    category: "React Native",
    severity: "warn",
    rule: {
      ...rnListDataMapped,
      framework: "react-native",
      category: "React Native",
      requires: [...new Set(["react-native", ...(rnListDataMapped.requires ?? [])])],
      tags: [...new Set(["react-native", ...(rnListDataMapped.tags ?? [])])],
    },
  },
  {
    key: "react-doctor/rn-list-recyclable-without-types",
    id: "rn-list-recyclable-without-types",
    source: "react-doctor",
    originallyExternal: false,
    framework: "react-native",
    category: "React Native",
    severity: "warn",
    rule: {
      ...rnListRecyclableWithoutTypes,
      framework: "react-native",
      category: "React Native",
      requires: [...new Set(["react-native", ...(rnListRecyclableWithoutTypes.requires ?? [])])],
      tags: [...new Set(["react-native", ...(rnListRecyclableWithoutTypes.tags ?? [])])],
    },
  },
  {
    key: "react-doctor/rn-no-deprecated-modules",
    id: "rn-no-deprecated-modules",
    source: "react-doctor",
    originallyExternal: false,
    framework: "react-native",
    category: "React Native",
    severity: "error",
    rule: {
      ...rnNoDeprecatedModules,
      framework: "react-native",
      category: "React Native",
      requires: [...new Set(["react-native", ...(rnNoDeprecatedModules.requires ?? [])])],
      tags: [...new Set(["react-native", ...(rnNoDeprecatedModules.tags ?? [])])],
    },
  },
  {
    key: "react-doctor/rn-no-dimensions-get",
    id: "rn-no-dimensions-get",
    source: "react-doctor",
    originallyExternal: false,
    framework: "react-native",
    category: "React Native",
    severity: "warn",
    rule: {
      ...rnNoDimensionsGet,
      framework: "react-native",
      category: "React Native",
      requires: [...new Set(["react-native", ...(rnNoDimensionsGet.requires ?? [])])],
      tags: [...new Set(["react-native", ...(rnNoDimensionsGet.tags ?? [])])],
    },
  },
  {
    key: "react-doctor/rn-no-inline-flatlist-renderitem",
    id: "rn-no-inline-flatlist-renderitem",
    source: "react-doctor",
    originallyExternal: false,
    framework: "react-native",
    category: "React Native",
    severity: "warn",
    rule: {
      ...rnNoInlineFlatlistRenderitem,
      framework: "react-native",
      category: "React Native",
      requires: [...new Set(["react-native", ...(rnNoInlineFlatlistRenderitem.requires ?? [])])],
      tags: [...new Set(["react-native", ...(rnNoInlineFlatlistRenderitem.tags ?? [])])],
    },
  },
  {
    key: "react-doctor/rn-no-inline-object-in-list-item",
    id: "rn-no-inline-object-in-list-item",
    source: "react-doctor",
    originallyExternal: false,
    framework: "react-native",
    category: "React Native",
    severity: "warn",
    rule: {
      ...rnNoInlineObjectInListItem,
      framework: "react-native",
      category: "React Native",
      requires: [...new Set(["react-native", ...(rnNoInlineObjectInListItem.requires ?? [])])],
      tags: [...new Set(["react-native", ...(rnNoInlineObjectInListItem.tags ?? [])])],
    },
  },
  {
    key: "react-doctor/rn-no-legacy-expo-packages",
    id: "rn-no-legacy-expo-packages",
    source: "react-doctor",
    originallyExternal: false,
    framework: "react-native",
    category: "React Native",
    severity: "warn",
    rule: {
      ...rnNoLegacyExpoPackages,
      framework: "react-native",
      category: "React Native",
      requires: [...new Set(["react-native", ...(rnNoLegacyExpoPackages.requires ?? [])])],
      tags: [...new Set(["react-native", ...(rnNoLegacyExpoPackages.tags ?? [])])],
    },
  },
  {
    key: "react-doctor/rn-no-legacy-shadow-styles",
    id: "rn-no-legacy-shadow-styles",
    source: "react-doctor",
    originallyExternal: false,
    framework: "react-native",
    category: "React Native",
    severity: "warn",
    rule: {
      ...rnNoLegacyShadowStyles,
      framework: "react-native",
      category: "React Native",
      requires: [...new Set(["react-native", ...(rnNoLegacyShadowStyles.requires ?? [])])],
      tags: [...new Set(["react-native", ...(rnNoLegacyShadowStyles.tags ?? [])])],
    },
  },
  {
    key: "react-doctor/rn-no-non-native-navigator",
    id: "rn-no-non-native-navigator",
    source: "react-doctor",
    originallyExternal: false,
    framework: "react-native",
    category: "React Native",
    severity: "warn",
    rule: {
      ...rnNoNonNativeNavigator,
      framework: "react-native",
      category: "React Native",
      requires: [...new Set(["react-native", ...(rnNoNonNativeNavigator.requires ?? [])])],
      tags: [...new Set(["react-native", ...(rnNoNonNativeNavigator.tags ?? [])])],
    },
  },
  {
    key: "react-doctor/rn-no-raw-text",
    id: "rn-no-raw-text",
    source: "react-doctor",
    originallyExternal: false,
    framework: "react-native",
    category: "React Native",
    severity: "error",
    rule: {
      ...rnNoRawText,
      framework: "react-native",
      category: "React Native",
      requires: [...new Set(["react-native", ...(rnNoRawText.requires ?? [])])],
      tags: [...new Set(["react-native", ...(rnNoRawText.tags ?? [])])],
    },
  },
  {
    key: "react-doctor/rn-no-scroll-state",
    id: "rn-no-scroll-state",
    source: "react-doctor",
    originallyExternal: false,
    framework: "react-native",
    category: "React Native",
    severity: "error",
    rule: {
      ...rnNoScrollState,
      framework: "react-native",
      category: "React Native",
      requires: [...new Set(["react-native", ...(rnNoScrollState.requires ?? [])])],
      tags: [...new Set(["react-native", ...(rnNoScrollState.tags ?? [])])],
    },
  },
  {
    key: "react-doctor/rn-no-scrollview-mapped-list",
    id: "rn-no-scrollview-mapped-list",
    source: "react-doctor",
    originallyExternal: false,
    framework: "react-native",
    category: "React Native",
    severity: "warn",
    rule: {
      ...rnNoScrollviewMappedList,
      framework: "react-native",
      category: "React Native",
      requires: [...new Set(["react-native", ...(rnNoScrollviewMappedList.requires ?? [])])],
      tags: [...new Set(["react-native", ...(rnNoScrollviewMappedList.tags ?? [])])],
    },
  },
  {
    key: "react-doctor/rn-no-single-element-style-array",
    id: "rn-no-single-element-style-array",
    source: "react-doctor",
    originallyExternal: false,
    framework: "react-native",
    category: "React Native",
    severity: "warn",
    rule: {
      ...rnNoSingleElementStyleArray,
      framework: "react-native",
      category: "React Native",
      requires: [...new Set(["react-native", ...(rnNoSingleElementStyleArray.requires ?? [])])],
      tags: [...new Set(["react-native", ...(rnNoSingleElementStyleArray.tags ?? [])])],
    },
  },
  {
    key: "react-doctor/rn-prefer-content-inset-adjustment",
    id: "rn-prefer-content-inset-adjustment",
    source: "react-doctor",
    originallyExternal: false,
    framework: "react-native",
    category: "React Native",
    severity: "warn",
    rule: {
      ...rnPreferContentInsetAdjustment,
      framework: "react-native",
      category: "React Native",
      requires: [...new Set(["react-native", ...(rnPreferContentInsetAdjustment.requires ?? [])])],
      tags: [...new Set(["react-native", ...(rnPreferContentInsetAdjustment.tags ?? [])])],
    },
  },
  {
    key: "react-doctor/rn-prefer-expo-image",
    id: "rn-prefer-expo-image",
    source: "react-doctor",
    originallyExternal: false,
    framework: "react-native",
    category: "React Native",
    severity: "warn",
    rule: {
      ...rnPreferExpoImage,
      framework: "react-native",
      category: "React Native",
      requires: [...new Set(["react-native", ...(rnPreferExpoImage.requires ?? [])])],
      tags: [...new Set(["react-native", ...(rnPreferExpoImage.tags ?? [])])],
    },
  },
  {
    key: "react-doctor/rn-prefer-pressable",
    id: "rn-prefer-pressable",
    source: "react-doctor",
    originallyExternal: false,
    framework: "react-native",
    category: "React Native",
    severity: "warn",
    rule: {
      ...rnPreferPressable,
      framework: "react-native",
      category: "React Native",
      requires: [...new Set(["react-native", ...(rnPreferPressable.requires ?? [])])],
      tags: [...new Set(["react-native", ...(rnPreferPressable.tags ?? [])])],
    },
  },
  {
    key: "react-doctor/rn-prefer-reanimated",
    id: "rn-prefer-reanimated",
    source: "react-doctor",
    originallyExternal: false,
    framework: "react-native",
    category: "React Native",
    severity: "warn",
    rule: {
      ...rnPreferReanimated,
      framework: "react-native",
      category: "React Native",
      requires: [...new Set(["react-native", ...(rnPreferReanimated.requires ?? [])])],
      tags: [...new Set(["react-native", ...(rnPreferReanimated.tags ?? [])])],
    },
  },
  {
    key: "react-doctor/rn-pressable-shared-value-mutation",
    id: "rn-pressable-shared-value-mutation",
    source: "react-doctor",
    originallyExternal: false,
    framework: "react-native",
    category: "React Native",
    severity: "warn",
    rule: {
      ...rnPressableSharedValueMutation,
      framework: "react-native",
      category: "React Native",
      requires: [...new Set(["react-native", ...(rnPressableSharedValueMutation.requires ?? [])])],
      tags: [...new Set(["react-native", ...(rnPressableSharedValueMutation.tags ?? [])])],
    },
  },
  {
    key: "react-doctor/rn-scrollview-dynamic-padding",
    id: "rn-scrollview-dynamic-padding",
    source: "react-doctor",
    originallyExternal: false,
    framework: "react-native",
    category: "React Native",
    severity: "warn",
    rule: {
      ...rnScrollviewDynamicPadding,
      framework: "react-native",
      category: "React Native",
      requires: [...new Set(["react-native", ...(rnScrollviewDynamicPadding.requires ?? [])])],
      tags: [...new Set(["react-native", ...(rnScrollviewDynamicPadding.tags ?? [])])],
    },
  },
  {
    key: "react-doctor/rn-style-prefer-boxshadow",
    id: "rn-style-prefer-boxshadow",
    source: "react-doctor",
    originallyExternal: false,
    framework: "react-native",
    category: "React Native",
    severity: "warn",
    rule: {
      ...rnStylePreferBoxShadow,
      framework: "react-native",
      category: "React Native",
      requires: [...new Set(["react-native", ...(rnStylePreferBoxShadow.requires ?? [])])],
      tags: [...new Set(["react-native", ...(rnStylePreferBoxShadow.tags ?? [])])],
    },
  },
] as const;
