export const MAX_SHADOWED_POINT_LIGHT_COUNT = 2;
export const MINIMUM_PROVABLY_REPEATED_ITEM_COUNT = 2;
export const LIFECYCLE_ANALYSIS_PERFORMANCE_ALLOCATION_COUNT = 2_000;
export const LIFECYCLE_ANALYSIS_PERFORMANCE_BUDGET_MS = 2_000;
export const LIFECYCLE_ANALYSIS_DENSE_EFFECT_COUNT = 800;
export const LIFECYCLE_ANALYSIS_DENSE_EFFECT_BUDGET_MS = 2_500;
