packages:
  - "packages/*"

minimumReleaseAge: 7200
minimumReleaseAgeExclude:
  - "@oxc-parser/*"
  - "@oxc-project/*"
  - "@oxc-resolver/*"
  - "@oxlint-tsgolint/*"
  - "@oxlint/*"
  - "oxc-*"
  - "oxlint"
  - "oxlint-*"
trustPolicy: no-downgrade
blockExoticSubdeps: true

overrides:
  vite: npm:@voidzero-dev/vite-plus-core@^0.1.15
  vitest: npm:@voidzero-dev/vite-plus-test@^0.1.15
