// Ported from `oxc_linter::rules::react::no_unknown_property::ATTRIBUTE_TAGS_MAP`.
// Maps a DOM attribute (camelCase or hyphenated, exactly as React expects)
// to the set of HTML/SVG element tag names where that attribute is valid.
// Used by `react-builtins/no-unknown-property` to flag e.g.
// `<div fetchPriority="high">` (allowed only on `<img|link|script>`).
export const DOM_PROPERTY_TO_ALLOWED_TAGS: ReadonlyMap<string, ReadonlySet<string>> = new Map([
  ["abbr", new Set(["th", "td"])],
  ["charset", new Set(["meta"])],
  ["checked", new Set(["input"])],
  ["closedby", new Set(["dialog"])],
  ["crossOrigin", new Set(["script", "img", "video", "audio", "link", "image"])],
  ["displaystyle", new Set(["math"])],
  ["download", new Set(["a", "area"])],
  ["fetchPriority", new Set(["img", "link", "script"])],
  [
    "fill",
    new Set([
      "altGlyph",
      "circle",
      "ellipse",
      "g",
      "line",
      "marker",
      "mask",
      "path",
      "polygon",
      "polyline",
      "rect",
      "svg",
      "symbol",
      "text",
      "textPath",
      "tref",
      "tspan",
      "use",
      "animate",
      "animateColor",
      "animateMotion",
      "animateTransform",
      "set",
    ]),
  ],
  ["focusable", new Set(["svg"])],
  ["imageSizes", new Set(["link"])],
  ["imageSrcSet", new Set(["link"])],
  ["property", new Set(["meta"])],
  ["popoverTarget", new Set(["button", "input"])],
  ["popoverTargetAction", new Set(["button", "input"])],
  ["viewBox", new Set(["marker", "pattern", "svg", "symbol", "view"])],
  ["as", new Set(["link"])],
  [
    "align",
    new Set([
      "applet",
      "caption",
      "col",
      "colgroup",
      "hr",
      "iframe",
      "img",
      "table",
      "tbody",
      "td",
      "tfoot",
      "th",
      "thead",
      "tr",
    ]),
  ],
  ["valign", new Set(["tr", "td", "th", "thead", "tbody", "tfoot", "colgroup", "col"])],
  ["noModule", new Set(["script"])],
  ["onAbort", new Set(["audio", "video"])],
  ["onCancel", new Set(["dialog"])],
  ["onCanPlay", new Set(["audio", "video"])],
  ["onCanPlayThrough", new Set(["audio", "video"])],
  ["onClose", new Set(["dialog"])],
  ["onDurationChange", new Set(["audio", "video"])],
  ["onEmptied", new Set(["audio", "video"])],
  ["onEncrypted", new Set(["audio", "video"])],
  ["onEnded", new Set(["audio", "video"])],
  ["onError", new Set(["audio", "video", "img", "link", "source", "script", "picture", "iframe"])],
  ["onLoad", new Set(["script", "img", "link", "picture", "iframe", "object", "source", "body"])],
  ["onLoadedData", new Set(["audio", "video"])],
  ["onLoadedMetadata", new Set(["audio", "video"])],
  ["onLoadStart", new Set(["audio", "video"])],
  ["onPause", new Set(["audio", "video"])],
  ["onPlay", new Set(["audio", "video"])],
  ["onPlaying", new Set(["audio", "video"])],
  ["onProgress", new Set(["audio", "video"])],
  ["onRateChange", new Set(["audio", "video"])],
  ["onResize", new Set(["audio", "video"])],
  ["onSeeked", new Set(["audio", "video"])],
  ["onSeeking", new Set(["audio", "video"])],
  ["onStalled", new Set(["audio", "video"])],
  ["onSuspend", new Set(["audio", "video"])],
  ["onTimeUpdate", new Set(["audio", "video"])],
  ["onVolumeChange", new Set(["audio", "video"])],
  ["onWaiting", new Set(["audio", "video"])],
  ["autoPictureInPicture", new Set(["video"])],
  ["controls", new Set(["audio", "video"])],
  ["controlsList", new Set(["audio", "video"])],
  ["disablePictureInPicture", new Set(["video"])],
  ["disableRemotePlayback", new Set(["audio", "video"])],
  ["loop", new Set(["audio", "video"])],
  ["muted", new Set(["audio", "video"])],
  ["playsInline", new Set(["video"])],
  ["allowFullScreen", new Set(["iframe", "video"])],
  ["webkitAllowFullScreen", new Set(["iframe", "video"])],
  ["mozAllowFullScreen", new Set(["iframe", "video"])],
  ["poster", new Set(["video"])],
  ["preload", new Set(["audio", "video"])],
  ["scrolling", new Set(["iframe"])],
  ["returnValue", new Set(["dialog"])],
  ["webkitDirectory", new Set(["input"])],
  ["shadowrootmode", new Set(["template"])],
  ["shadowrootclonable", new Set(["template"])],
  ["shadowrootdelegatesfocus", new Set(["template"])],
  ["shadowrootserializable", new Set(["template"])],
  [
    // A presentation/CSS attribute valid on every transformable SVG
    // element, not just `<rect>`.
    "transform-origin",
    new Set([
      "a",
      "circle",
      "clipPath",
      "defs",
      "ellipse",
      "foreignObject",
      "g",
      "image",
      "line",
      "linearGradient",
      "marker",
      "mask",
      "path",
      "pattern",
      "polygon",
      "polyline",
      "radialGradient",
      "rect",
      "stop",
      "svg",
      "switch",
      "symbol",
      "text",
      "textPath",
      "tspan",
      "use",
    ]),
  ],
  ["precedence", new Set(["style", "link"])],
]);
