export const MINIMUM_CARD_PADDING_SCALE = 2;
export const SHAPE_ASSEMBLED_ILLUSTRATION_MINIMUM_SIZE_PX = 200;
export const SHAPE_ASSEMBLED_ILLUSTRATION_MINIMUM_PRIMITIVE_COUNT = 8;
export const SHAPE_ASSEMBLED_ILLUSTRATION_MINIMUM_DISTINCT_FILL_COUNT = 3;
export const SHAPE_ASSEMBLED_ILLUSTRATION_MAXIMUM_TEXT_ELEMENT_COUNT = 2;
