export const VIDEO_WIDTH_PX = 1920;
export const VIDEO_HEIGHT_PX = 1080;
export const VIDEO_FPS = 30;

export const BACKGROUND_COLOR = "#0a0a0a";
export const TEXT_COLOR = "#d4d4d8";
export const MUTED_COLOR = "#737373";
export const RED_COLOR = "#f87171";
export const GREEN_COLOR = "#4ade80";
export const YELLOW_COLOR = "#eab308";

export const ERROR_ROW_BACKGROUND_COLOR = "rgba(127, 29, 29, 0.28)";
export const ERROR_BADGE_BACKGROUND_COLOR = "#dc2626";
export const ERROR_BADGE_TEXT_COLOR = "#fafafa";
export const WARNING_BADGE_BACKGROUND_COLOR = "#a16207";

export const FILE_ROW_HORIZONTAL_PADDING_PX = 24;
export const FILE_ROW_VERTICAL_PADDING_PX = 4;
export const FILE_ROW_GAP_PX = 24;
export const LINE_NUMBER_COLUMN_WIDTH_PX = 90;
export const SEVERITY_BADGE_SIZE_PX = 44;
export const SEVERITY_BADGE_RADIUS_PX = 6;
export const POINTS_LOST_COLUMN_WIDTH_PX = 140;
export const OVERLAY_GRADIENT_RGB = "10, 10, 10";
export const OVERLAY_GRADIENT_HEIGHT_PX = 400;
export const OVERLAY_GRADIENT_HORIZONTAL_PADDING_PX = 120;
export const OVERLAY_GRADIENT_BOTTOM_PADDING_PX = 80;
export const OVERLAY_GRADIENT_BOTTOM_ALPHA = 0.96;
export const OVERLAY_GRADIENT_MIDDLE_ALPHA = 0.85;
export const OVERLAY_GRADIENT_MIDDLE_STOP_PERCENT = 50;

export const COMMAND = "npx react-doctor@latest";
export const REACT_DOCTOR_URL = "https://react.doctor";
export const CONTENT_WIDTH_PX = 1400;

export const TYPING_FONT_SIZE_PX = 100;
export const TYPING_CHAR_WIDTH_PX = 60;
export const CHAR_FRAMES = 1;
export const CURSOR_BLINK_FRAMES = 16;
export const TYPING_INITIAL_DELAY_FRAMES = 10;
export const TYPING_POST_PAUSE_FRAMES = 24;
export const TYPING_PAN_THRESHOLD_PX = CONTENT_WIDTH_PX * 0.6;

export const FILE_SCAN_FONT_SIZE_PX = 48;
export const FRAMES_PER_FILE = 2;
export const FILE_SCAN_INITIAL_DELAY_FRAMES = 5;
export const FILE_SCAN_VISIBLE_ROWS = 14;

export const DIAGNOSTIC_FONT_SIZE_PX = 28;
export const DIAGNOSTIC_LINE_HEIGHT = 1.7;
export const FRAMES_PER_DIAGNOSTIC = 4;
export const DIAGNOSTIC_INITIAL_DELAY_FRAMES = 15;
export const SCORE_PAUSE_FRAMES = 18;
export const SCORE_ANIMATION_FRAMES = 20;
export const POST_SCORE_PAUSE_FRAMES = 21;
export const TARGET_SCORE = 42;
export const PERFECT_SCORE = 100;
export const TOTAL_ERROR_COUNT = 22;
export const AFFECTED_FILE_COUNT = 18;
export const ELAPSED_TIME = "2.1s";
export const SCORE_BAR_WIDTH = 30;
export const SCORE_GOOD_THRESHOLD = 75;
export const SCORE_OK_THRESHOLD = 50;

export const FRAMES_PER_FIX = 20;
export const FIX_INITIAL_DELAY_FRAMES = 15;

export const SCENE_TYPING_DURATION_FRAMES = 70;
export const SCENE_FILE_SCAN_DURATION_FRAMES = 80;
export const SCENE_DIAGNOSE_AND_FIX_DURATION_FRAMES = 175;
export const SCENE_SCORE_REVEAL_DURATION_FRAMES = 110;
export const TRANSITION_DURATION_FRAMES = 15;

export const TOTAL_DURATION =
  SCENE_TYPING_DURATION_FRAMES +
  SCENE_FILE_SCAN_DURATION_FRAMES +
  SCENE_DIAGNOSE_AND_FIX_DURATION_FRAMES +
  SCENE_SCORE_REVEAL_DURATION_FRAMES -
  TRANSITION_DURATION_FRAMES * 2;

export const SECURITY_INTRO_DURATION_FRAMES = 65;
export const SECURITY_SCAN_DURATION_FRAMES = 110;
export const SECURITY_FIX_DURATION_FRAMES = 115;
export const SECURITY_TOTAL_DURATION =
  SECURITY_INTRO_DURATION_FRAMES +
  SECURITY_SCAN_DURATION_FRAMES +
  SECURITY_FIX_DURATION_FRAMES +
  SCENE_SCORE_REVEAL_DURATION_FRAMES -
  TRANSITION_DURATION_FRAMES * 2;
