import { describe, expect, it } from "vite-plus/test";
import {
  assembleInspectOutput,
  type AssembleInspectOutputInput,
} from "../src/assemble-inspect-output.js";
import type { Diagnostic, ProjectInfo } from "../src/types/index.js";

const project: ProjectInfo = {
  rootDirectory: "/repo",
  projectName: "sample-app",
  reactVersion: "19.0.0",
  reactMajorVersion: 19,
  tailwindVersion: null,
  zodVersion: null,
  zodMajorVersion: null,
  framework: "vite",
  hasTypeScript: true,
  hasReactCompiler: false,
  hasI18nLibrary: false,
  tanstackQueryVersion: null,
  mobxVersion: null,
  styledComponentsVersion: null,
  nextjsVersion: null,
  nextjsMajorVersion: null,
  hasReactNativeWorkspace: false,
  expoVersion: null,
  shopifyFlashListVersion: null,
  shopifyFlashListMajorVersion: null,
  hasReanimated: false,
  isPreES2023Target: false,
  preactVersion: null,
  preactMajorVersion: null,
  sourceFileCount: 2,
};

const diagnostic: Diagnostic = {
  filePath: "/repo/src/app.tsx",
  plugin: "react-doctor",
  rule: "no-derived-state",
  severity: "error",
  message: "Avoid derived state.",
  help: "Use the value directly.",
  line: 1,
  column: 1,
  category: "Correctness",
};

const completeInput: AssembleInspectOutputInput = {
  project,
  userConfig: null,
  resolvedDirectory: "/repo",
  diagnostics: [diagnostic],
  score: { score: 85, label: "Good" },
  scoreMetadata: {
    repo: "millionco/sample-app",
    sha: "abc123",
    framework: "vite",
    reactVersion: "19.0.0",
    sourceFileCount: 2,
    defaultBranch: "main",
  },
  lint: {
    didFail: false,
    failureReason: null,
    failureReasonTag: null,
    failureReasonKind: null,
    partialFailures: [],
    analyzedFiles: ["src/app.tsx", "src/other.tsx"],
    cacheHitFileCount: 1,
    cacheTotalFileCount: 2,
    sidecarReplayedFileCount: 1,
    sidecarTotalFileCount: 1,
  },
  deadCode: {
    didFail: false,
    failureReason: null,
    didOverlap: true,
    cacheHit: false,
    summaryCacheHits: 4,
    summaryCacheMisses: 2,
  },
  scan: {
    scannedFileCount: 2,
    scannedFilePaths: ["/repo/src/app.tsx", "/repo/src/other.tsx"],
    elapsedMilliseconds: 125,
    concurrency: 4,
  },
  supplyChainOverlapTimedOut: false,
  securityScanFailed: false,
  suppressedRuleCounts: [{ rule: "react-doctor/no-debugger", source: "inline", count: 3 }],
};

describe("assembleInspectOutput", () => {
  it("assembles the exact completed scan contract", () => {
    expect(assembleInspectOutput(completeInput)).toEqual({
      project,
      userConfig: null,
      resolvedDirectory: "/repo",
      diagnostics: [diagnostic],
      score: { score: 85, label: "Good" },
      scoreMetadata: {
        repo: "millionco/sample-app",
        sha: "abc123",
        framework: "vite",
        reactVersion: "19.0.0",
        sourceFileCount: 2,
        defaultBranch: "main",
      },
      didLintFail: false,
      lintFailureReason: null,
      lintFailureReasonTag: null,
      lintFailureReasonKind: null,
      lintPartialFailures: [],
      didDeadCodeFail: false,
      deadCodeFailureReason: null,
      deadCodeOverlapped: true,
      scannedFileCount: 2,
      scannedFilePaths: ["/repo/src/app.tsx", "/repo/src/other.tsx"],
      analyzedFiles: ["src/app.tsx", "src/other.tsx"],
      scanElapsedMilliseconds: 125,
      scanConcurrency: 4,
      supplyChainOverlapTimedOut: false,
      securityScanFailed: false,
      lintCacheHitFileCount: 1,
      lintCacheTotalFileCount: 2,
      lintSidecarReplayedFileCount: 1,
      lintSidecarTotalFileCount: 1,
      deadCodeCacheHit: false,
      deadCodeSummaryCacheHits: 4,
      deadCodeSummaryCacheMisses: 2,
      suppressedRuleCounts: [{ rule: "react-doctor/no-debugger", source: "inline", count: 3 }],
    });
  });

  it("preserves partial lint details and clears discarded dead-code cache outcomes", () => {
    const output = assembleInspectOutput({
      ...completeInput,
      diagnostics: [],
      score: null,
      lint: {
        ...completeInput.lint,
        didFail: true,
        failureReason: "oxlint exited before every batch completed",
        failureReasonTag: "OxlintSpawnFailed",
        partialFailures: ["React Hooks rules were skipped"],
        analyzedFiles: ["src/app.tsx"],
      },
      deadCode: {
        ...completeInput.deadCode,
        didOverlap: false,
      },
      supplyChainOverlapTimedOut: true,
      securityScanFailed: true,
    });

    expect(output).toEqual({
      project,
      userConfig: null,
      resolvedDirectory: "/repo",
      diagnostics: [],
      score: null,
      scoreMetadata: completeInput.scoreMetadata,
      didLintFail: true,
      lintFailureReason: "oxlint exited before every batch completed",
      lintFailureReasonTag: "OxlintSpawnFailed",
      lintFailureReasonKind: null,
      lintPartialFailures: ["React Hooks rules were skipped"],
      didDeadCodeFail: false,
      deadCodeFailureReason: null,
      deadCodeOverlapped: false,
      scannedFileCount: 2,
      scannedFilePaths: ["/repo/src/app.tsx", "/repo/src/other.tsx"],
      analyzedFiles: ["src/app.tsx"],
      scanElapsedMilliseconds: 125,
      scanConcurrency: 4,
      supplyChainOverlapTimedOut: true,
      securityScanFailed: true,
      lintCacheHitFileCount: 1,
      lintCacheTotalFileCount: 2,
      lintSidecarReplayedFileCount: 1,
      lintSidecarTotalFileCount: 1,
      deadCodeCacheHit: null,
      deadCodeSummaryCacheHits: null,
      deadCodeSummaryCacheMisses: null,
      suppressedRuleCounts: [{ rule: "react-doctor/no-debugger", source: "inline", count: 3 }],
    });
  });
});
