import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { afterEach, describe, expect, it } from "vite-plus/test";
import { analyzeProject } from "../src/project-analysis/analyze-project.js";

const temporaryDirectories: string[] = [];

afterEach(() => {
  for (const directory of temporaryDirectories.splice(0)) {
    fs.rmSync(directory, { recursive: true, force: true });
  }
});

const createProject = (
  files: Readonly<Record<string, string>>,
  packageJson: Readonly<Record<string, unknown>> = {},
): string => {
  const rootDirectory = fs.mkdtempSync(path.join(os.tmpdir(), "react-doctor-runtime-discovery-"));
  temporaryDirectories.push(rootDirectory);
  fs.writeFileSync(path.join(rootDirectory, "package.json"), JSON.stringify(packageJson));
  for (const [relativePath, source] of Object.entries(files)) {
    const filePath = path.join(rootDirectory, relativePath);
    fs.mkdirSync(path.dirname(filePath), { recursive: true });
    fs.writeFileSync(filePath, source);
  }
  return fs.realpathSync(rootDirectory);
};

const relativeUnusedPaths = (
  rootDirectory: string,
  unusedFiles: ReadonlyArray<{ readonly path: string }>,
): string[] =>
  unusedFiles.map((unusedFile) =>
    path.relative(rootDirectory, unusedFile.path).replaceAll("\\", "/"),
  );

describe("runtime-discovered project entries", () => {
  it("links source files consumed through generated unplugin auto imports", async () => {
    const rootDirectory = createProject(
      {
        "vite.config.ts": `
          import AutoImport from 'unplugin-auto-import/vite';
          export default { plugins: [AutoImport({ eslintrc: { enabled: true } })] };
        `,
        ".eslintrc-auto-import.json": JSON.stringify({
          globals: { useFeature: "readonly", useDormant: "readonly" },
        }),
        "src/index.tsx": "export const App = () => useFeature();",
        "src/hooks/use-feature.ts": "export const useFeature = () => true;",
        "src/hooks/use-dormant.ts": "export const useDormant = () => false;",
        "src/types/auto-imports.d.ts": `
          // Generated by unplugin-auto-import
          declare global {
            const useFeature: typeof import('../hooks/use-feature')['useFeature'];
            const useDormant: typeof import('../hooks/use-dormant')['useDormant'];
          }
        `,
      },
      { dependencies: { react: "1.0.0" }, devDependencies: { "unplugin-auto-import": "1.0.0" } },
    );

    const result = await analyzeProject({ rootDirectory, entryPatterns: ["src/index.tsx"] });

    expect(relativeUnusedPaths(rootDirectory, result.unusedFiles)).toEqual([
      "src/hooks/use-dormant.ts",
    ]);
  });

  it("retains identical generated auto-import bindings and rejects conflicts", async () => {
    const rootDirectory = createProject(
      {
        "vite.config.ts": `
          import AutoImport from 'unplugin-auto-import/vite';
          export default { plugins: [AutoImport({ eslintrc: { enabled: true } })] };
        `,
        ".eslintrc-auto-import.json": JSON.stringify({
          globals: { useFeature: "readonly", useConflict: "readonly" },
        }),
        "src/index.ts": "export const result = [useFeature(), useConflict()];",
        "src/hooks/use-feature.ts": "export const useFeature = () => true;",
        "src/hooks/use-conflict-a.ts": "export const useConflict = () => 'a';",
        "src/hooks/use-conflict-b.ts": "export const useConflict = () => 'b';",
        "src/types/auto-imports.d.ts": `
          // Generated by unplugin-auto-import
          declare global {
            const useFeature: typeof import('../hooks/use-feature')['useFeature'];
            const useConflict: typeof import('../hooks/use-conflict-a')['useConflict'];
          }
        `,
        "src/generated/auto-imports.d.ts": `
          // Generated by unplugin-auto-import
          declare global {
            const useFeature: typeof import('../hooks/use-feature')['useFeature'];
            const useConflict: typeof import('../hooks/use-conflict-b')['useConflict'];
          }
        `,
      },
      { dependencies: { react: "1.0.0" }, devDependencies: { "unplugin-auto-import": "1.0.0" } },
    );

    const result = await analyzeProject({ rootDirectory, entryPatterns: ["src/index.ts"] });

    expect(relativeUnusedPaths(rootDirectory, result.unusedFiles)).toEqual([
      "src/hooks/use-conflict-a.ts",
      "src/hooks/use-conflict-b.ts",
    ]);
  });

  it("resolves unplugin auto imports with lexical bindings and reference positions", async () => {
    const rootDirectory = createProject(
      {
        "vite.config.ts": `
          import AutoImport from 'unplugin-auto-import/vite';
          export default { plugins: [AutoImport({ eslintrc: { enabled: true } })] };
        `,
        ".eslintrc-auto-import.json": JSON.stringify({
          globals: {
            ref: "readonly",
            scopedRef: "readonly",
            localRef: "readonly",
            propertyRef: "readonly",
            shorthandRef: "readonly",
          },
        }),
        "src/index.ts": `
          const object = { ref: true, propertyRef: true };
          object.ref;
          object.propertyRef;
          const { propertyRef } = object;
          ref();
          const values = { shorthandRef };
          const inside = (scopedRef: () => void) => scopedRef();
          scopedRef();
          const local = (localRef: () => void) => localRef();
          console.log(inside, local, propertyRef, values);
        `,
        "src/globals/ref.ts": "export const ref = () => true;",
        "src/globals/scoped-ref.ts": "export const scopedRef = () => true;",
        "src/globals/local-ref.ts": "export const localRef = () => true;",
        "src/globals/property-ref.ts": "export const propertyRef = () => true;",
        "src/globals/shorthand-ref.ts": "export const shorthandRef = () => true;",
        "src/types/auto-imports.d.ts": `
          // Generated by unplugin-auto-import
          declare global {
            const ref: typeof import('../globals/ref')['ref'];
            const scopedRef: typeof import('../globals/scoped-ref')['scopedRef'];
            const localRef: typeof import('../globals/local-ref')['localRef'];
            const propertyRef: typeof import('../globals/property-ref')['propertyRef'];
            const shorthandRef: typeof import('../globals/shorthand-ref')['shorthandRef'];
          }
        `,
      },
      { dependencies: { react: "1.0.0" }, devDependencies: { "unplugin-auto-import": "1.0.0" } },
    );

    const result = await analyzeProject({ rootDirectory, entryPatterns: ["src/index.ts"] });

    expect(relativeUnusedPaths(rootDirectory, result.unusedFiles)).toEqual([
      "src/globals/local-ref.ts",
      "src/globals/property-ref.ts",
    ]);
  });

  it("does not trust stale generated auto-import declarations", async () => {
    const rootDirectory = createProject(
      {
        "src/index.tsx": "export const App = () => useFeature();",
        "src/hooks/use-feature.ts": "export const useFeature = () => true;",
        "src/types/auto-imports.d.ts": `
          // Generated by unplugin-auto-import
          declare global {
            const useFeature: typeof import('../hooks/use-feature')['useFeature'];
          }
        `,
      },
      { dependencies: { react: "1.0.0" }, devDependencies: { "unplugin-auto-import": "1.0.0" } },
    );

    const result = await analyzeProject({ rootDirectory, entryPatterns: ["src/index.tsx"] });

    expect(relativeUnusedPaths(rootDirectory, result.unusedFiles)).toEqual([
      "src/hooks/use-feature.ts",
    ]);
  });

  it("keeps generated auto-import bindings inside their active workspace scope", async () => {
    const generatedDeclaration = `
      // Generated by unplugin-auto-import
      declare global {
        const useFeature: typeof import('../hooks/use-feature')['useFeature'];
      }
    `;
    const rootDirectory = createProject(
      {
        "packages/active/package.json": JSON.stringify({ name: "active" }),
        "packages/active/vite.config.ts": `
          import AutoImport from 'unplugin-auto-import/vite';
          export default { plugins: [AutoImport({ eslintrc: { enabled: true } })] };
        `,
        "packages/active/.eslintrc-auto-import.json": JSON.stringify({
          globals: { useFeature: "readonly" },
        }),
        "packages/active/src/index.ts": "export const active = useFeature();",
        "packages/active/src/hooks/use-feature.ts": "export const useFeature = () => true;",
        "packages/active/src/types/auto-imports.d.ts": generatedDeclaration,
        "packages/stale/package.json": JSON.stringify({ name: "stale" }),
        "packages/stale/src/index.ts": "export const stale = useFeature();",
        "packages/stale/src/hooks/use-feature.ts": "export const useFeature = () => false;",
        "packages/stale/src/types/auto-imports.d.ts": generatedDeclaration,
      },
      {
        workspaces: ["packages/*"],
        devDependencies: { "unplugin-auto-import": "1.0.0" },
      },
    );

    const result = await analyzeProject({
      rootDirectory,
      entryPatterns: ["packages/*/src/index.ts"],
    });

    expect(relativeUnusedPaths(rootDirectory, result.unusedFiles)).toEqual([
      "packages/stale/src/hooks/use-feature.ts",
    ]);
  });

  it("credits only static Next config loader calls, not unrelated strings", async () => {
    const rootDirectory = createProject(
      {
        "next.config.mjs": `
          import { createJiti } from "jiti";
          const runtimeLoader = createJiti(import.meta.url);
          await runtimeLoader.import("./src/runtime-schema.ts");
          const loadModule = (source) => source;
          loadModule("./src/orphan.ts");
          export default { env: { UNUSED_SOURCE: "./src/orphan.ts" } };
        `,
        "src/index.ts": "export const entry = true;",
        "src/runtime-schema.ts": "export const schema = true;",
        "src/orphan.ts": "export const orphan = true;",
      },
      { dependencies: { jiti: "1.0.0", next: "1.0.0", react: "1.0.0" } },
    );

    const result = await analyzeProject({ rootDirectory, entryPatterns: ["src/index.ts"] });

    expect(relativeUnusedPaths(rootDirectory, result.unusedFiles)).toEqual(["src/orphan.ts"]);
    expect(result.unusedExports).not.toContainEqual(expect.objectContaining({ name: "schema" }));
  });

  it("keeps Jiti loader resolution lexical", async () => {
    const rootDirectory = createProject(
      {
        "next.config.mjs": `
          import { createJiti } from "jiti";
          const runtimeLoader = createJiti(import.meta.url);
          await runtimeLoader.import("./src/runtime-schema.ts");
          const runOrdinaryLoader = (runtimeLoader) => runtimeLoader("./src/orphan.ts");
          runOrdinaryLoader((source) => source);
          export default {};
        `,
        "src/index.ts": "export const entry = true;",
        "src/runtime-schema.ts": "export const schema = true;",
        "src/orphan.ts": "export const orphan = true;",
      },
      { dependencies: { jiti: "1.0.0", next: "1.0.0", react: "1.0.0" } },
    );

    const result = await analyzeProject({ rootDirectory, entryPatterns: ["src/index.ts"] });

    expect(relativeUnusedPaths(rootDirectory, result.unusedFiles)).toEqual(["src/orphan.ts"]);
    expect(result.unusedExports).not.toContainEqual(expect.objectContaining({ name: "schema" }));
  });

  it("does not report exports when a genuine Jiti target is computed", async () => {
    const rootDirectory = createProject(
      {
        "src/index.ts": `
          import "./schema";
          import { createJiti } from "jiti";
          const runtimeLoader = createJiti(import.meta.url);
          runtimeLoader.import(process.env.RUNTIME_MODULE).then((loadedModule) => loadedModule.special);
        `,
        "src/schema.ts": "export const special = true;",
      },
      { dependencies: { jiti: "1.0.0" } },
    );

    const result = await analyzeProject({ rootDirectory, entryPatterns: ["src/index.ts"] });

    expect(result.unusedExports).toEqual([]);
  });

  it("credits CommonJS Jiti calls in Next config without promoting ordinary helpers", async () => {
    const rootDirectory = createProject(
      {
        "next.config.js": `
          const jiti = require("jiti")(__filename);
          const { loadModule } = require("./config-helper");
          jiti("./src/runtime-schema.ts");
          loadModule("./src/ordinary-helper-target.ts");
          module.exports = {};
        `,
        "config-helper.js": "exports.loadModule = (value) => value;",
        "src/index.ts": "export const entry = true;",
        "src/runtime-schema.ts": "export const schema = true;",
        "src/ordinary-helper-target.ts": "export const helperTarget = true;",
        "src/orphan.ts": "export const orphan = true;",
      },
      { dependencies: { jiti: "1.0.0", next: "1.0.0", react: "1.0.0" } },
    );

    const result = await analyzeProject({ rootDirectory, entryPatterns: ["src/index.ts"] });

    expect(relativeUnusedPaths(rootDirectory, result.unusedFiles)).toEqual([
      "src/ordinary-helper-target.ts",
      "src/orphan.ts",
    ]);
  });

  it("discovers the configured React Email preview directory", async () => {
    const rootDirectory = createProject(
      {
        "src/templates/updates/launch.tsx": "export default () => null;",
        "src/templates/_components/frame.tsx": "export default () => null;",
        "src/orphan.ts": "export const orphan = true;",
      },
      {
        scripts: { dev: "email dev --dir ./src/templates -p 3333" },
        devDependencies: { "react-email": "1.0.0" },
      },
    );

    const result = await analyzeProject({
      rootDirectory,
      entryPatterns: ["src/templates/**/!(_components)/*.tsx"],
    });

    expect(relativeUnusedPaths(rootDirectory, result.unusedFiles)).toEqual([
      "src/orphan.ts",
      "src/templates/_components/frame.tsx",
    ]);
  });

  it("discovers a quoted React Email preview directory", async () => {
    const rootDirectory = createProject(
      {
        "email templates/welcome.tsx": "export default () => null;",
        "src/orphan.ts": "export const orphan = true;",
      },
      {
        scripts: { dev: `email dev --dir "email templates"` },
        devDependencies: { "react-email": "1.0.0" },
      },
    );

    const result = await analyzeProject({ rootDirectory, entryPatterns: [] });

    expect(relativeUnusedPaths(rootDirectory, result.unusedFiles)).toEqual(["src/orphan.ts"]);
  });

  it("keeps the default React Email preview directory exact", async () => {
    const rootDirectory = createProject(
      {
        "emails/welcome.tsx": "export default () => null;",
        "emails/helper.ts": "export const helper = true;",
        "email-templates/misspelled.tsx": "export default () => null;",
      },
      {
        scripts: { dev: "email dev" },
        devDependencies: { "react-email": "1.0.0" },
      },
    );

    const result = await analyzeProject({ rootDirectory, entryPatterns: ["emails/**/*.tsx"] });

    expect(relativeUnusedPaths(rootDirectory, result.unusedFiles)).toEqual([
      "email-templates/misspelled.tsx",
      "emails/helper.ts",
    ]);
  });

  it("discovers React Email templates through default export aliases", async () => {
    const rootDirectory = createProject(
      {
        "emails/welcome.tsx": `
          const Welcome = () => null;
          export { Welcome as default };
        `,
        "emails/comment-only.tsx": `
          // export default () => null;
          export const helper = true;
        `,
      },
      {
        scripts: { dev: "email dev" },
        devDependencies: { "react-email": "1.0.0" },
      },
    );

    const result = await analyzeProject({ rootDirectory, entryPatterns: [] });

    expect(relativeUnusedPaths(rootDirectory, result.unusedFiles)).toEqual([
      "emails/comment-only.tsx",
    ]);
  });

  it("maps sibling workspace imports from missing build output to source", async () => {
    const monorepoDirectory = createProject(
      {
        "packages/library/package.json": JSON.stringify({
          name: "@example/library",
          main: "./lib/index.js",
        }),
        "packages/library/src/index.ts": "export const root = true;",
        "packages/library/src/utils/transaction.ts": "export const transaction = true;",
        "packages/library/src/orphan.ts": "export const orphan = true;",
        "packages/app/package.json": JSON.stringify({ name: "@example/app" }),
        "packages/app/src/index.ts": `import { transaction } from "@example/library/lib/utils/transaction"; console.log(transaction);`,
      },
      { private: true, workspaces: ["packages/*"] },
    );

    const libraryDirectory = path.join(monorepoDirectory, "packages/library");
    const result = await analyzeProject({
      rootDirectory: libraryDirectory,
      entryPatterns: ["src/index.ts"],
    });

    expect(relativeUnusedPaths(libraryDirectory, result.unusedFiles)).toEqual(["src/orphan.ts"]);
  });

  it("prefers an exact sibling workspace target over a source fallback", async () => {
    const monorepoDirectory = createProject(
      {
        "packages/library/package.json": JSON.stringify({
          name: "@example/library",
          exports: { "./lib/foo": "./lib/foo.js" },
        }),
        "packages/library/src/index.ts": "export const root = true;",
        "packages/library/lib/foo.js": "export const compiled = true;",
        "packages/library/src/foo.ts": "export const unrelated = true;",
        "packages/app/package.json": JSON.stringify({ name: "@example/app" }),
        "packages/app/src/index.ts": 'import "@example/library/lib/foo";',
      },
      { private: true, workspaces: ["packages/*"] },
    );

    const libraryDirectory = path.join(monorepoDirectory, "packages/library");
    const result = await analyzeProject({
      rootDirectory: libraryDirectory,
      entryPatterns: ["src/index.ts"],
    });

    expect(relativeUnusedPaths(libraryDirectory, result.unusedFiles)).toEqual(["src/foo.ts"]);
  });

  it("maps workspace Stylelint plugin paths from sibling configs", async () => {
    const monorepoDirectory = createProject(
      {
        "packages/library/package.json": JSON.stringify({
          name: "@example/library",
          exports: {
            "./stylelint/custom-rule.mjs": "./src/stylelint/custom-rule.mjs",
          },
        }),
        "packages/library/src/stylelint/custom-rule.mjs": "export default {};",
        "packages/library/src/orphan.mjs": "export default {};",
        "packages/app/package.json": JSON.stringify({ name: "@example/app" }),
        "packages/app/.stylelintrc.mjs": `export default {
          description: "@example/library/orphan.mjs",
          plugins: ["@example/library/stylelint/custom-rule.mjs"],
        };`,
        "packages/app/src/unrelated.ts": `export const label = "@example/library/orphan.mjs";`,
      },
      { private: true, workspaces: ["packages/*"] },
    );

    const libraryDirectory = path.join(monorepoDirectory, "packages/library");
    const result = await analyzeProject({
      rootDirectory: libraryDirectory,
      entryPatterns: ["src/stylelint/custom-rule.mjs"],
    });

    expect(relativeUnusedPaths(libraryDirectory, result.unusedFiles)).toEqual(["src/orphan.mjs"]);
  });

  it("expands static globby calls in framework entries with their exact cwd and exclusions", async () => {
    const rootDirectory = createProject(
      {
        "src/app/experiments/[...slug]/page.tsx": `
          import { dirname, resolve } from "node:path";
          import { fileURLToPath } from "node:url";
          import { globby } from "globby";
          const currentDirectory = dirname(fileURLToPath(import.meta.url));
          const experimentsRootDirectory = resolve(currentDirectory, "..");
          export const generateStaticParams = async () => globby(
            ["**/*.tsx", "!infra/**/*", "!**/page.tsx"],
            { cwd: experimentsRootDirectory },
          );
          export default () => null;
        `,
        "src/app/experiments/menu/basic.tsx": "export default null;",
        "src/app/experiments/infra/private.tsx": "export default null;",
        "src/app/experiments/unused/page.tsx": "export default null;",
        "src/orphan.ts": "export const orphan = true;",
      },
      { dependencies: { next: "1.0.0", globby: "1.0.0" } },
    );

    const result = await analyzeProject({ rootDirectory });

    expect(relativeUnusedPaths(rootDirectory, result.unusedFiles)).toEqual([
      "src/app/experiments/infra/private.tsx",
      "src/orphan.ts",
    ]);
  });

  it("does not activate globby calls from unreachable modules or unrelated functions", async () => {
    const rootDirectory = createProject(
      {
        "src/index.ts": "console.log('entry');",
        "src/dormant-registry.ts": `
          import { globby } from "globby";
          export const modules = globby("./modules/*.ts");
        `,
        "src/unrelated.ts": `
          const globby = (pattern: string) => pattern;
          globby("./modules/*.ts");
        `,
        "src/modules/hidden.ts": "export const hidden = true;",
      },
      { dependencies: { globby: "1.0.0" } },
    );

    const result = await analyzeProject({ rootDirectory, entryPatterns: ["src/index.ts"] });

    expect(relativeUnusedPaths(rootDirectory, result.unusedFiles)).toEqual([
      "src/dormant-registry.ts",
      "src/modules/hidden.ts",
      "src/unrelated.ts",
    ]);
  });

  it("discovers default and configured Netlify function directories only with netlify.toml", async () => {
    const defaultRoot = createProject({
      "src/index.ts": "console.log('entry');",
      "netlify.toml": "[build]\ncommand = 'build'",
      "netlify/functions/notify.ts": "export default () => new Response();",
      "functions/dormant.ts": "export default () => new Response();",
    });
    const configuredRoot = createProject({
      "src/index.ts": "console.log('entry');",
      "netlify.toml": "[functions]\ndirectory = 'server/functions'",
      "netlify/functions/dormant.ts": "export default () => new Response();",
      "server/functions/notify.ts": "export default () => new Response();",
    });
    const unrelatedRoot = createProject({
      "src/index.ts": "console.log('entry');",
      "netlify/functions/dormant.ts": "export default () => new Response();",
    });

    const [defaultResult, configuredResult, unrelatedResult] = await Promise.all([
      analyzeProject({ rootDirectory: defaultRoot, entryPatterns: ["src/index.ts"] }),
      analyzeProject({ rootDirectory: configuredRoot, entryPatterns: ["src/index.ts"] }),
      analyzeProject({ rootDirectory: unrelatedRoot, entryPatterns: ["src/index.ts"] }),
    ]);

    expect(relativeUnusedPaths(defaultRoot, defaultResult.unusedFiles)).toEqual([
      "functions/dormant.ts",
    ]);
    expect(relativeUnusedPaths(configuredRoot, configuredResult.unusedFiles)).toEqual([
      "netlify/functions/dormant.ts",
    ]);
    expect(relativeUnusedPaths(unrelatedRoot, unrelatedResult.unusedFiles)).toEqual([
      "netlify/functions/dormant.ts",
    ]);
  });
});

describe("tool-consumed source conventions", () => {
  it("keeps MUI docs metadata files only when the docs infrastructure is installed", async () => {
    const enabledRoot = createProject(
      {
        "src/index.ts": "console.log('entry');",
        "src/button/ButtonDataAttributes.ts":
          "export enum ButtonDataAttributes { pressed = 'data-pressed' }",
        "src/button/ButtonCssVars.ts": "export enum ButtonCssVars { width = '--button-width' }",
        "src/button/ButtonDormant.ts": "export const dormant = true;",
      },
      { devDependencies: { "@mui/internal-docs-infra": "1.0.0" } },
    );
    const disabledRoot = createProject({
      "src/index.ts": "console.log('entry');",
      "src/button/ButtonDataAttributes.ts":
        "export enum ButtonDataAttributes { pressed = 'data-pressed' }",
    });

    const [enabledResult, disabledResult] = await Promise.all([
      analyzeProject({ rootDirectory: enabledRoot, entryPatterns: ["src/index.ts"] }),
      analyzeProject({ rootDirectory: disabledRoot, entryPatterns: ["src/index.ts"] }),
    ]);

    expect(relativeUnusedPaths(enabledRoot, enabledResult.unusedFiles)).toEqual([
      "src/button/ButtonDormant.ts",
    ]);
    expect(relativeUnusedPaths(disabledRoot, disabledResult.unusedFiles)).toEqual([
      "src/button/ButtonDataAttributes.ts",
    ]);
  });

  it("keeps the internal bundle-size checker default config only with its package", async () => {
    const enabledRoot = createProject(
      {
        "src/index.ts": "console.log('entry');",
        "bundle-size-checker.config.mjs": "export default {};",
        "unrelated.config.mjs": "export default {};",
      },
      { devDependencies: { "@mui/internal-bundle-size-checker": "1.0.0" } },
    );
    const disabledRoot = createProject({
      "src/index.ts": "console.log('entry');",
      "bundle-size-checker.config.mjs": "export default {};",
    });

    const [enabledResult, disabledResult] = await Promise.all([
      analyzeProject({ rootDirectory: enabledRoot, entryPatterns: ["src/index.ts"] }),
      analyzeProject({ rootDirectory: disabledRoot, entryPatterns: ["src/index.ts"] }),
    ]);

    expect(relativeUnusedPaths(enabledRoot, enabledResult.unusedFiles)).toEqual([
      "unrelated.config.mjs",
    ]);
    expect(relativeUnusedPaths(disabledRoot, disabledResult.unusedFiles)).toEqual([
      "bundle-size-checker.config.mjs",
    ]);
  });

  it("keeps compiler-only public type fixture inputs without widening ordinary packages", async () => {
    const rootDirectory = createProject({
      "src/index.ts": "console.log('entry');",
      "public-types/package.json": JSON.stringify({
        private: true,
        scripts: { test: "tsc --noEmit" },
      }),
      "public-types/tsconfig.json": JSON.stringify({
        compilerOptions: { noEmit: true },
        include: ["**/*.ts", "**/*.tsx"],
        exclude: ["excluded/**"],
      }),
      "public-types/use-render.tsx": "export const fixture = <div />;",
      "public-types/excluded/dormant.ts": "export const dormant = true;",
      "ordinary/package.json": JSON.stringify({ private: true, scripts: { test: "tsc --noEmit" } }),
      "ordinary/tsconfig.json": JSON.stringify({
        compilerOptions: { noEmit: true },
        include: ["**/*.ts"],
      }),
      "ordinary/dormant.ts": "export const dormant = true;",
    });

    const result = await analyzeProject({ rootDirectory, entryPatterns: ["src/index.ts"] });

    expect(relativeUnusedPaths(rootDirectory, result.unusedFiles)).toEqual([
      "ordinary/dormant.ts",
      "public-types/excluded/dormant.ts",
    ]);
  });
});
