/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Run the React Compiler lint validations over `source` and return the
 * diagnostics. `filename` drives source-type inference only.
 */
export declare function lint(source: string, filename: string): Array<LintEvent>

/** One `kind: 'error'` detail (location + code-frame message) of a [`LintEvent`]. */
export interface LintDetail {
  loc?: LintLocation
  message?: string
}

/**
 * One lint diagnostic. `category` is the stable `ErrorCategory` tag (e.g.
 * `"RenderSetState"`) the JS plugin filters on; `ruleName` is the rule the
 * diagnostic surfaces under (e.g. `"set-state-in-render"`); `severity` is the
 * ESLint string level (`"error"` / `"warn"` / `"off"`).
 */
export interface LintEvent {
  category: string
  ruleName: string
  severity: string
  reason: string
  description?: string
  details: Array<LintDetail>
}

/** A babel-style `[start, end)` source range. */
export interface LintLocation {
  start: LintPosition
  end: LintPosition
}

/** A babel-style source position (1-based line, 0-based UTF-16 column). */
export interface LintPosition {
  line: number
  column: number
}

/** The crate version, for cache-keying / diagnostics. */
export declare function version(): string
