import * as fs from "node:fs";
import os from "node:os";
import * as path from "node:path";
import { afterAll, describe, expect, it } from "vite-plus/test";
import { runOxlint } from "@react-doctor/core";
import { buildTestProject, setupReactProject } from "../regressions/_helpers.js";

const temporaryRoot = fs.mkdtempSync(path.join(os.tmpdir(), "rd-auto-import-e2e-"));

afterAll(() => {
  fs.rmSync(temporaryRoot, { recursive: true, force: true });
});

describe("runOxlint unplugin-auto-import globals", () => {
  it("does not report JSX identifiers listed in current generated ESLint globals", async () => {
    const projectDirectory = setupReactProject(temporaryRoot, "generated-globals", {
      packageJsonExtras: {
        devDependencies: { "unplugin-auto-import": "^20.0.0" },
      },
      files: {
        "vite.config.ts": `
          import { defineConfig } from "vite";
          import AutoImport from "unplugin-auto-import/vite";
          export default defineConfig({
            plugins: [
              AutoImport({
                imports: ["react-router-dom"],
                dts: "./src/auto-imports.d.ts",
                eslintrc: {
                  enabled: true,
                  filepath: "./src/auto-imports.json",
                },
              }),
            ],
          });
        `,
        "src/auto-imports.d.ts": `
          // Generated by unplugin-auto-import
          export {}
          declare global {
            const Route: typeof import('react-router-dom').Route
            const Routes: typeof import('react-router-dom').Routes
          }
        `,
        "src/auto-imports.json": JSON.stringify({
          globals: { Route: "readonly", Routes: "readonly" },
        }),
        "src/routes/index.tsx": `
          export const AppRoutes = () => (
            <Routes>
              <Route path="/" element={<Missing />} />
            </Routes>
          );
        `,
      },
    });

    const diagnostics = await runOxlint({
      rootDirectory: projectDirectory,
      project: buildTestProject({
        rootDirectory: projectDirectory,
        framework: "vite",
      }),
    });
    const undefinedComponents = diagnostics.filter(
      (diagnostic) => diagnostic.rule === "jsx-no-undef",
    );

    expect(undefinedComponents.map((diagnostic) => diagnostic.message)).toEqual([
      "`Missing` crashes at runtime because it isn't defined here.",
    ]);
  });

  it("reports stale declarations when no active auto-import config exists", async () => {
    const projectDirectory = setupReactProject(temporaryRoot, "stale-generated-globals", {
      files: {
        "src/auto-imports.d.ts": `
          // Generated by unplugin-auto-import
          export {}
          declare global {
            const Route: typeof import('react-router-dom').Route
          }
        `,
        "src/routes/index.tsx": `export const AppRoutes = () => <Route />;`,
      },
    });

    const diagnostics = await runOxlint({
      rootDirectory: projectDirectory,
      project: buildTestProject({
        rootDirectory: projectDirectory,
        framework: "vite",
      }),
    });

    expect(
      diagnostics
        .filter((diagnostic) => diagnostic.rule === "jsx-no-undef")
        .map((diagnostic) => diagnostic.message),
    ).toEqual(["`Route` crashes at runtime because it isn't defined here."]);
  });
});
