import {
  buildRuleDocsUrl,
  CANONICAL_DISCORD_URL,
  CANONICAL_GITHUB_URL,
  CI_URL,
  CONFIG_SCHEMA_URL,
  DOCS_URL,
  ENTERPRISE_CONTACT_URL,
  GITHUB_ACTIONS_SETUP_URL,
  SHARE_BASE_URL,
  SKILL_NAME,
} from "@react-doctor/core";

export {
  buildRuleDocsUrl,
  CANONICAL_DISCORD_URL,
  CANONICAL_GITHUB_URL,
  CI_URL,
  CONFIG_SCHEMA_URL,
  DOCS_URL,
  ENTERPRISE_CONTACT_URL,
  GITHUB_ACTIONS_SETUP_URL,
  SHARE_BASE_URL,
  SKILL_NAME,
};
