// GENERATED FROM OXC — do not edit by hand. Run `pnpm gen:fixtures` to regenerate.
// Source: oxc-project/oxc `crates/oxc_linter/src/rules/jsx_a11y/aria_proptypes.rs`
// Each entry is a verbatim port of an OXC `pass`/`fail` vec entry.
// `oxcOptions` (optional) is OXC's first config arg (`Some(json!([…]))`),
// preserved as JS for tests that want to translate it. `oxcSettings`
// (optional) mirrors the third tuple slot used for plugin settings.

export interface OxcFixture {
  code: string;
  oxcOptions?: unknown;
  oxcSettings?: unknown;
  oxcFilename?: string;
}

export const passCases: ReadonlyArray<OxcFixture> = [
  { code: `<div aria-foo="true" />` },
  { code: `<div abcaria-foo="true" />` },
  { code: `<div aria-hidden={true} />` },
  { code: `<div aria-hidden="true" />` },
  { code: `<div aria-hidden={"false"} />` },
  { code: `<div aria-hidden={!false} />` },
  { code: `<div aria-hidden />` },
  { code: `<div aria-hidden={false} />` },
  { code: `<div aria-hidden={!!foo} />` },
  { code: `<div aria-hidden={!true} />` },
  { code: `<div aria-hidden={!"yes"} />` },
  { code: `<div aria-hidden={foo} />` },
  { code: `<div aria-hidden={foo.bar} />` },
  { code: `<div aria-hidden={null} />` },
  { code: `<div aria-hidden={undefined} />` },
  { code: `<div aria-hidden={<div />} />` },
  { code: `<div aria-label="Close" />` },
  { code: `<div aria-label="" />` },
  { code: `<div aria-label />` },
  { code: `<div aria-label={\`Close\`} />` },
  { code: `<div aria-label={\`Hello \${foo}\`} />` },
  { code: `<div aria-label={\`foo-\${id}\`} />` },
  { code: `<div aria-label={\`foo-\${id} bar\`} />` },
  { code: `<div aria-label={foo} />` },
  { code: `<div aria-label={foo.bar} />` },
  { code: `<div aria-label={null} />` },
  { code: `<div aria-label={undefined} />` },
  { code: `<input aria-invalid={error ? "true" : "false"} />` },
  { code: `<input aria-invalid={undefined ? "true" : "false"} />` },
  { code: `<div aria-checked={true} />` },
  { code: `<div aria-checked={!!foo} />` },
  { code: `<div aria-checked="true" />` },
  { code: `<div aria-checked={"false"} />` },
  { code: `<div aria-checked={!false} />` },
  { code: `<div aria-checked />` },
  { code: `<div aria-checked={false} />` },
  { code: `<div aria-checked={!true} />` },
  { code: `<div aria-checked={!"yes"} />` },
  { code: `<div aria-checked={foo} />` },
  { code: `<div aria-checked={foo.bar} />` },
  { code: `<div aria-checked="mixed" />` },
  { code: `<div aria-checked={\`mixed\`} />` },
  { code: `<div aria-checked={null} />` },
  { code: `<div aria-checked={undefined} />` },
  { code: `<div aria-level={123} />` },
  { code: `<div aria-level={-123} />` },
  { code: `<div aria-level={+123} />` },
  { code: `<div aria-level={~123} />` },
  { code: `<div aria-level={"123"} />` },
  { code: `<div aria-level={\`123\`} />` },
  { code: `<div aria-level="123" />` },
  { code: `<div aria-level={foo} />` },
  { code: `<div aria-level={foo.bar} />` },
  { code: `<div aria-level={null} />` },
  { code: `<div aria-level={undefined} />` },
  { code: `<div aria-valuemax={123} />` },
  { code: `<div aria-valuemax={-123} />` },
  { code: `<div aria-valuemax={+123} />` },
  { code: `<div aria-valuemax={~123} />` },
  { code: `<div aria-valuemax={"123"} />` },
  { code: `<div aria-valuemax={\`123\`} />` },
  { code: `<div aria-valuemax="123" />` },
  { code: `<div aria-valuemax={foo} />` },
  { code: `<div aria-valuemax={foo.bar} />` },
  { code: `<div aria-valuemax={null} />` },
  { code: `<div aria-valuemax={undefined} />` },
  { code: `<div aria-sort="ascending" />` },
  { code: `<div aria-sort="ASCENDING" />` },
  { code: `<div aria-sort={"ascending"} />` },
  { code: `<div aria-sort={\`ascending\`} />` },
  { code: `<div aria-sort="descending" />` },
  { code: `<div aria-sort={"descending"} />` },
  { code: `<div aria-sort={\`descending\`} />` },
  { code: `<div aria-sort="none" />` },
  { code: `<div aria-sort={"none"} />` },
  { code: `<div aria-sort={\`none\`} />` },
  { code: `<div aria-sort="other" />` },
  { code: `<div aria-sort={"other"} />` },
  { code: `<div aria-sort={\`other\`} />` },
  { code: `<div aria-sort={foo} />` },
  { code: `<div aria-sort={foo.bar} />` },
  { code: `<div aria-invalid={true} />` },
  { code: `<div aria-invalid="true" />` },
  { code: `<div aria-invalid={false} />` },
  { code: `<div aria-invalid="false" />` },
  { code: `<div aria-invalid="grammar" />` },
  { code: `<div aria-invalid="spelling" />` },
  { code: `<div aria-invalid={null} />` },
  { code: `<div aria-invalid={undefined} />` },
  { code: `<div aria-relevant="additions" />` },
  { code: `<div aria-relevant={"additions"} />` },
  { code: `<div aria-relevant={\`additions\`} />` },
  { code: `<div aria-relevant="additions removals" />` },
  { code: `<div aria-relevant="additions additions" />` },
  { code: `<div aria-relevant={"additions removals"} />` },
  { code: `<div aria-relevant={\`additions removals\`} />` },
  { code: `<div aria-relevant="additions removals text" />` },
  { code: `<div aria-relevant={"additions removals text"} />` },
  { code: `<div aria-relevant={\`additions removals text\`} />` },
  { code: `<div aria-relevant="additions removals text all" />` },
  { code: `<div aria-relevant={"additions removals text all"} />` },
  { code: `<div aria-relevant={\`removals additions text all\`} />` },
  { code: `<div aria-relevant={foo} />` },
  { code: `<div aria-relevant={foo.bar} />` },
  { code: `<div aria-relevant={null} />` },
  { code: `<div aria-relevant={undefined} />` },
  { code: `<div aria-activedescendant="ascending" />` },
  { code: `<div aria-activedescendant="ASCENDING" />` },
  { code: `<div aria-activedescendant={"ascending"} />` },
  { code: `<div aria-activedescendant={\`ascending\`} />` },
  { code: `<div aria-activedescendant="descending" />` },
  { code: `<div aria-activedescendant={"descending"} />` },
  { code: `<div aria-activedescendant={\`descending\`} />` },
  { code: `<div aria-activedescendant="none" />` },
  { code: `<div aria-activedescendant={"none"} />` },
  { code: `<div aria-activedescendant={\`none\`} />` },
  { code: `<div aria-activedescendant="other" />` },
  { code: `<div aria-activedescendant={"other"} />` },
  { code: `<div aria-activedescendant={\`other\`} />` },
  { code: `<div aria-activedescendant={foo} />` },
  { code: `<div aria-activedescendant={foo.bar} />` },
  { code: `<div aria-activedescendant={null} />` },
  { code: `<div aria-activedescendant={undefined} />` },
  { code: `<div aria-labelledby="additions" />` },
  { code: `<div aria-labelledby={"additions"} />` },
  { code: `<div aria-labelledby={\`additions\`} />` },
  { code: `<div aria-labelledby="additions removals" />` },
  { code: `<div aria-labelledby="additions additions" />` },
  { code: `<div aria-labelledby={"additions removals"} />` },
  { code: `<div aria-labelledby={\`additions removals\`} />` },
  { code: `<div aria-labelledby="additions removals text" />` },
  { code: `<div aria-labelledby={"additions removals text"} />` },
  { code: `<div aria-labelledby={\`additions removals text\`} />` },
  { code: `<div aria-labelledby="additions removals text all" />` },
  { code: `<div aria-labelledby={"additions removals text all"} />` },
  { code: `<div aria-labelledby={\`removals additions text all\`} />` },
  { code: `<div aria-labelledby={foo} />` },
  { code: `<div aria-labelledby={foo.bar} />` },
  { code: `<div aria-labelledby={null} />` },
  { code: `<div aria-labelledby={undefined} />` },
  { code: `<div aria-labelledby={\`\${id}\`} />` },
  { code: `<div aria-labelledby={\`\${id}-label \${id}-help-text\`} />` },
  { code: `<div aria-describedby={\`\${id}-label\`} />` },
  { code: `<div aria-describedby={\`\${id}\`} />` },
  { code: `<div aria-describedby={\`\${foo.bar}\`} />` },
  { code: `<div aria-describedby={\`\${id}-label \${id}-help-text\`} />` },
  { code: `<div aria-describedby={\`\${foo.bar}-label \${foo.bar}-help-text\`} />` },
];

export const failCases: ReadonlyArray<OxcFixture> = [
  { code: `<div aria-hidden="yes" />` },
  { code: `<div aria-hidden="no" />` },
  { code: `<div aria-hidden={1234} />` },
  { code: `<div aria-hidden={\`\${abc}\`} />` },
  { code: `<div aria-label={true} />` },
  { code: `<div aria-label={false} />` },
  { code: `<div aria-label={1234} />` },
  { code: `<div aria-label={!true} />` },
  { code: `<div aria-checked="yes" />` },
  { code: `<div aria-checked="no" />` },
  { code: `<div aria-checked={1234} />` },
  { code: `<div aria-checked={\`\${abc}\`} />` },
  { code: `<div aria-level="yes" />` },
  { code: `<div aria-level="no" />` },
  { code: `<div aria-level={\`abc\`} />` },
  { code: `<div aria-level={true} />` },
  { code: `<div aria-level />` },
  { code: `<div aria-level={"false"} />` },
  { code: `<div aria-level={!"false"} />` },
  { code: `<div aria-valuemax="yes" />` },
  { code: `<div aria-valuemax="no" />` },
  { code: `<div aria-valuemax={\`abc\`} />` },
  { code: `<div aria-valuemax={true} />` },
  { code: `<div aria-valuemax />` },
  { code: `<div aria-valuemax={"false"} />` },
  { code: `<div aria-valuemax={!"false"} />` },
  { code: `<div aria-sort="" />` },
  { code: `<div aria-sort="descnding" />` },
  { code: `<div aria-sort />` },
  { code: `<div aria-sort={true} />` },
  { code: `<div aria-sort={"false"} />` },
  { code: `<div aria-sort="ascending descending" />` },
  { code: `<div aria-relevant="" />` },
  { code: `<div aria-relevant="foobar" />` },
  { code: `<div aria-relevant />` },
  { code: `<div aria-relevant={true} />` },
  { code: `<div aria-relevant={"false"} />` },
  { code: `<div aria-relevant="additions removalss" />` },
  { code: `<div aria-relevant="additions removalss " />` },
  { code: `<div aria-labelledby={false} />` },
  { code: `<div aria-labelledby={123} />` },
];
