// GENERATED FROM OXC — do not edit by hand. Run `pnpm gen:fixtures` to regenerate.
// Source: oxc-project/oxc `crates/oxc_linter/src/rules/jsx_a11y/aria_unsupported_elements.rs`
// Each entry is a verbatim port of an OXC `pass`/`fail` vec entry.
// `oxcOptions` (optional) is OXC's first config arg (`Some(json!([…]))`),
// preserved as JS for tests that want to translate it. `oxcSettings`
// (optional) mirrors the third tuple slot used for plugin settings.

export interface OxcFixture {
  code: string;
  oxcOptions?: unknown;
  oxcSettings?: unknown;
  oxcFilename?: string;
}

export const passCases: ReadonlyArray<OxcFixture> = [
  { code: `<a role />` },
  { code: `<abbr role />` },
  { code: `<acronym role />` },
  { code: `<address role />` },
  { code: `<applet role />` },
  { code: `<area role />` },
  { code: `<article role />` },
  { code: `<aside role />` },
  { code: `<audio role />` },
  { code: `<b role />` },
  { code: `<base  />` },
  { code: `<bdi role />` },
  { code: `<bdo role />` },
  { code: `<big role />` },
  { code: `<blink role />` },
  { code: `<blockquote role />` },
  { code: `<body role />` },
  { code: `<br role />` },
  { code: `<button role />` },
  { code: `<canvas role />` },
  { code: `<caption role />` },
  { code: `<center role />` },
  { code: `<cite role />` },
  { code: `<code role />` },
  { code: `<col  />` },
  { code: `<colgroup  />` },
  { code: `<content role />` },
  { code: `<data role />` },
  { code: `<datalist role />` },
  { code: `<dd role />` },
  { code: `<del role />` },
  { code: `<details role />` },
  { code: `<dfn role />` },
  { code: `<dialog role />` },
  { code: `<dir role />` },
  { code: `<div role />` },
  { code: `<dl role />` },
  { code: `<dt role />` },
  { code: `<em role />` },
  { code: `<embed role />` },
  { code: `<fieldset role />` },
  { code: `<figcaption role />` },
  { code: `<figure role />` },
  { code: `<font role />` },
  { code: `<footer role />` },
  { code: `<form role />` },
  { code: `<frame role />` },
  { code: `<frameset role />` },
  { code: `<h1 role />` },
  { code: `<h2 role />` },
  { code: `<h3 role />` },
  { code: `<h4 role />` },
  { code: `<h5 role />` },
  { code: `<h6 role />` },
  { code: `<head  />` },
  { code: `<header role />` },
  { code: `<hgroup role />` },
  { code: `<hr role />` },
  { code: `<html  />` },
  { code: `<i role />` },
  { code: `<iframe role />` },
  { code: `<img role />` },
  { code: `<input role />` },
  { code: `<ins role />` },
  { code: `<kbd role />` },
  { code: `<keygen role />` },
  { code: `<label role />` },
  { code: `<legend role />` },
  { code: `<li role />` },
  { code: `<link  />` },
  { code: `<main role />` },
  { code: `<map role />` },
  { code: `<mark role />` },
  { code: `<marquee role />` },
  { code: `<menu role />` },
  { code: `<menuitem role />` },
  { code: `<meta  />` },
  { code: `<meter role />` },
  { code: `<nav role />` },
  { code: `<noembed  />` },
  { code: `<noscript  />` },
  { code: `<object role />` },
  { code: `<ol role />` },
  { code: `<optgroup role />` },
  { code: `<option role />` },
  { code: `<output role />` },
  { code: `<p role />` },
  { code: `<param  />` },
  { code: `<picture  />` },
  { code: `<pre role />` },
  { code: `<progress role />` },
  { code: `<q role />` },
  { code: `<rp role />` },
  { code: `<rt role />` },
  { code: `<rtc role />` },
  { code: `<ruby role />` },
  { code: `<s role />` },
  { code: `<samp role />` },
  { code: `<script  />` },
  { code: `<section role />` },
  { code: `<select role />` },
  { code: `<small role />` },
  { code: `<source  />` },
  { code: `<spacer role />` },
  { code: `<span role />` },
  { code: `<strike role />` },
  { code: `<strong role />` },
  { code: `<style  />` },
  { code: `<sub role />` },
  { code: `<summary role />` },
  { code: `<sup role />` },
  { code: `<table role />` },
  { code: `<tbody role />` },
  { code: `<td role />` },
  { code: `<textarea role />` },
  { code: `<tfoot role />` },
  { code: `<th role />` },
  { code: `<thead role />` },
  { code: `<time role />` },
  { code: `<title  />` },
  { code: `<tr role />` },
  { code: `<track  />` },
  { code: `<tt role />` },
  { code: `<u role />` },
  { code: `<ul role />` },
  { code: `<var role />` },
  { code: `<video role />` },
  { code: `<wbr role />` },
  { code: `<xmp role />` },
  { code: `<a aria-hidden />` },
  { code: `<abbr aria-hidden />` },
  { code: `<acronym aria-hidden />` },
  { code: `<address aria-hidden />` },
  { code: `<applet aria-hidden />` },
  { code: `<area aria-hidden />` },
  { code: `<article aria-hidden />` },
  { code: `<aside aria-hidden />` },
  { code: `<audio aria-hidden />` },
  { code: `<b aria-hidden />` },
  { code: `<base  />` },
  { code: `<bdi aria-hidden />` },
  { code: `<bdo aria-hidden />` },
  { code: `<big aria-hidden />` },
  { code: `<blink aria-hidden />` },
  { code: `<blockquote aria-hidden />` },
  { code: `<body aria-hidden />` },
  { code: `<br aria-hidden />` },
  { code: `<button aria-hidden />` },
  { code: `<canvas aria-hidden />` },
  { code: `<caption aria-hidden />` },
  { code: `<center aria-hidden />` },
  { code: `<cite aria-hidden />` },
  { code: `<code aria-hidden />` },
  { code: `<col  />` },
  { code: `<colgroup  />` },
  { code: `<content aria-hidden />` },
  { code: `<data aria-hidden />` },
  { code: `<datalist aria-hidden />` },
  { code: `<dd aria-hidden />` },
  { code: `<del aria-hidden />` },
  { code: `<details aria-hidden />` },
  { code: `<dfn aria-hidden />` },
  { code: `<dialog aria-hidden />` },
  { code: `<dir aria-hidden />` },
  { code: `<div aria-hidden />` },
  { code: `<dl aria-hidden />` },
  { code: `<dt aria-hidden />` },
  { code: `<em aria-hidden />` },
  { code: `<embed aria-hidden />` },
  { code: `<fieldset aria-hidden />` },
  { code: `<figcaption aria-hidden />` },
  { code: `<figure aria-hidden />` },
  { code: `<font aria-hidden />` },
  { code: `<footer aria-hidden />` },
  { code: `<form aria-hidden />` },
  { code: `<frame aria-hidden />` },
  { code: `<frameset aria-hidden />` },
  { code: `<h1 aria-hidden />` },
  { code: `<h2 aria-hidden />` },
  { code: `<h3 aria-hidden />` },
  { code: `<h4 aria-hidden />` },
  { code: `<h5 aria-hidden />` },
  { code: `<h6 aria-hidden />` },
  { code: `<head  />` },
  { code: `<header aria-hidden />` },
  { code: `<hgroup aria-hidden />` },
  { code: `<hr aria-hidden />` },
  { code: `<html  />` },
  { code: `<i aria-hidden />` },
  { code: `<iframe aria-hidden />` },
  { code: `<img aria-hidden />` },
  { code: `<input aria-hidden />` },
  { code: `<ins aria-hidden />` },
  { code: `<kbd aria-hidden />` },
  { code: `<keygen aria-hidden />` },
  { code: `<label aria-hidden />` },
  { code: `<legend aria-hidden />` },
  { code: `<li aria-hidden />` },
  { code: `<link  />` },
  { code: `<main aria-hidden />` },
  { code: `<map aria-hidden />` },
  { code: `<mark aria-hidden />` },
  { code: `<marquee aria-hidden />` },
  { code: `<menu aria-hidden />` },
  { code: `<menuitem aria-hidden />` },
  { code: `<meta  />` },
  { code: `<meter aria-hidden />` },
  { code: `<nav aria-hidden />` },
  { code: `<noembed  />` },
  { code: `<noscript  />` },
  { code: `<object aria-hidden />` },
  { code: `<ol aria-hidden />` },
  { code: `<optgroup aria-hidden />` },
  { code: `<option aria-hidden />` },
  { code: `<output aria-hidden />` },
  { code: `<p aria-hidden />` },
  { code: `<param  />` },
  { code: `<picture  />` },
  { code: `<pre aria-hidden />` },
  { code: `<progress aria-hidden />` },
  { code: `<q aria-hidden />` },
  { code: `<rp aria-hidden />` },
  { code: `<rt aria-hidden />` },
  { code: `<rtc aria-hidden />` },
  { code: `<ruby aria-hidden />` },
  { code: `<s aria-hidden />` },
  { code: `<samp aria-hidden />` },
  { code: `<script  />` },
  { code: `<section aria-hidden />` },
  { code: `<select aria-hidden />` },
  { code: `<small aria-hidden />` },
  { code: `<source  />` },
  { code: `<spacer aria-hidden />` },
  { code: `<span aria-hidden />` },
  { code: `<strike aria-hidden />` },
  { code: `<strong aria-hidden />` },
  { code: `<style  />` },
  { code: `<sub aria-hidden />` },
  { code: `<summary aria-hidden />` },
  { code: `<sup aria-hidden />` },
  { code: `<table aria-hidden />` },
  { code: `<tbody aria-hidden />` },
  { code: `<td aria-hidden />` },
  { code: `<textarea aria-hidden />` },
  { code: `<tfoot aria-hidden />` },
  { code: `<th aria-hidden />` },
  { code: `<thead aria-hidden />` },
  { code: `<time aria-hidden />` },
  { code: `<title  />` },
  { code: `<tr aria-hidden />` },
  { code: `<track  />` },
  { code: `<tt aria-hidden />` },
  { code: `<u aria-hidden />` },
  { code: `<ul aria-hidden />` },
  { code: `<var aria-hidden />` },
  { code: `<video aria-hidden />` },
  { code: `<wbr aria-hidden />` },
  { code: `<xmp aria-hidden />` },
];

export const failCases: ReadonlyArray<OxcFixture> = [
  { code: `<base role {...props} />` },
  { code: `<col role {...props} />` },
  { code: `<colgroup role {...props} />` },
  { code: `<head role {...props} />` },
  { code: `<html role {...props} />` },
  { code: `<link role {...props} />` },
  { code: `<meta role {...props} />` },
  { code: `<noembed role {...props} />` },
  { code: `<noscript role {...props} />` },
  { code: `<param role {...props} />` },
  { code: `<picture role {...props} />` },
  { code: `<script role {...props} />` },
  { code: `<source role {...props} />` },
  { code: `<style role {...props} />` },
  { code: `<title role {...props} />` },
  { code: `<track role {...props} />` },
  { code: `<base aria-hidden aria-role="none" {...props} />` },
  { code: `<col aria-hidden aria-role="none" {...props} />` },
  { code: `<colgroup aria-hidden aria-role="none" {...props} />` },
  { code: `<head aria-hidden aria-role="none" {...props} />` },
  { code: `<html aria-hidden aria-role="none" {...props} />` },
  { code: `<link aria-hidden aria-role="none" {...props} />` },
  { code: `<meta aria-hidden aria-role="none" {...props} />` },
  { code: `<noembed aria-hidden aria-role="none" {...props} />` },
  { code: `<noscript aria-hidden aria-role="none" {...props} />` },
  { code: `<param aria-hidden aria-role="none" {...props} />` },
  { code: `<picture aria-hidden aria-role="none" {...props} />` },
  { code: `<script aria-hidden aria-role="none" {...props} />` },
  { code: `<source aria-hidden aria-role="none" {...props} />` },
  { code: `<style aria-hidden aria-role="none" {...props} />` },
  { code: `<title aria-hidden aria-role="none" {...props} />` },
  { code: `<track aria-hidden aria-role="none" {...props} />` },
];
