// GENERATED FROM OXC — do not edit by hand. Run `pnpm gen:fixtures` to regenerate.
// Source: oxc-project/oxc `crates/oxc_linter/src/rules/jsx_a11y/interactive_supports_focus.rs`
// Each entry is a verbatim port of an OXC `pass`/`fail` vec entry.
// `oxcOptions` (optional) is OXC's first config arg (`Some(json!([…]))`),
// preserved as JS for tests that want to translate it. `oxcSettings`
// (optional) mirrors the third tuple slot used for plugin settings.

export interface OxcFixture {
  code: string;
  oxcOptions?: unknown;
  oxcSettings?: unknown;
  oxcFilename?: string;
}

export const passCases: ReadonlyArray<OxcFixture> = [
  { code: `<div />` },
  { code: `<div aria-hidden onClick={() => void 0} />` },
  { code: `<div aria-hidden={true == true} onClick={() => void 0} />` },
  { code: `<div aria-hidden={true === true} onClick={() => void 0} />` },
  { code: `<div aria-hidden={hidden !== false} onClick={() => void 0} />` },
  { code: `<div aria-hidden={hidden != false} onClick={() => void 0} />` },
  { code: `<div aria-hidden={1 < 2} onClick={() => void 0} />` },
  { code: `<div aria-hidden={1 <= 2} onClick={() => void 0} />` },
  { code: `<div aria-hidden={2 > 1} onClick={() => void 0} />` },
  { code: `<div aria-hidden={2 >= 1} onClick={() => void 0} />` },
  { code: `<div onClick={() => void 0} />;` },
  { code: `<div onClick={() => void 0} tabIndex={undefined} />;` },
  { code: `<div onClick={() => void 0} tabIndex="bad" />;` },
  { code: `<div onClick={() => void 0} role={undefined} />;` },
  { code: `<div role="section" onClick={() => void 0} />` },
  { code: `<div onClick={() => void 0} aria-hidden={false} />;` },
  { code: `<div onClick={() => void 0} {...props} />;` },
  { code: `<input type="text" onClick={() => void 0} />` },
  { code: `<input type="hidden" onClick={() => void 0} tabIndex="-1" />` },
  { code: `<input type={\`hidden\`} onClick={() => void 0} tabIndex={-1} />` },
  { code: `<input onClick={() => void 0} />` },
  { code: `<input onClick={() => void 0} role="combobox" />` },
  { code: `<button onClick={() => void 0} className="foo" />` },
  { code: `<option onClick={() => void 0} className="foo" />` },
  { code: `<select onClick={() => void 0} className="foo" />` },
  { code: `<area href='#' onClick={() => void 0} className='foo' />` },
  { code: `<area onClick={() => void 0} className="foo" />` },
  { code: `<summary onClick={() => void 0} />` },
  { code: `<textarea onClick={() => void 0} className="foo" />` },
  { code: `<a onClick="showNextPage();">Next page</a>` },
  { code: `<a onClick="showNextPage();" tabIndex={undefined}>Next page</a>` },
  { code: `<a onClick="showNextPage();" tabIndex="bad">Next page</a>` },
  { code: `<a onClick={() => void 0} />` },
  { code: `<a tabIndex="0" onClick={() => void 0} />` },
  { code: `<a tabIndex={dynamicTabIndex} onClick={() => void 0} />` },
  { code: `<a tabIndex={0} onClick={() => void 0} />` },
  { code: `<a role='button' href='#' onClick={() => void 0} />` },
  { code: `<a onClick={() => void 0} href="http://x.y.z" />` },
  { code: `<a onClick={() => void 0} href="http://x.y.z" tabIndex="0" />` },
  { code: `<a onClick={() => void 0} href="http://x.y.z" tabIndex={0} />` },
  { code: `<a onClick={() => void 0} href="http://x.y.z" role="button" />` },
  { code: `<TestComponent onClick={doFoo} />` },
  { code: `<HigherLevelComponent role="button" onClick={() => void 0} />` },
  { code: `<Foo.Bar role="button" onClick={() => void 0} />` },
  { code: `<input onClick={() => void 0} type="hidden" />;` },
  { code: `<span onClick='submitForm();'>Submit</span>` },
  { code: `<span onClick='submitForm();' tabIndex={undefined}>Submit</span>` },
  { code: `<span onClick='submitForm();' tabIndex='bad'>Submit</span>` },
  { code: `<span onClick='doSomething();' tabIndex='0'>Click me!</span>` },
  { code: `<span onClick='doSomething();' tabIndex={0}>Click me!</span>` },
  { code: `<span onClick='doSomething();' tabIndex='-1'>Click me too!</span>` },
  { code: `<a href="javascript:void(0);" onClick='doSomething();'>Click ALL the things!</a>` },
  { code: `<section onClick={() => void 0} />;` },
  { code: `<main onClick={() => void 0} />;` },
  { code: `<article onClick={() => void 0} />;` },
  { code: `<header onClick={() => void 0} />;` },
  { code: `<footer onClick={() => void 0} />;` },
  { code: `<div role="button" tabIndex="0" onClick={() => void 0} />` },
  { code: `<div role="checkbox" tabIndex="0" onClick={() => void 0} />` },
  { code: `<div role="link" tabIndex="0" onClick={() => void 0} />` },
  { code: `<div role="menuitem" tabIndex="0" onClick={() => void 0} />` },
  { code: `<div role="menuitemcheckbox" tabIndex="0" onClick={() => void 0} />` },
  { code: `<div role="menuitemradio" tabIndex="0" onClick={() => void 0} />` },
  { code: `<div role="option" tabIndex="0" onClick={() => void 0} />` },
  { code: `<div role="radio" tabIndex="0" onClick={() => void 0} />` },
  { code: `<div role="spinbutton" tabIndex="0" onClick={() => void 0} />` },
  { code: `<div role="switch" tabIndex="0" onClick={() => void 0} />` },
  { code: `<div role="tablist" tabIndex="0" onClick={() => void 0} />` },
  { code: `<div role="tab" tabIndex="0" onClick={() => void 0} />` },
  { code: `<div role="textbox" tabIndex="0" onClick={() => void 0} />` },
  { code: `<div role="textbox" aria-disabled="true" onClick={() => void 0} />` },
  { code: `<Foo.Bar onClick={() => void 0} aria-hidden={false} />;` },
  { code: `<Input onClick={() => void 0} type='hidden' />;` },
  {
    code: `<Div onClick={() => void 0} role='button' tabIndex='0' />`,
    oxcSettings: {
      settings: {
        "jsx-a11y": {
          components: {
            Div: "div",
          },
        },
      },
    },
  },
  { code: `<div role="checkbox" onFocus={() => void 0} />` },
  { code: `<div role="link" onFocus={() => void 0} />` },
  { code: `<div role="gridcell" onFocus={() => void 0} />` },
  { code: `<div role="menuitem" onFocus={() => void 0} />` },
  { code: `<div role="menuitemcheckbox" onFocus={() => void 0} />` },
  { code: `<div role="menuitemradio" onFocus={() => void 0} />` },
  { code: `<div role="option" onFocus={() => void 0} />` },
  { code: `<div role="radio" onFocus={() => void 0} />` },
  { code: `<div role="searchbox" onFocus={() => void 0} />` },
  { code: `<div role="slider" onFocus={() => void 0} />` },
  { code: `<div role="spinbutton" onFocus={() => void 0} />` },
  { code: `<div role="switch" onFocus={() => void 0} />` },
  { code: `<div role="tab" onFocus={() => void 0} />` },
  { code: `<div role="textbox" onFocus={() => void 0} />` },
  { code: `<div role="treeitem" onFocus={() => void 0} />` },
  { code: `<div role="menuitem" onClick={() => void 0} tabIndex="0" />` },
  { code: `<div role="menuitemcheckbox" onClick={() => void 0} tabIndex="0" />` },
  { code: `<div role="menuitemradio" onClick={() => void 0} tabIndex="0" />` },
  { code: `<div role="option" onClick={() => void 0} tabIndex="0" />` },
  { code: `<div role="radio" onClick={() => void 0} tabIndex="0" />` },
  { code: `<div role="slider" onClick={() => void 0} tabIndex="0" />` },
  { code: `<div role="tab" onClick={() => void 0} tabIndex="0" />` },
  { code: `<div role="treeitem" onClick={() => void 0} tabIndex="0" />` },
];

export const failCases: ReadonlyArray<OxcFixture> = [
  {
    code: `<Div onClick={() => void 0} role='button' />`,
    oxcSettings: {
      settings: {
        "jsx-a11y": {
          components: {
            Div: "div",
          },
        },
      },
    },
  },
  { code: `<div role="button" onClick={() => void 0} />` },
  { code: `<div role="checkbox" onClick={() => void 0} />` },
  { code: `<div role="link" onClick={() => void 0} />` },
  { code: `<div role="searchbox" onClick={() => void 0} />` },
  { code: `<div role="spinbutton" onClick={() => void 0} />` },
  { code: `<div role="switch" onClick={() => void 0} />` },
  { code: `<div role="textbox" onClick={() => void 0} />` },
  { code: `<div role="gridcell" onClick={() => void 0} />` },
  { code: `<div role="menuitem" onClick={() => void 0} />` },
  { code: `<div role="menuitemcheckbox" onClick={() => void 0} />` },
  { code: `<div role="menuitemradio" onClick={() => void 0} />` },
  { code: `<div role="option" onClick={() => void 0} />` },
  { code: `<div role="radio" onClick={() => void 0} />` },
  { code: `<div role="slider" onClick={() => void 0} />` },
  { code: `<div role="tab" onClick={() => void 0} />` },
  { code: `<div role="treeitem" onClick={() => void 0} />` },
];
