// GENERATED FROM OXC — do not edit by hand. Run `pnpm gen:fixtures` to regenerate.
// Source: oxc-project/oxc `crates/oxc_linter/src/rules/jsx_a11y/no_interactive_element_to_noninteractive_role.rs`
// Each entry is a verbatim port of an OXC `pass`/`fail` vec entry.
// `oxcOptions` (optional) is OXC's first config arg (`Some(json!([…]))`),
// preserved as JS for tests that want to translate it. `oxcSettings`
// (optional) mirrors the third tuple slot used for plugin settings.

export interface OxcFixture {
  code: string;
  oxcOptions?: unknown;
  oxcSettings?: unknown;
  oxcFilename?: string;
}

export const passCases: ReadonlyArray<OxcFixture> = [
  { code: `<TestComponent onClick={doFoo} />` },
  { code: `<Button onClick={doFoo} />` },
  { code: `<a href="http://x.y.z" role="button" />` },
  { code: `<a href="http://x.y.z" tabIndex="0" role="button" />` },
  { code: `<button className="foo" role="button" />` },
  { code: `<input role="button" />` },
  { code: `<input type="button" role="button" />` },
  { code: `<input type="checkbox" role="button" />` },
  { code: `<input type="color" role="button" />` },
  { code: `<input type="date" role="button" />` },
  { code: `<input type="datetime" role="button" />` },
  { code: `<input type="datetime-local" role="button" />` },
  { code: `<input type="email" role="button" />` },
  { code: `<input type="file" role="button" />` },
  { code: `<input type="image" role="button" />` },
  { code: `<input type="month" role="button" />` },
  { code: `<input type="number" role="button" />` },
  { code: `<input type="password" role="button" />` },
  { code: `<input type="radio" role="button" />` },
  { code: `<input type="range" role="button" />` },
  { code: `<input type="reset" role="button" />` },
  { code: `<input type="search" role="button" />` },
  { code: `<input type="submit" role="button" />` },
  { code: `<input type="tel" role="button" />` },
  { code: `<input type="text" role="button" />` },
  { code: `<input type="time" role="button" />` },
  { code: `<input type="url" role="button" />` },
  { code: `<input type="week" role="button" />` },
  { code: `<input type="hidden" role="button" />` },
  { code: `<menuitem role="button" />;` },
  { code: `<option className="foo" role="button" />` },
  { code: `<select className="foo" role="button" />` },
  { code: `<textarea className="foo" role="button" />` },
  { code: `<tr role="button" />;` },
  { code: `<a role="button" />` },
  { code: `<a role="img" />;` },
  { code: `<a tabIndex="0" role="button" />` },
  { code: `<a tabIndex="0" role="img" />` },
  { code: `<acronym role="button" />;` },
  { code: `<address role="button" />;` },
  { code: `<applet role="button" />;` },
  { code: `<aside role="button" />;` },
  { code: `<audio role="button" />;` },
  { code: `<b role="button" />;` },
  { code: `<base role="button" />;` },
  { code: `<bdi role="button" />;` },
  { code: `<bdo role="button" />;` },
  { code: `<big role="button" />;` },
  { code: `<blink role="button" />;` },
  { code: `<blockquote role="button" />;` },
  { code: `<body role="button" />;` },
  { code: `<br role="button" />;` },
  { code: `<canvas role="button" />;` },
  { code: `<caption role="button" />;` },
  { code: `<center role="button" />;` },
  { code: `<cite role="button" />;` },
  { code: `<code role="button" />;` },
  { code: `<col role="button" />;` },
  { code: `<colgroup role="button" />;` },
  { code: `<content role="button" />;` },
  { code: `<data role="button" />;` },
  { code: `<datalist role="button" />;` },
  { code: `<del role="button" />;` },
  { code: `<details role="button" />;` },
  { code: `<dir role="button" />;` },
  { code: `<div role="button" />;` },
  { code: `<div className="foo" role="button" />;` },
  { code: `<div className="foo" {...props} role="button" />;` },
  { code: `<div aria-hidden role="button" />;` },
  { code: `<div aria-hidden={true} role="button" />;` },
  { code: `<div role="button" />;` },
  { code: `<div role={undefined} role="button" />;` },
  { code: `<div {...props} role="button" />;` },
  { code: `<div onKeyUp={() => void 0} aria-hidden={false} role="button" />;` },
  { code: `<dl role="button" />;` },
  { code: `<em role="button" />;` },
  { code: `<embed role="button" />;` },
  { code: `<figcaption role="button" />;` },
  { code: `<font role="button" />;` },
  { code: `<footer role="button" />;` },
  { code: `<frameset role="button" />;` },
  { code: `<head role="button" />;` },
  { code: `<header role="button" />;` },
  { code: `<hgroup role="button" />;` },
  { code: `<html role="button" />;` },
  { code: `<i role="button" />;` },
  { code: `<iframe role="button" />;` },
  { code: `<ins role="button" />;` },
  { code: `<kbd role="button" />;` },
  { code: `<keygen role="button" />;` },
  { code: `<label role="button" />;` },
  { code: `<legend role="button" />;` },
  { code: `<link role="button" />;` },
  { code: `<map role="button" />;` },
  { code: `<mark role="button" />;` },
  { code: `<marquee role="button" />;` },
  { code: `<menu role="button" />;` },
  { code: `<meta role="button" />;` },
  { code: `<meter role="button" />;` },
  { code: `<noembed role="button" />;` },
  { code: `<noscript role="button" />;` },
  { code: `<object role="button" />;` },
  { code: `<optgroup role="button" />;` },
  { code: `<output role="button" />;` },
  { code: `<p role="button" />;` },
  { code: `<param role="button" />;` },
  { code: `<picture role="button" />;` },
  { code: `<pre role="button" />;` },
  { code: `<progress role="button" />;` },
  { code: `<q role="button" />;` },
  { code: `<rp role="button" />;` },
  { code: `<rt role="button" />;` },
  { code: `<rtc role="button" />;` },
  { code: `<ruby role="button" />;` },
  { code: `<s role="button" />;` },
  { code: `<samp role="button" />;` },
  { code: `<script role="button" />;` },
  { code: `<section role="button" />;` },
  { code: `<small role="button" />;` },
  { code: `<source role="button" />;` },
  { code: `<spacer role="button" />;` },
  { code: `<span role="button" />;` },
  { code: `<strike role="button" />;` },
  { code: `<strong role="button" />;` },
  { code: `<style role="button" />;` },
  { code: `<sub role="button" />;` },
  { code: `<summary role="button" />;` },
  { code: `<sup role="button" />;` },
  { code: `<th role="button" />;` },
  { code: `<time role="button" />;` },
  { code: `<title role="button" />;` },
  { code: `<track role="button" />;` },
  { code: `<tt role="button" />;` },
  { code: `<u role="button" />;` },
  { code: `<var role="button" />;` },
  { code: `<video role="button" />;` },
  { code: `<wbr role="button" />;` },
  { code: `<xmp role="button" />;` },
  { code: `<div role="button" />;` },
  { code: `<div role="checkbox" />;` },
  { code: `<div role="columnheader" />;` },
  { code: `<div role="combobox" />;` },
  { code: `<div role="grid" />;` },
  { code: `<div role="gridcell" />;` },
  { code: `<div role="link" />;` },
  { code: `<div role="listbox" />;` },
  { code: `<div role="menu" />;` },
  { code: `<div role="menubar" />;` },
  { code: `<div role="menuitem" />;` },
  { code: `<div role="menuitemcheckbox" />;` },
  { code: `<div role="menuitemradio" />;` },
  { code: `<div role="option" />;` },
  { code: `<div role="progressbar" />;` },
  { code: `<div role="radio" />;` },
  { code: `<div role="radiogroup" />;` },
  { code: `<div role="row" />;` },
  { code: `<div role="rowheader" />;` },
  { code: `<div role="searchbox" />;` },
  { code: `<div role="slider" />;` },
  { code: `<div role="spinbutton" />;` },
  { code: `<div role="switch" />;` },
  { code: `<div role="tab" />;` },
  { code: `<div role="textbox" />;` },
  { code: `<div role="treeitem" />;` },
  { code: `<div role="presentation" />;` },
  { code: `<div role="command" />;` },
  { code: `<div role="composite" />;` },
  { code: `<div role="input" />;` },
  { code: `<div role="landmark" />;` },
  { code: `<div role="range" />;` },
  { code: `<div role="roletype" />;` },
  { code: `<div role="section" />;` },
  { code: `<div role="sectionhead" />;` },
  { code: `<div role="select" />;` },
  { code: `<div role="structure" />;` },
  { code: `<div role="tablist" />;` },
  { code: `<div role="toolbar" />;` },
  { code: `<div role="tree" />;` },
  { code: `<div role="treegrid" />;` },
  { code: `<div role="widget" />;` },
  { code: `<div role="window" />;` },
  { code: `<main role="button" />;` },
  { code: `<area role="button" />;` },
  { code: `<article role="button" />;` },
  { code: `<article role="button" />;` },
  { code: `<dd role="button" />;` },
  { code: `<dfn role="button" />;` },
  { code: `<dt role="button" />;` },
  { code: `<fieldset role="button" />;` },
  { code: `<figure role="button" />;` },
  { code: `<form role="button" />;` },
  { code: `<frame role="button" />;` },
  { code: `<h1 role="button" />;` },
  { code: `<h2 role="button" />;` },
  { code: `<h3 role="button" />;` },
  { code: `<h4 role="button" />;` },
  { code: `<h5 role="button" />;` },
  { code: `<h6 role="button" />;` },
  { code: `<hr role="button" />;` },
  { code: `<img role="button" />;` },
  { code: `<li role="button" />;` },
  { code: `<li role="presentation" />;` },
  { code: `<nav role="button" />;` },
  { code: `<ol role="button" />;` },
  { code: `<table role="button" />;` },
  { code: `<tbody role="button" />;` },
  { code: `<td role="button" />;` },
  { code: `<tfoot role="button" />;` },
  { code: `<thead role="button" />;` },
  { code: `<ul role="button" />;` },
  { code: `<div role="alert" />;` },
  { code: `<div role="alertdialog" />;` },
  { code: `<div role="application" />;` },
  { code: `<div role="article" />;` },
  { code: `<div role="banner" />;` },
  { code: `<div role="cell" />;` },
  { code: `<div role="complementary" />;` },
  { code: `<div role="contentinfo" />;` },
  { code: `<div role="definition" />;` },
  { code: `<div role="dialog" />;` },
  { code: `<div role="directory" />;` },
  { code: `<div role="document" />;` },
  { code: `<div role="feed" />;` },
  { code: `<div role="figure" />;` },
  { code: `<div role="form" />;` },
  { code: `<div role="group" />;` },
  { code: `<div role="heading" />;` },
  { code: `<div role="img" />;` },
  { code: `<div role="list" />;` },
  { code: `<div role="listitem" />;` },
  { code: `<div role="log" />;` },
  { code: `<div role="main" />;` },
  { code: `<div role="marquee" />;` },
  { code: `<div role="math" />;` },
  { code: `<div role="navigation" />;` },
  { code: `<div role="note" />;` },
  { code: `<div role="region" />;` },
  { code: `<div role="rowgroup" />;` },
  { code: `<div role="search" />;` },
  { code: `<div role="separator" />;` },
  { code: `<div role="scrollbar" />;` },
  { code: `<div role="status" />;` },
  { code: `<div role="table" />;` },
  { code: `<div role="tabpanel" />;` },
  { code: `<div role="term" />;` },
  { code: `<div role="timer" />;` },
  { code: `<div role="tooltip" />;` },
  { code: `<div mynamespace:role="term" />` },
  { code: `<input mynamespace:role="img" />` },
  { code: `<Link href="http://x.y.z" role="img" />` },
  {
    code: `<Link href="http://x.y.z" />`,
    oxcSettings: {
      settings: {
        "jsx-a11y": {
          components: {
            Button: "button",
            Link: "a",
          },
        },
      },
    },
  },
  {
    code: `<Button onClick={doFoo} />`,
    oxcSettings: {
      settings: {
        "jsx-a11y": {
          components: {
            Button: "button",
            Link: "a",
          },
        },
      },
    },
  },
  { code: `<tr role="presentation" />;` },
  { code: `<canvas role="img" />;` },
  { code: `<input role="img" />;`, oxcOptions: [{ input: ["img"] }] },
  { code: `<Component role="presentation" />;` },
];

export const failCases: ReadonlyArray<OxcFixture> = [
  { code: `<a href="http://x.y.z" role="img" />` },
  { code: `<a href="http://x.y.z" tabIndex="0" role="img" />` },
  { code: `<input role="img" />` },
  { code: `<input type="img" role="img" />` },
  { code: `<input type="checkbox" role="img" />` },
  { code: `<input type="color" role="img" />` },
  { code: `<input type="date" role="img" />` },
  { code: `<input type="datetime" role="img" />` },
  { code: `<input type="datetime-local" role="img" />` },
  { code: `<input type="email" role="img" />` },
  { code: `<input type="file" role="img" />` },
  { code: `<input type="hidden" role="img" />` },
  { code: `<input type="image" role="img" />` },
  { code: `<input type="month" role="img" />` },
  { code: `<input type="number" role="img" />` },
  { code: `<input type="password" role="img" />` },
  { code: `<input type="radio" role="img" />` },
  { code: `<input type="range" role="img" />` },
  { code: `<input type="reset" role="img" />` },
  { code: `<input type="search" role="img" />` },
  { code: `<input type="submit" role="img" />` },
  { code: `<input type="tel" role="img" />` },
  { code: `<input type="text" role="img" />` },
  { code: `<input type="time" role="img" />` },
  { code: `<input type="url" role="img" />` },
  { code: `<input type="week" role="img" />` },
  { code: `<menuitem role="img" />;` },
  { code: `<option className="foo" role="img" />` },
  { code: `<select className="foo" role="img" />` },
  { code: `<textarea className="foo" role="img" />` },
  { code: `<tr role="img" />;` },
  { code: `<a href="http://x.y.z" role="listitem" />` },
  { code: `<a href="http://x.y.z" tabIndex="0" role="listitem" />` },
  { code: `<input role="listitem" />` },
  { code: `<input type="listitem" role="listitem" />` },
  { code: `<input type="checkbox" role="listitem" />` },
  { code: `<input type="color" role="listitem" />` },
  { code: `<input type="date" role="listitem" />` },
  { code: `<input type="datetime" role="listitem" />` },
  { code: `<input type="datetime-local" role="listitem" />` },
  { code: `<input type="email" role="listitem" />` },
  { code: `<input type="file" role="listitem" />` },
  { code: `<input type="image" role="listitem" />` },
  { code: `<input type="month" role="listitem" />` },
  { code: `<input type="number" role="listitem" />` },
  { code: `<input type="password" role="listitem" />` },
  { code: `<input type="radio" role="listitem" />` },
  { code: `<input type="range" role="listitem" />` },
  { code: `<input type="reset" role="listitem" />` },
  { code: `<input type="search" role="listitem" />` },
  { code: `<input type="submit" role="listitem" />` },
  { code: `<input type="tel" role="listitem" />` },
  { code: `<input type="text" role="listitem" />` },
  { code: `<input type="time" role="listitem" />` },
  { code: `<input type="url" role="listitem" />` },
  { code: `<input type="week" role="listitem" />` },
  { code: `<menuitem role="listitem" />;` },
  { code: `<option className="foo" role="listitem" />` },
  { code: `<select className="foo" role="listitem" />` },
  { code: `<textarea className="foo" role="listitem" />` },
  { code: `<tr role="listitem" />;` },
  {
    code: `<Link href="http://x.y.z" role="img" />`,
    oxcSettings: {
      settings: {
        "jsx-a11y": {
          components: {
            Button: "button",
            Link: "a",
          },
        },
      },
    },
  },
  { code: `<tr role="presentation" />;`, oxcOptions: [{}] },
  { code: `<canvas role="img" />;`, oxcOptions: [{}] },
];
