// GENERATED FROM OXC — do not edit by hand. Run `pnpm gen:fixtures` to regenerate.
// Source: oxc-project/oxc `crates/oxc_linter/src/rules/jsx_a11y/no_noninteractive_element_to_interactive_role.rs`
// Each entry is a verbatim port of an OXC `pass`/`fail` vec entry.
// `oxcOptions` (optional) is OXC's first config arg (`Some(json!([…]))`),
// preserved as JS for tests that want to translate it. `oxcSettings`
// (optional) mirrors the third tuple slot used for plugin settings.

export interface OxcFixture {
  code: string;
  oxcOptions?: unknown;
  oxcSettings?: unknown;
  oxcFilename?: string;
}

export const passCases: ReadonlyArray<OxcFixture> = [
  { code: `<Button onClick={doFoo} />` },
  { code: `<a href="http://x.y.z" role="button" />` },
  { code: `<a href="http://x.y.z" tabIndex="0" role="button" />` },
  { code: `<area role="button" />` },
  { code: `<area role="menuitem" />` },
  { code: `<button className="foo" role="button" />` },
  { code: `<body role="button" />` },
  { code: `<frame role="button" />` },
  { code: `<td role="button" />` },
  { code: `<frame role="menuitem" />` },
  { code: `<td role="menuitem" />` },
  { code: `<input type="button" role="button" />` },
  { code: `<input type="checkbox" role="button" />` },
  { code: `<input type="color" role="button" />` },
  { code: `<input type="date" role="button" />` },
  { code: `<input type="datetime" role="button" />` },
  { code: `<input type="datetime-local" role="button" />` },
  { code: `<input type="email" role="button" />` },
  { code: `<input type="file" role="button" />` },
  { code: `<input type="hidden" role="button" />` },
  { code: `<input type="image" role="button" />` },
  { code: `<input type="month" role="button" />` },
  { code: `<input type="number" role="button" />` },
  { code: `<input type="password" role="button" />` },
  { code: `<input type="radio" role="button" />` },
  { code: `<input type="range" role="button" />` },
  { code: `<input type="reset" role="button" />` },
  { code: `<input type="search" role="button" />` },
  { code: `<input type="submit" role="button" />` },
  { code: `<input type="tel" role="button" />` },
  { code: `<input type="text" role="button" />` },
  { code: `<input type="time" role="button" />` },
  { code: `<input type="url" role="button" />` },
  { code: `<input type="week" role="button" />` },
  { code: `<input type="hidden" role="img" />` },
  { code: `<menuitem role="button" />` },
  { code: `<option className="foo" role="button" />` },
  { code: `<select className="foo" role="button" />` },
  { code: `<textarea className="foo" role="button" />` },
  { code: `<tr role="button" />` },
  { code: `<tr role="presentation" />` },
  { code: `<a href="http://x.y.z" role="img" />` },
  { code: `<dd role="listitem" />` },
  { code: `<dfn role="listitem" />` },
  { code: `<dt role="listitem" />` },
  { code: `<fieldset role="listitem" />` },
  { code: `<figure role="listitem" />` },
  { code: `<form role="listitem" />` },
  { code: `<h1 role="listitem" />` },
  { code: `<h2 role="listitem" />` },
  { code: `<h3 role="listitem" />` },
  { code: `<h4 role="listitem" />` },
  { code: `<h5 role="listitem" />` },
  { code: `<h6 role="listitem" />` },
  { code: `<hr role="listitem" />` },
  { code: `<img role="listitem" />` },
  { code: `<li role="listitem" />` },
  { code: `<li role="presentation" />` },
  { code: `<main role="listitem" />` },
  { code: `<nav role="listitem" />` },
  { code: `<ol role="listitem" />` },
  { code: `<table role="listitem" />` },
  { code: `<tbody role="listitem" />` },
  { code: `<tfoot role="listitem" />` },
  { code: `<thead role="listitem" />` },
  { code: `<ul role="listitem" />` },
  { code: `<div className="foo" role="button" />` },
  { code: `<span role="button" />` },
  { code: `<header role="button" />` },
  { code: `<b role="button" />` },
  { code: `<i role="button" />` },
  { code: `<div role="article" />` },
  { code: `<div role="listitem" />` },
  { code: `<div role="presentation" />` },
  { code: `<div role="composite" />` },
  { code: `<div role="widget" />` },
  { code: `<ul role="menubar" />` },
  { code: `<ul role="radiogroup" />` },
  { code: `<ul role="tablist" />` },
  { code: `<ul role="tree" />` },
  { code: `<ul role="treegrid" />` },
  { code: `<ol role="menu" />` },
  { code: `<ol role="menubar" />` },
  { code: `<ol role="radiogroup" />` },
  { code: `<ol role="tablist" />` },
  { code: `<ol role="tree" />` },
  { code: `<ol role="treegrid" />` },
  { code: `<li role="tab" />` },
  { code: `<li role="menuitem" />` },
  { code: `<li role="menuitemcheckbox" />` },
  { code: `<li role="menuitemradio" />` },
  { code: `<li role="row" />` },
  { code: `<li role="treeitem" />` },
  { code: `<fieldset role="radiogroup" />` },
  { code: `<fieldset role="presentation" />` },
  {
    code: `<table role="grid" />`,
    oxcOptions: [
      {
        table: ["grid"],
      },
    ],
  },
];

export const failCases: ReadonlyArray<OxcFixture> = [
  { code: `<article role="button" />` },
  { code: `<aside role="button" />` },
  { code: `<blockquote role="button" />` },
  { code: `<br role="button" />` },
  { code: `<caption role="button" />` },
  { code: `<code role="button" />` },
  { code: `<dd role="button" />` },
  { code: `<del role="button" />` },
  { code: `<details role="button" />` },
  { code: `<dfn role="button" />` },
  { code: `<dir role="button" />` },
  { code: `<dl role="button" />` },
  { code: `<dt role="button" />` },
  { code: `<em role="button" />` },
  { code: `<fieldset role="button" />` },
  { code: `<figcaption role="button" />` },
  { code: `<figure role="button" />` },
  { code: `<footer role="button" />` },
  { code: `<form role="button" />` },
  { code: `<h1 role="button" />` },
  { code: `<h2 role="button" />` },
  { code: `<h3 role="button" />` },
  { code: `<h4 role="button" />` },
  { code: `<h5 role="button" />` },
  { code: `<h6 role="button" />` },
  { code: `<hr role="button" />` },
  { code: `<html role="button" />` },
  { code: `<iframe role="button" />` },
  { code: `<img role="button" />` },
  { code: `<ins role="button" />` },
  { code: `<label role="button" />` },
  { code: `<legend role="button" />` },
  { code: `<li role="button" />` },
  { code: `<main role="button" />` },
  { code: `<mark role="button" />` },
  { code: `<marquee role="button" />` },
  { code: `<menu role="button" />` },
  { code: `<meter role="button" />` },
  { code: `<nav role="button" />` },
  { code: `<ol role="button" />` },
  { code: `<optgroup role="button" />` },
  { code: `<output role="button" />` },
  { code: `<pre role="button" />` },
  { code: `<progress role="button" />` },
  { code: `<ruby role="button" />` },
  { code: `<strong role="button" />` },
  { code: `<sub role="button" />` },
  { code: `<sup role="button" />` },
  { code: `<table role="button" />` },
  { code: `<tbody role="button" />` },
  { code: `<tfoot role="button" />` },
  { code: `<thead role="button" />` },
  { code: `<time role="button" />` },
  { code: `<ul role="button" />` },
  { code: `<p role="button" />` },
  { code: `<section role="button" aria-label="Aardvark" />` },
  { code: `<article role="menuitem" />` },
  { code: `<dd role="menuitem" />` },
  { code: `<dfn role="menuitem" />` },
  { code: `<dt role="menuitem" />` },
  { code: `<fieldset role="menuitem" />` },
  { code: `<figure role="menuitem" />` },
  { code: `<form role="menuitem" />` },
  { code: `<h1 role="menuitem" />` },
  { code: `<h2 role="menuitem" />` },
  { code: `<h3 role="menuitem" />` },
  { code: `<h4 role="menuitem" />` },
  { code: `<h5 role="menuitem" />` },
  { code: `<h6 role="menuitem" />` },
  { code: `<hr role="menuitem" />` },
  { code: `<img role="menuitem" />` },
  { code: `<nav role="menuitem" />` },
  { code: `<ol role="menuitem" />` },
  { code: `<table role="menuitem" />` },
  { code: `<tbody role="menuitem" />` },
  { code: `<tfoot role="menuitem" />` },
  { code: `<thead role="menuitem" />` },
  {
    code: `<table role="button" />`,
    oxcOptions: [
      {
        table: ["grid"],
      },
    ],
  },
];
