// GENERATED FROM OXC — do not edit by hand. Run `pnpm gen:fixtures` to regenerate.
// Source: oxc-project/oxc `crates/oxc_linter/src/rules/jsx_a11y/no_static_element_interactions.rs`
// Each entry is a verbatim port of an OXC `pass`/`fail` vec entry.
// `oxcOptions` (optional) is OXC's first config arg (`Some(json!([…]))`),
// preserved as JS for tests that want to translate it. `oxcSettings`
// (optional) mirrors the third tuple slot used for plugin settings.

export interface OxcFixture {
  code: string;
  oxcOptions?: unknown;
  oxcSettings?: unknown;
  oxcFilename?: string;
}

export const passCases: ReadonlyArray<OxcFixture> = [
  { code: `<div />` },
  { code: `<div className="foo" />` },
  { code: `<div className="foo" {...props} />` },
  { code: `<div onClick={() => void 0} aria-hidden />` },
  { code: `<div onClick={() => void 0} aria-hidden={true} />` },
  { code: `<div onClick={null} />` },
  { code: `<input type="button" onClick={() => void 0} />` },
  { code: `<input type="checkbox" onClick={() => void 0} />` },
  { code: `<input type="color" onClick={() => void 0} />` },
  { code: `<input type="date" onClick={() => void 0} />` },
  { code: `<input type="datetime" onClick={() => void 0} />` },
  { code: `<input type="datetime-local" onClick={() => void 0} />` },
  { code: `<input type="email" onClick={() => void 0} />` },
  { code: `<input type="file" onClick={() => void 0} />` },
  { code: `<input type="hidden" onClick={() => void 0} />` },
  { code: `<input type="image" onClick={() => void 0} />` },
  { code: `<input type="month" onClick={() => void 0} />` },
  { code: `<input type="number" onClick={() => void 0} />` },
  { code: `<input type="password" onClick={() => void 0} />` },
  { code: `<input type="radio" onClick={() => void 0} />` },
  { code: `<input type="range" onClick={() => void 0} />` },
  { code: `<input type="reset" onClick={() => void 0} />` },
  { code: `<input type="search" onClick={() => void 0} />` },
  { code: `<input type="submit" onClick={() => void 0} />` },
  { code: `<input type="tel" onClick={() => void 0} />` },
  { code: `<input type="text" onClick={() => void 0} />` },
  { code: `<input type="time" onClick={() => void 0} />` },
  { code: `<input type="url" onClick={() => void 0} />` },
  { code: `<input type="week" onClick={() => void 0} />` },
  { code: `<datalist onClick={() => {}} />;` },
  { code: `<menuitem onClick={() => {}} />;` },
  { code: `<option onClick={() => void 0} className="foo" />` },
  { code: `<select onClick={() => void 0} className="foo" />` },
  { code: `<textarea onClick={() => void 0} className="foo" />` },
  { code: `<a onClick={() => void 0} href="http://x.y.z" />` },
  { code: `<a onClick={() => void 0} href="http://x.y.z" tabIndex="0" />` },
  { code: `<audio onClick={() => {}} />;` },
  { code: `<form onClick={() => {}} />;` },
  { code: `<form onSubmit={() => {}} />;` },
  { code: `<div role="checkbox" onClick={() => {}} />;` },
  { code: `<div role="columnheader" onClick={() => {}} />;` },
  { code: `<div role="combobox" onClick={() => {}} />;` },
  { code: `<div role="form" onClick={() => {}} />;` },
  { code: `<div role="gridcell" onClick={() => {}} />;` },
  { code: `<div role="link" onClick={() => {}} />;` },
  { code: `<div role="menuitem" onClick={() => {}} />;` },
  { code: `<div role="menuitemcheckbox" onClick={() => {}} />;` },
  { code: `<div role="menuitemradio" onClick={() => {}} />;` },
  { code: `<div role="option" onClick={() => {}} />;` },
  { code: `<div role="radio" onClick={() => {}} />;` },
  { code: `<div role="rowheader" onClick={() => {}} />;` },
  { code: `<div role="searchbox" onClick={() => {}} />;` },
  { code: `<div role="slider" onClick={() => {}} />;` },
  { code: `<div role="spinbutton" onClick={() => {}} />;` },
  { code: `<div role="switch" onClick={() => {}} />;` },
  { code: `<div role="tab" onClick={() => {}} />;` },
  { code: `<div role="textbox" onClick={() => {}} />;` },
  { code: `<div role="treeitem" onClick={() => {}} />;` },
  { code: `<div role="presentation" onKeyDown={() => {}} />;` },
  { code: `<article onClick={() => {}} />;` },
  { code: `<article onDblClick={() => void 0} />;` },
  { code: `<aside onClick={() => {}} />;` },
  { code: `<blockquote onClick={() => {}} />;` },
  { code: `<br onClick={() => {}} />;` },
  { code: `<canvas onClick={() => {}} />;` },
  { code: `<caption onClick={() => {}} />;` },
  { code: `<code onClick={() => {}} />;` },
  { code: `<dd onClick={() => {}} />;` },
  { code: `<del onClick={() => {}} />;` },
  { code: `<details onClick={() => {}} />;` },
  { code: `<dfn onClick={() => {}} />;` },
  { code: `<dir onClick={() => {}} />;` },
  { code: `<dl onClick={() => {}} />;` },
  { code: `<dt onClick={() => {}} />;` },
  { code: `<em onClick={() => {}} />;` },
  { code: `<embed onClick={() => {}} />;` },
  { code: `<fieldset onClick={() => {}} />;` },
  { code: `<figcaption onClick={() => {}} />;` },
  { code: `<figure onClick={() => {}} />;` },
  { code: `<footer onClick={() => {}} />;` },
  { code: `<h1 onClick={() => {}} />;` },
  { code: `<h2 onClick={() => {}} />;` },
  { code: `<h3 onClick={() => {}} />;` },
  { code: `<h4 onClick={() => {}} />;` },
  { code: `<h5 onClick={() => {}} />;` },
  { code: `<h6 onClick={() => {}} />;` },
  { code: `<hr onClick={() => {}} />;` },
  { code: `<html onClick={() => {}} />;` },
  { code: `<iframe onClick={() => {}} />;` },
  { code: `<img onClick={() => {}} />;` },
  { code: `<ins onClick={() => {}} />;` },
  { code: `<label onClick={() => {}} />;` },
  { code: `<legend onClick={() => {}} />;` },
  { code: `<li onClick={() => {}} />;` },
  { code: `<main onClick={() => void 0} />;` },
  { code: `<mark onClick={() => {}} />;` },
  { code: `<marquee onClick={() => {}} />;` },
  { code: `<menu onClick={() => {}} />;` },
  { code: `<meter onClick={() => {}} />;` },
  { code: `<nav onClick={() => {}} />;` },
  { code: `<ol onClick={() => {}} />;` },
  { code: `<optgroup onClick={() => {}} />;` },
  { code: `<output onClick={() => {}} />;` },
  { code: `<p onClick={() => {}} />;` },
  { code: `<pre onClick={() => {}} />;` },
  { code: `<progress onClick={() => {}} />;` },
  { code: `<ruby onClick={() => {}} />;` },
  { code: `<section onClick={() => {}} aria-label="Aa" />;` },
  { code: `<section onClick={() => {}} aria-labelledby="js_1" />;` },
  { code: `<strong onClick={() => {}} />;` },
  { code: `<sub onClick={() => {}} />;` },
  { code: `<summary onClick={() => {}} />;` },
  { code: `<sup onClick={() => {}} />;` },
  { code: `<table onClick={() => {}} />;` },
  { code: `<tbody onClick={() => {}} />;` },
  { code: `<tfoot onClick={() => {}} />;` },
  { code: `<th onClick={() => {}} />;` },
  { code: `<thead onClick={() => {}} />;` },
  { code: `<time onClick={() => {}} />;` },
  { code: `<tr onClick={() => {}} />;` },
  { code: `<video onClick={() => {}} />;` },
  { code: `<ul onClick={() => {}} />;` },
  { code: `<div role="composite" onClick={() => {}} />;` },
  { code: `<div role="input" onClick={() => {}} />;` },
  { code: `<div role="landmark" onClick={() => {}} />;` },
  { code: `<div role="range" onClick={() => {}} />;` },
  { code: `<div role="roletype" onClick={() => {}} />;` },
  { code: `<div role="sectionhead" onClick={() => {}} />;` },
  { code: `<div role="select" onClick={() => {}} />;` },
  { code: `<div role="structure" onClick={() => {}} />;` },
  { code: `<div role="widget" onClick={() => {}} />;` },
  { code: `<div role="window" onClick={() => {}} />;` },
  { code: `<div role="alertdialog" onClick={() => {}} />;` },
  { code: `<div role="application" onClick={() => {}} />;` },
  { code: `<div role="article" onClick={() => {}} />;` },
  { code: `<div role="banner" onClick={() => {}} />;` },
  { code: `<div role="cell" onClick={() => {}} />;` },
  { code: `<div role="complementary" onClick={() => {}} />;` },
  { code: `<div role="contentinfo" onClick={() => {}} />;` },
  { code: `<div role="definition" onClick={() => {}} />;` },
  { code: `<div role="dialog" onClick={() => {}} />;` },
  { code: `<div role="directory" onClick={() => {}} />;` },
  { code: `<div role="document" onClick={() => {}} />;` },
  { code: `<div role="feed" onClick={() => {}} />;` },
  { code: `<div role="figure" onClick={() => {}} />;` },
  { code: `<div role="grid" onClick={() => {}} />;` },
  { code: `<div role="group" onClick={() => {}} />;` },
  { code: `<div role="heading" onClick={() => {}} />;` },
  { code: `<div role="img" onClick={() => {}} />;` },
  { code: `<div role="list" onClick={() => {}} />;` },
  { code: `<div role="listbox" onClick={() => {}} />;` },
  { code: `<div role="listitem" onClick={() => {}} />;` },
  { code: `<div role="log" onClick={() => {}} />;` },
  { code: `<div role="main" onClick={() => {}} />;` },
  { code: `<div role="marquee" onClick={() => {}} />;` },
  { code: `<div role="math" onClick={() => {}} />;` },
  { code: `<div role="menu" onClick={() => {}} />;` },
  { code: `<div role="menubar" onClick={() => {}} />;` },
  { code: `<div role="navigation" onClick={() => {}} />;` },
  { code: `<div role="note" onClick={() => {}} />;` },
  { code: `<div role="progressbar" onClick={() => {}} />;` },
  { code: `<div role="radiogroup" onClick={() => {}} />;` },
  { code: `<div role="region" onClick={() => {}} />;` },
  { code: `<div role="row" onClick={() => {}} />;` },
  { code: `<div role="rowgroup" onClick={() => {}} />;` },
  { code: `<div role="section" onClick={() => {}} />;` },
  { code: `<div role="search" onClick={() => {}} />;` },
  { code: `<div role="separator" onClick={() => {}} />;` },
  { code: `<div role="scrollbar" onClick={() => {}} />;` },
  { code: `<div role="status" onClick={() => {}} />;` },
  { code: `<div role="table" onClick={() => {}} />;` },
  { code: `<div role="tablist" onClick={() => {}} />;` },
  { code: `<div role="tabpanel" onClick={() => {}} />;` },
  { code: `<div role="term" onClick={() => {}} />;` },
  { code: `<div role="timer" onClick={() => {}} />;` },
  { code: `<div role="toolbar" onClick={() => {}} />;` },
  { code: `<div role="tooltip" onClick={() => {}} />;` },
  { code: `<div role="tree" onClick={() => {}} />;` },
  { code: `<div role="treegrid" onClick={() => {}} />;` },
  { code: `<div onCut={() => {}} />;` },
  { code: `<div onPaste={() => {}} />;` },
  { code: `<div onCompositionEnd={() => {}} />;` },
  { code: `<div onCompositionStart={() => {}} />;` },
  { code: `<div onCompositionUpdate={() => {}} />;` },
  { code: `<div onChange={() => {}} />;` },
  { code: `<div onInput={() => {}} />;` },
  { code: `<div onSubmit={() => {}} />;` },
  { code: `<div onSelect={() => {}} />;` },
  { code: `<div onTouchCancel={() => {}} />;` },
  { code: `<div onTouchEnd={() => {}} />;` },
  { code: `<div onTouchMove={() => {}} />;` },
  { code: `<div onTouchStart={() => {}} />;` },
  { code: `<div onScroll={() => {}} />;` },
  { code: `<div onWheel={() => {}} />;` },
  { code: `<div onAbort={() => {}} />;` },
  { code: `<div onCanPlay={() => {}} />;` },
  { code: `<div onCanPlayThrough={() => {}} />;` },
  { code: `<div onDurationChange={() => {}} />;` },
  { code: `<div onEmptied={() => {}} />;` },
  { code: `<div onEncrypted={() => {}} />;` },
  { code: `<div onEnded={() => {}} />;` },
  { code: `<div onError={() => {}} />;` },
  { code: `<div onLoadedData={() => {}} />;` },
  { code: `<div onLoadedMetadata={() => {}} />;` },
  { code: `<div onLoadStart={() => {}} />;` },
  { code: `<div onPause={() => {}} />;` },
  { code: `<div onPlay={() => {}} />;` },
  { code: `<div onPlaying={() => {}} />;` },
  { code: `<div onProgress={() => {}} />;` },
  { code: `<div onRateChange={() => {}} />;` },
  { code: `<div onSeeked={() => {}} />;` },
  { code: `<div onSeeking={() => {}} />;` },
  { code: `<div onStalled={() => {}} />;` },
  { code: `<div onSuspend={() => {}} />;` },
  { code: `<div onTimeUpdate={() => {}} />;` },
  { code: `<div onVolumeChange={() => {}} />;` },
  { code: `<div onWaiting={() => {}} />;` },
  { code: `<div onLoad={() => {}} />;` },
  { code: `<div onError={() => {}} />;` },
  { code: `<div onAnimationStart={() => {}} />;` },
  { code: `<div onAnimationEnd={() => {}} />;` },
  { code: `<div onAnimationIteration={() => {}} />;` },
  { code: `<div className="foo" onKeyDown={() => {}} role="button" />;` },
  { code: `<div onClick={() => {}} role="button" />;` },
  { code: `<button onClick={() => {}} className="foo" />;` },
  { code: `<input type="text" onClick={() => {}} />;` },
  { code: `<input onClick={() => {}} />;` },
  { code: `<button onClick={() => {}} className="foo" />;` },
  { code: `<select onClick={() => {}} />;` },
  { code: `<textarea onClick={() => {}} />;` },
  { code: `<input type="hidden" onClick={() => {}} />;` },
  { code: `<div onClick={() => {}} role="presentation" />;` },
  { code: `<div onClick={() => {}} role="none" />;` },
  { code: `<div onMouseDown={() => {}} role="button" />;` },
  { code: `<div onMouseUp={() => {}} role="button" />;` },
  { code: `<div onKeyPress={() => {}} role="button" />;` },
  { code: `<div onKeyDown={() => {}} role="button" />;` },
  { code: `<div onKeyUp={() => {}} role="button" />;` },
  { code: `<div onClick={() => {}} aria-hidden />;` },
  { code: `<div onClick={() => {}} aria-hidden={true} />;` },
  { code: `<div onClick={() => {}} aria-hidden={false} role="button" />;` },
  { code: `<input onClick={() => {}} type="submit" />;` },
  { code: `<TestComponent onClick={() => {}} />;` },
  { code: `<Button onClick={() => {}} />;` },
  { code: `<div onClick={() => {}} role={ROLE} />`, oxcOptions: [{ allowExpressionValues: true }] },
  {
    code: `<div onClick={() => {}} role={isButton ? "button" : "link"} />`,
    oxcOptions: [{ allowExpressionValues: true }],
  },
  { code: `<div onDblClick={() => {}} />`, oxcOptions: [{ handlers: ["onClick"] }] },
];

export const failCases: ReadonlyArray<OxcFixture> = [
  { code: `<div onClick={() => {}} aria-hidden={false} />;` },
  { code: `<a tabIndex="0" onClick={() => {}} />` },
  {
    code: `<div onClick={() => {}} role={ROLE} />`,
    oxcOptions: [{ allowExpressionValues: false }],
  },
  {
    code: `<div onClick={() => {}} role={isButton ? "button" : "link"} />`,
    oxcOptions: [{ allowExpressionValues: false }],
  },
  { code: `<div onDblClick={() => {}} />`, oxcOptions: [{ handlers: ["onClick", "onDblClick"] }] },
  { code: `<span onClick={() => {}} />;` },
  { code: `<div onClick={() => void 0} role={undefined} />;` },
  { code: `<div onClick={() => void 0} {...props} />;` },
  { code: `<div onKeyUp={() => void 0} aria-hidden={false} />;` },
  { code: `<a onClick={() => void 0} />` },
  { code: `<a tabIndex="0" onClick={() => void 0} />` },
  { code: `<acronym onClick={() => {}} />;` },
  { code: `<applet onClick={() => {}} />;` },
  { code: `<area onClick={() => {}} />;` },
  { code: `<b onClick={() => {}} />;` },
  { code: `<base onClick={() => {}} />;` },
  { code: `<bdi onClick={() => {}} />;` },
  { code: `<bdo onClick={() => {}} />;` },
  { code: `<big onClick={() => {}} />;` },
  { code: `<blink onClick={() => {}} />;` },
  { code: `<body onClick={() => {}} />;` },
  { code: `<center onClick={() => {}} />;` },
  { code: `<cite onClick={() => {}} />;` },
  { code: `<col onClick={() => {}} />;` },
  { code: `<colgroup onClick={() => {}} />;` },
  { code: `<content onClick={() => {}} />;` },
  { code: `<data onClick={() => {}} />;` },
  { code: `<font onClick={() => {}} />;` },
  { code: `<frame onClick={() => {}} />;` },
  { code: `<frameset onClick={() => {}} />;` },
  { code: `<head onClick={() => {}} />;` },
  { code: `<header onClick={() => {}} />;` },
  { code: `<hgroup onClick={() => {}} />;` },
  { code: `<i onClick={() => {}} />;` },
  { code: `<kbd onClick={() => {}} />;` },
  { code: `<keygen onClick={() => {}} />;` },
  { code: `<map onClick={() => {}} />;` },
  { code: `<meta onClick={() => {}} />;` },
  { code: `<noembed onClick={() => {}} />;` },
  { code: `<noscript onClick={() => {}} />;` },
  { code: `<object onClick={() => {}} />;` },
  { code: `<param onClick={() => {}} />;` },
  { code: `<picture onClick={() => {}} />;` },
  { code: `<q onClick={() => {}} />;` },
  { code: `<rp onClick={() => {}} />;` },
  { code: `<rt onClick={() => {}} />;` },
  { code: `<rtc onClick={() => {}} />;` },
  { code: `<s onClick={() => {}} />;` },
  { code: `<samp onClick={() => {}} />;` },
  { code: `<script onClick={() => {}} />;` },
  { code: `<section onClick={() => {}} />;` },
  { code: `<small onClick={() => {}} />;` },
  { code: `<source onClick={() => {}} />;` },
  { code: `<spacer onClick={() => {}} />;` },
  { code: `<span onClick={() => {}} />;` },
  { code: `<strike onClick={() => {}} />;` },
  { code: `<style onClick={() => {}} />;` },
  { code: `<title onClick={() => {}} />;` },
  { code: `<track onClick={() => {}} />;` },
  { code: `<tt onClick={() => {}} />;` },
  { code: `<u onClick={() => {}} />;` },
  { code: `<var onClick={() => {}} />;` },
  { code: `<wbr onClick={() => {}} />;` },
  { code: `<xmp onClick={() => {}} />;` },
  { code: `<div onKeyPress={() => {}} />;` },
  { code: `<div onKeyUp={() => {}} />;` },
  { code: `<div onClick={() => {}} />;` },
  { code: `<div onMouseDown={() => {}} />;` },
  { code: `<div onMouseUp={() => {}} />;` },
];
