import { defineRule } from "../../utils/define-rule.js";
import { normalizeFilename } from "../../utils/normalize-filename.js";
import type { Rule } from "../../utils/rule.js";
import type { RuleContext } from "../../utils/rule-context.js";
import { isNodeOfType } from "../../utils/is-node-of-type.js";
import type { EsTreeNodeOfType } from "../../utils/es-tree-node-of-type.js";

const SVG_PATH_HIGH_PRECISION_PATTERN = /\d+\.\d{4,}/;

const SVG_PATH_ATTRIBUTES = new Set(["d", "points", "transform"]);

// Directory segments that EXPLICITLY signal machine-generated output
// — codegen sinks, design-tool export folders. The high-precision
// paths there come from the exporter, not the engineer; flagging
// them is unactionable noise (re-export reintroduces the precision).
//
// NOTE: deliberately narrow. Earlier broader heuristics (`/icons/`,
// `/icon/`, `/svg/`, `/svgs/`, `/brand/`, `/logo/`, `/logos/`,
// `/flags/`, `/emoji/`, `/emojis/`, `<*Icon>.tsx` basenames) hid
// thousands of real TPs on hand-written, hand-maintained icon
// components (react-grab/icons/*, posthog/icons.tsx, plane/empty-state/
// assets/*). Those are bytes the dev OWNS and CAN optimise — keep
// flagging them.
const AUTO_GENERATED_PATH_SEGMENTS: ReadonlyArray<string> = [
  "/__generated__/",
  "/generated/",
  "/codegen/",
  "/figma-export/",
  "/sketch-export/",
];

const isAutoGeneratedSvgFile = (filename: string | undefined): boolean => {
  if (!filename) return false;
  for (const segment of AUTO_GENERATED_PATH_SEGMENTS) {
    if (filename.includes(segment)) return true;
  }
  return false;
};

// HACK: SVG path strings with 4+ decimals (e.g. `M 10.293847 20.847362`)
// add bytes for sub-pixel precision the user can't see. Most editors
// emit these by default; truncating to 1–2 decimals trims 30–50% off
// markup with no visible difference.
export const renderingSvgPrecision = defineRule<Rule>({
  id: "rendering-svg-precision",
  severity: "warn",
  category: "Performance",
  recommendation:
    "Truncate path/points/transform decimals to 1–2 digits — sub-pixel precision adds bytes with no visible difference",
  create: (context: RuleContext) => {
    const filename = context.getFilename?.();
    const isAutoGenerated = isAutoGeneratedSvgFile(
      filename ? normalizeFilename(filename) : undefined,
    );
    return {
      JSXAttribute(node: EsTreeNodeOfType<"JSXAttribute">) {
        if (isAutoGenerated) return;
        if (!isNodeOfType(node.name, "JSXIdentifier")) return;
        if (!SVG_PATH_ATTRIBUTES.has(node.name.name)) return;
        if (!isNodeOfType(node.value, "Literal")) return;
        const value = node.value.value;
        if (typeof value !== "string") return;
        if (!SVG_PATH_HIGH_PRECISION_PATTERN.test(value)) return;

        context.report({
          node,
          message: `SVG ${node.name.name} attribute uses 4+ decimal precision — truncate to 1–2 decimals to shrink markup with no visible difference`,
        });
      },
    };
  },
});
