export const FAST_QUERY_DELAY_MS = 20;
export const LATE_QUERY_SETTLE_WAIT_MS = 250;
export const PRIMARY_STORE_INITIAL_VERSION = 0;
export const SECONDARY_STORE_INITIAL_VERSION = 100;
export const SLOW_QUERY_DELAY_MS = 200;
export const STORE_VERSION_INCREMENT = 1;
