import { GENERATED_SOURCE_HEADER_CHARACTERS } from "../constants.js";
import { hasGraphqlCodegenSignature } from "./has-graphql-codegen-signature.js";

const GENERATED_SOURCE_DIRECTORY_PATTERN =
  /(?:^|\/)(?:__generated__|generated|__registry__)(?:\/|$)/i;
const GENERATED_SOURCE_FILE_PATTERN = /\.(?:gen|generated)\.[^/]+$/i;
const GENERATED_SOURCE_MARKER_PATTERN =
  /(?:@generated\b|code generated\b|generated by\b|this file was generated via\b|automatically generated\b|auto-generated\b|autogenerated\b)/i;
const WHITESPACE_PATTERN = /\s/;

const hasGeneratedSourceHeader = (sourceText: string): boolean => {
  const header = sourceText.slice(0, GENERATED_SOURCE_HEADER_CHARACTERS);
  let offset = 0;

  while (offset < header.length) {
    while (offset < header.length && WHITESPACE_PATTERN.test(header[offset])) offset++;
    if (offset >= header.length) return false;

    if (header.startsWith("//", offset) || header.startsWith("#!", offset)) {
      const lineEnd = header.indexOf("\n", offset + 2);
      const commentEnd = lineEnd === -1 ? header.length : lineEnd;
      if (GENERATED_SOURCE_MARKER_PATTERN.test(header.slice(offset, commentEnd))) return true;
      offset = commentEnd;
      continue;
    }

    if (header.startsWith("/*", offset)) {
      const blockEnd = header.indexOf("*/", offset + 2);
      const commentEnd = blockEnd === -1 ? header.length : blockEnd + 2;
      if (GENERATED_SOURCE_MARKER_PATTERN.test(header.slice(offset, commentEnd))) return true;
      offset = commentEnd;
      continue;
    }

    return false;
  }

  return false;
};

export const isGeneratedSource = (filePath: string, sourceText: string): boolean =>
  GENERATED_SOURCE_DIRECTORY_PATTERN.test(filePath) ||
  GENERATED_SOURCE_FILE_PATTERN.test(filePath) ||
  hasGeneratedSourceHeader(sourceText) ||
  hasGraphqlCodegenSignature(sourceText);
