import { existsSync, readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import fg from "fast-glob";
import ts from "typescript";
import type { ImportReference, SourceFile } from "../types.js";
import { isPathInsideDirectoryOrEqual } from "../utils/is-path-inside-directory-or-equal.js";
import { resolveEntryWithExtensions } from "../utils/resolve-entry-with-extensions.js";
import {
  collectUnpluginAutoImportGlobalScopes,
  type UnpluginAutoImportGlobalScope,
} from "../../runners/oxlint/collect-unplugin-auto-import-global-scopes.js";

interface AutoImportSourceBinding {
  globalName: string;
  exportName: string;
  scopeDirectory: string;
  sourcePath: string;
}

interface AutoImportScopeBindings {
  bindingsByGlobalName: Map<string, AutoImportSourceBinding>;
  candidateGlobalNames: Set<string>;
}

const GENERATED_AUTO_IMPORT_MARKER = "Generated by unplugin-auto-import";
const AUTO_IMPORT_SOURCE_BINDING_PATTERN =
  /\bconst\s+([A-Za-z_$][\w$]*)\s*:\s*typeof\s+import\(["']([^"']+)["']\)\[["']([^"']+)["']\]/g;

const isNonReferenceIdentifier = (identifier: ts.Identifier): boolean => {
  const parent = identifier.parent;
  return (
    ((ts.isVariableDeclaration(parent) ||
      ts.isParameter(parent) ||
      ts.isFunctionDeclaration(parent) ||
      ts.isFunctionExpression(parent) ||
      ts.isClassDeclaration(parent) ||
      ts.isClassExpression(parent) ||
      ts.isImportClause(parent) ||
      ts.isImportSpecifier(parent) ||
      ts.isNamespaceImport(parent) ||
      ts.isBindingElement(parent)) &&
      parent.name === identifier) ||
    (ts.isImportSpecifier(parent) && parent.propertyName === identifier) ||
    (ts.isBindingElement(parent) && parent.propertyName === identifier) ||
    (ts.isJsxAttribute(parent) && parent.name === identifier) ||
    ((ts.isPropertyAccessExpression(parent) ||
      ts.isPropertyAssignment(parent) ||
      ts.isPropertyDeclaration(parent) ||
      ts.isMethodDeclaration(parent) ||
      ts.isMethodSignature(parent) ||
      ts.isPropertySignature(parent)) &&
      parent.name === identifier) ||
    (ts.isQualifiedName(parent) && parent.right === identifier)
  );
};

const collectUnboundGlobalNames = (
  filePath: string,
  candidateGlobalNames: ReadonlySet<string>,
): Set<string> => {
  let source: string;
  try {
    source = readFileSync(filePath, "utf8");
  } catch {
    return new Set();
  }
  const sourceFile = ts.createSourceFile(filePath, source, ts.ScriptTarget.Latest, true);
  const compilerOptions: ts.CompilerOptions = {
    allowJs: true,
    jsx: ts.JsxEmit.Preserve,
    noLib: true,
    noResolve: true,
    target: ts.ScriptTarget.Latest,
  };
  const compilerHost = ts.createCompilerHost(compilerOptions);
  compilerHost.fileExists = (candidatePath) => candidatePath === filePath;
  compilerHost.getSourceFile = (candidatePath) =>
    candidatePath === filePath ? sourceFile : undefined;
  compilerHost.readFile = (candidatePath) => (candidatePath === filePath ? source : undefined);
  const program = ts.createProgram({
    rootNames: [filePath],
    options: compilerOptions,
    host: compilerHost,
  });
  const typeChecker = program.getTypeChecker();
  const boundSourceFile = program.getSourceFile(filePath);
  if (!boundSourceFile) return new Set();
  const unboundGlobalNames = new Set<string>();
  const visitNode = (node: ts.Node): void => {
    if (
      ts.isIdentifier(node) &&
      candidateGlobalNames.has(node.text) &&
      !isNonReferenceIdentifier(node)
    ) {
      const bindingSymbol = ts.isShorthandPropertyAssignment(node.parent)
        ? typeChecker.getShorthandAssignmentValueSymbol(node.parent)
        : typeChecker.getSymbolAtLocation(node);
      if (!bindingSymbol) unboundGlobalNames.add(node.text);
    }
    ts.forEachChild(node, visitNode);
  };
  visitNode(boundSourceFile);
  return unboundGlobalNames;
};

const findOwningScope = (
  filePath: string,
  scopes: ReadonlyArray<UnpluginAutoImportGlobalScope>,
  rootDirectory: string,
): UnpluginAutoImportGlobalScope | undefined =>
  scopes
    .filter((scope) =>
      isPathInsideDirectoryOrEqual(filePath, resolve(rootDirectory, scope.directory)),
    )
    .toSorted(
      (leftScope, rightScope) => rightScope.directory.length - leftScope.directory.length,
    )[0];

const collectSourceBindings = (
  rootDirectory: string,
  activeScopes: ReadonlyArray<UnpluginAutoImportGlobalScope>,
): AutoImportSourceBinding[] => {
  const bindingsByScopeAndGlobalName = new Map<string, AutoImportSourceBinding | undefined>();
  const declarationFilePaths = fg.sync("**/*auto-import*.d.ts", {
    cwd: rootDirectory,
    absolute: true,
    onlyFiles: true,
    ignore: ["**/node_modules/**", "**/dist/**", "**/build/**"],
  });

  for (const declarationFilePath of declarationFilePaths) {
    const activeScope = findOwningScope(declarationFilePath, activeScopes, rootDirectory);
    if (!activeScope) continue;
    const activeGlobalNames = new Set(activeScope.names);
    const absoluteScopeDirectory = resolve(rootDirectory, activeScope.directory);
    let source: string;
    try {
      source = readFileSync(declarationFilePath, "utf8");
    } catch {
      continue;
    }
    if (!source.includes(GENERATED_AUTO_IMPORT_MARKER)) continue;
    let bindingMatch: RegExpExecArray | null;
    AUTO_IMPORT_SOURCE_BINDING_PATTERN.lastIndex = 0;
    while ((bindingMatch = AUTO_IMPORT_SOURCE_BINDING_PATTERN.exec(source)) !== null) {
      if (!bindingMatch[2].startsWith(".")) continue;
      if (!activeGlobalNames.has(bindingMatch[1])) continue;
      const sourcePath = resolveEntryWithExtensions(
        resolve(dirname(declarationFilePath), bindingMatch[2]),
      );
      if (
        !sourcePath ||
        !existsSync(sourcePath) ||
        !isPathInsideDirectoryOrEqual(sourcePath, absoluteScopeDirectory)
      ) {
        continue;
      }
      const binding = {
        globalName: bindingMatch[1],
        exportName: bindingMatch[3],
        scopeDirectory: activeScope.directory,
        sourcePath,
      };
      const bindingKey = `${binding.scopeDirectory}\0${binding.globalName}`;
      const existingBinding = bindingsByScopeAndGlobalName.get(bindingKey);
      if (
        bindingsByScopeAndGlobalName.has(bindingKey) &&
        (!existingBinding ||
          existingBinding.sourcePath !== binding.sourcePath ||
          existingBinding.exportName !== binding.exportName)
      ) {
        bindingsByScopeAndGlobalName.set(bindingKey, undefined);
      } else if (!bindingsByScopeAndGlobalName.has(bindingKey)) {
        bindingsByScopeAndGlobalName.set(bindingKey, binding);
      }
    }
  }

  return [...bindingsByScopeAndGlobalName.values()].filter(
    (binding): binding is AutoImportSourceBinding => binding !== undefined,
  );
};

export const collectUnpluginAutoImportReferences = (
  rootDirectory: string,
  files: ReadonlyArray<SourceFile>,
): ReadonlyMap<number, ReadonlyArray<ImportReference>> => {
  const activeScopes = collectUnpluginAutoImportGlobalScopes({
    rootDirectory,
    candidateFiles: files.map((file) => file.path),
  });
  const sourceBindings = collectSourceBindings(rootDirectory, activeScopes);
  if (sourceBindings.length === 0) return new Map();
  const scopeBindingsByDirectory = new Map<string, AutoImportScopeBindings>();
  for (const sourceBinding of sourceBindings) {
    const scopeBindings = scopeBindingsByDirectory.get(sourceBinding.scopeDirectory) ?? {
      bindingsByGlobalName: new Map(),
      candidateGlobalNames: new Set(),
    };
    scopeBindings.bindingsByGlobalName.set(sourceBinding.globalName, sourceBinding);
    scopeBindings.candidateGlobalNames.add(sourceBinding.globalName);
    scopeBindingsByDirectory.set(sourceBinding.scopeDirectory, scopeBindings);
  }
  const referencesByModuleIndex = new Map<number, ImportReference[]>();

  for (let moduleIndex = 0; moduleIndex < files.length; moduleIndex++) {
    const file = files[moduleIndex];
    const activeScope = findOwningScope(file.path, activeScopes, rootDirectory);
    if (!activeScope) continue;
    const scopeBindings = scopeBindingsByDirectory.get(activeScope.directory);
    if (!scopeBindings) continue;
    const unboundGlobalNames = collectUnboundGlobalNames(
      file.path,
      scopeBindings.candidateGlobalNames,
    );
    for (const globalName of unboundGlobalNames) {
      const sourceBinding = scopeBindings.bindingsByGlobalName.get(globalName);
      if (!sourceBinding || sourceBinding.sourcePath === file.path) continue;
      const importReference: ImportReference = {
        specifier: sourceBinding.sourcePath,
        importedNames: [
          {
            name: sourceBinding.exportName,
            alias: globalName,
            isNamespace: false,
            isDefault: sourceBinding.exportName === "default",
            isTypeOnly: false,
          },
        ],
        isTypeOnly: false,
        isDynamic: false,
        isSideEffect: false,
        line: 0,
        column: 0,
      };
      const references = referencesByModuleIndex.get(moduleIndex) ?? [];
      references.push(importReference);
      referencesByModuleIndex.set(moduleIndex, references);
    }
  }

  return referencesByModuleIndex;
};
