#!/usr/bin/env bash

set -euo pipefail

TERMINAL_RECORDING_REPOSITORY_ROOT="$PWD"
TERMINAL_RECORDING_DIRECTORY="$(mktemp -d)"
TERMINAL_RECORDING_GIT_DIRECTORY="$TERMINAL_RECORDING_DIRECTORY/.terminal-recording-bin"

python3 "$TERMINAL_RECORDING_REPOSITORY_ROOT/scripts/smoke-tty-prompt.py" \
  --prepare-fixture "$TERMINAL_RECORDING_DIRECTORY"

export PATH="$TERMINAL_RECORDING_GIT_DIRECTORY:$PATH"
unset CI GITHUB_ACTIONS GITLAB_CI BUILDKITE JENKINS_URL TF_BUILD CODEBUILD_BUILD_ID
unset TEAMCITY_VERSION BITBUCKET_BUILD_NUMBER CIRCLECI TRAVIS DRONE GIT_DIR
unset CLAUDECODE CLAUDE_CODE CURSOR_AGENT CODEX_CI CODEX_SANDBOX
unset CODEX_SANDBOX_NETWORK_DISABLED OPENCODE GOOSE_TERMINAL AGENT_SESSION_ID
unset AMP_THREAD_ID AGENT_THREAD_ID AGENT

react-doctor() {
  node "$TERMINAL_RECORDING_REPOSITORY_ROOT/packages/react-doctor/dist/cli.js" "$@"
}
export -f react-doctor

trap 'rm -rf "$TERMINAL_RECORDING_DIRECTORY"' EXIT
cd "$TERMINAL_RECORDING_DIRECTORY"
clear
