// HACK: `$1` aliases preserve the byte-identical built bindings that separate
// direct imports produced before this facade centralized the core boundary.
export {
  AmbiguousProjectError,
  buildSkippedChecks,
  Config,
  createOxlintSpawnSlots,
  DeadCode,
  DEFAULT_PROJECT_SCAN_CONCURRENCY,
  DEFAULT_SHOW_WARNINGS,
  defineConfig,
  detectAiTrainingEnvironment,
  Files,
  Git,
  hasReactRuntime,
  hasReactRuntime as hasReactRuntime$1,
  isReactDoctorError,
  layerOtlp,
  Linter,
  LintPartialFailures,
  mapWithConcurrency,
  mergeReactDoctorConfigs,
  NoReactDependencyError,
  NotADirectoryError,
  OxlintConcurrency,
  OxlintSpawnSlots,
  PackageJsonNotFoundError,
  Progress,
  Project,
  ProjectChecks,
  ProjectNotFoundError,
  ReactDoctorError,
  Reporter,
  resolveScanTarget,
  restoreLegacyThrow,
  runInspect,
  Score,
  SupplyChain,
} from "@react-doctor/core";
export type {
  DiagnoseOptions,
  DiagnoseOptions as DiagnoseOptions$1,
  DiagnoseProjectsInput,
  DiagnoseProjectsInput as DiagnoseProjectsInput$1,
  DiagnoseProjectsResult,
  DiagnoseProjectsResult as DiagnoseProjectsResult$1,
  DiagnoseResult,
  DiagnoseResult as DiagnoseResult$1,
  Diagnostic,
  InspectOutput,
  ProjectDefinition,
  ProjectInfo,
  ProjectResult,
  ProjectResultError,
  ProjectResultOk,
  ReactDoctorConfig,
  ResolvedScanTarget,
  ScoreResult,
  WorkerSlots,
} from "@react-doctor/core";
