import { defineRule } from "../../utils/define-rule.js";
import type { EsTreeNodeOfType } from "../../utils/es-tree-node-of-type.js";
import { getElementType } from "../../utils/get-element-type.js";
import { getJsxPropStringValue } from "../../utils/get-jsx-prop-string-value.js";
import { hasJsxPropIgnoreCase } from "../../utils/has-jsx-prop-ignore-case.js";

const MESSAGE =
  "Screen readers can't pick the right voice because this `lang` isn't a real language code, so use a valid one like `en` or `en-US`.";

// ISO-639-1 two-letter primary subtags. Full BCP-47 validation needs the
// IANA registry; this set plus the three-letter and grandfathered sets
// below covers the real-world primary subtags an author would write.
const COMMON_LANGUAGE_PRIMARY_TAGS: ReadonlySet<string> = new Set([
  "aa",
  "ab",
  "ae",
  "af",
  "ak",
  "am",
  "an",
  "ar",
  "as",
  "av",
  "ay",
  "az",
  "ba",
  "be",
  "bg",
  "bh",
  "bi",
  "bm",
  "bn",
  "bo",
  "br",
  "bs",
  "ca",
  "ce",
  "ch",
  "co",
  "cr",
  "cs",
  "cu",
  "cv",
  "cy",
  "da",
  "de",
  "dv",
  "dz",
  "ee",
  "el",
  "en",
  "eo",
  "es",
  "et",
  "eu",
  "fa",
  "ff",
  "fi",
  "fj",
  "fo",
  "fr",
  "fy",
  "ga",
  "gd",
  "gl",
  "gn",
  "gu",
  "gv",
  "ha",
  "he",
  "hi",
  "ho",
  "hr",
  "ht",
  "hu",
  "hy",
  "hz",
  "ia",
  "id",
  "ie",
  "ig",
  "ii",
  "ik",
  "io",
  "is",
  "it",
  "iu",
  "ja",
  "jv",
  "ka",
  "kg",
  "ki",
  "kj",
  "kk",
  "kl",
  "km",
  "kn",
  "ko",
  "kr",
  "ks",
  "ku",
  "kv",
  "kw",
  "ky",
  "la",
  "lb",
  "lg",
  "li",
  "ln",
  "lo",
  "lt",
  "lu",
  "lv",
  "mg",
  "mh",
  "mi",
  "mk",
  "ml",
  "mn",
  "mr",
  "ms",
  "mt",
  "my",
  "na",
  "nb",
  "nd",
  "ne",
  "ng",
  "nl",
  "nn",
  "no",
  "nr",
  "nv",
  "ny",
  "oc",
  "oj",
  "om",
  "or",
  "os",
  "pa",
  "pi",
  "pl",
  "ps",
  "pt",
  "qu",
  "rm",
  "rn",
  "ro",
  "ru",
  "rw",
  "sa",
  "sc",
  "sd",
  "se",
  "sg",
  "si",
  "sk",
  "sl",
  "sm",
  "sn",
  "so",
  "sq",
  "sr",
  "ss",
  "st",
  "su",
  "sv",
  "sw",
  "ta",
  "te",
  "tg",
  "th",
  "ti",
  "tk",
  "tl",
  "tn",
  "to",
  "tr",
  "ts",
  "tt",
  "tw",
  "ty",
  "ug",
  "uk",
  "ur",
  "uz",
  "ve",
  "vi",
  "vo",
  "wa",
  "wo",
  "xh",
  "yi",
  "yo",
  "za",
  "zh",
  "zu",
]);

// ISO-639-2 / ISO-639-3 three-letter primary subtags (incl. living
// languages without a two-letter code: fil, haw, yue, ceb, gsw, cmn, …).
// A representative real-world subset, not the full registry.
const ISO_639_THREE_LETTER_PRIMARY_TAGS: ReadonlySet<string> = new Set([
  "ace",
  "ach",
  "ada",
  "ady",
  "ain",
  "akk",
  "ale",
  "alt",
  "ang",
  "anp",
  "arb",
  "arc",
  "arn",
  "arp",
  "arw",
  "ast",
  "awa",
  "bal",
  "ban",
  "bas",
  "bej",
  "bem",
  "ber",
  "bho",
  "bik",
  "bin",
  "bla",
  "bra",
  "bua",
  "bug",
  "byn",
  "cad",
  "car",
  "cdo",
  "ceb",
  "chb",
  "chg",
  "chk",
  "chm",
  "chn",
  "cho",
  "chp",
  "chr",
  "chy",
  "cjy",
  "cmn",
  "cnr",
  "cop",
  "cpx",
  "cre",
  "crh",
  "csb",
  "czh",
  "czo",
  "dak",
  "dar",
  "del",
  "den",
  "dgr",
  "din",
  "doi",
  "dsb",
  "dua",
  "dum",
  "dyu",
  "dzo",
  "efi",
  "egy",
  "eka",
  "elx",
  "enm",
  "ewo",
  "fan",
  "fat",
  "fil",
  "fon",
  "frm",
  "fro",
  "frr",
  "frs",
  "fur",
  "gaa",
  "gan",
  "gay",
  "gba",
  "gez",
  "gil",
  "gmh",
  "goh",
  "gon",
  "gor",
  "got",
  "grb",
  "grc",
  "gsw",
  "gwi",
  "hai",
  "hak",
  "haw",
  "hil",
  "hit",
  "hmn",
  "hsb",
  "hsn",
  "hup",
  "iba",
  "ido",
  "inh",
  "jbo",
  "jpr",
  "jrb",
  "kaa",
  "kab",
  "kac",
  "kam",
  "kar",
  "kaw",
  "kbd",
  "kha",
  "kho",
  "kmb",
  "kok",
  "kos",
  "kpe",
  "krc",
  "krl",
  "kru",
  "kum",
  "kut",
  "lad",
  "lah",
  "lam",
  "lez",
  "lol",
  "loz",
  "lua",
  "lui",
  "lun",
  "luo",
  "lus",
  "lzh",
  "mad",
  "mag",
  "mai",
  "mak",
  "man",
  "mas",
  "mdf",
  "mdr",
  "men",
  "mga",
  "mic",
  "min",
  "mlg",
  "mnc",
  "mni",
  "mnp",
  "moh",
  "mos",
  "mus",
  "mwl",
  "mwr",
  "myv",
  "nah",
  "nan",
  "nap",
  "nds",
  "new",
  "nia",
  "niu",
  "nog",
  "non",
  "nqo",
  "nso",
  "nub",
  "nwc",
  "nym",
  "nyn",
  "nyo",
  "nzi",
  "osa",
  "ota",
  "pag",
  "pal",
  "pam",
  "pap",
  "pau",
  "peo",
  "pes",
  "phn",
  "pnb",
  "pon",
  "pro",
  "prs",
  "raj",
  "rap",
  "rar",
  "rom",
  "rup",
  "sad",
  "sah",
  "sam",
  "sas",
  "sat",
  "scn",
  "sco",
  "sel",
  "sga",
  "shn",
  "sid",
  "sma",
  "smj",
  "smn",
  "sms",
  "snk",
  "sog",
  "son",
  "srn",
  "srr",
  "suk",
  "sus",
  "sux",
  "swh",
  "syc",
  "syr",
  "tem",
  "ter",
  "tet",
  "tig",
  "tiv",
  "tkl",
  "tlh",
  "tli",
  "tmh",
  "tog",
  "tpi",
  "tsi",
  "tum",
  "tvl",
  "tyv",
  "udm",
  "uga",
  "umb",
  "vai",
  "vot",
  "wal",
  "war",
  "was",
  "wen",
  "wuu",
  "xal",
  "yao",
  "yap",
  "yue",
  "zap",
  "zen",
  "zgh",
  "zsm",
  "zun",
  "zza",
]);

// Irregular / regular grandfathered tags collapse to a single primary
// subtag (`i-klingon` → `i`, `art-lojban` → `art`, `cel-gaulish` → `cel`,
// `sgn-BE-FR` → `sgn`); the remaining two-letter primaries (en/no/zh) are
// already covered above.
const GRANDFATHERED_PRIMARY_TAGS: ReadonlySet<string> = new Set(["i", "art", "cel", "sgn"]);

const isKnownPrimarySubtag = (primary: string): boolean =>
  COMMON_LANGUAGE_PRIMARY_TAGS.has(primary) ||
  ISO_639_THREE_LETTER_PRIMARY_TAGS.has(primary) ||
  GRANDFATHERED_PRIMARY_TAGS.has(primary);

const isValidLangTag = (value: string): boolean => {
  if (value.length === 0) return false;
  // BCP-47 shape: primary[-script][-region][...]
  const parts = value.split(/[-_]/);
  if (parts.length === 0) return false;
  const primary = parts[0]!.toLowerCase();
  if (!isKnownPrimarySubtag(primary)) return false;
  // Subtags should be alphanumeric.
  return parts.every((part) => /^[A-Za-z0-9]+$/.test(part));
};

// Port of `oxc_linter::rules::jsx_a11y::lang`. Validates `lang`
// attribute on `<html>` and similar elements.
export const lang = defineRule({
  id: "lang",
  title: "Invalid lang attribute value",
  tags: ["react-jsx-only"],
  severity: "warn",
  recommendation:
    "Use a valid language code like `en` or `en-US` so screen readers choose the right pronunciation rules.",
  category: "Accessibility",
  create: (context) => ({
    JSXOpeningElement(node: EsTreeNodeOfType<"JSXOpeningElement">) {
      const tag = getElementType(node, context.settings);
      if (tag !== "html") return;
      const langAttr = hasJsxPropIgnoreCase(node.attributes, "lang");
      if (!langAttr) return;
      const attributeValue = langAttr.value;
      if (attributeValue && attributeValue.type === "JSXExpressionContainer") {
        const expression = (
          attributeValue as {
            expression: { type?: string; name?: string; value?: unknown };
          }
        ).expression;
        // lang={undefined} / lang={null} are explicit invalid values.
        if (
          (expression.type === "Identifier" && expression.name === "undefined") ||
          (expression.type === "Literal" && expression.value === null)
        ) {
          context.report({ node: langAttr, message: MESSAGE });
          return;
        }
      }
      const value = getJsxPropStringValue(langAttr);
      if (value === null) return;
      if (!isValidLangTag(value)) {
        context.report({ node: langAttr, message: MESSAGE });
      }
    },
  }),
});
