//! Codegen parity harness (Stage 7 — `CodegenReactiveFunction`).
//!
//! Stage 7 turns the post-`PruneHoistedContexts`
//! [`ReactiveFunction`](react_compiler_oxc::reactive_scopes::ReactiveFunction)
//! into compiled JS. The TS oracle prints this via babel-generator
//! (`result.code`); the Rust side builds an oxc AST and prints it via
//! `oxc::codegen`. babel-generator and oxc-codegen format differently, so the
//! two are **not byte-comparable** directly.
//!
//! ## Canonical comparison
//!
//! We normalize *both* sides through the *same* oxc parser + printer:
//!
//! ```text
//! oracle_canonical = canonicalize(ref.code)        // re-parse + print the oracle output
//! rust_canonical   = canonicalize(rust_output)     // re-parse + print the Rust output
//! ```
//!
//! (The Rust side is already an oxc AST, so it could be printed directly; we
//! route it through [`canonicalize`] too for symmetry and to guarantee both
//! sides see exactly the same parser+printer pipeline.) Because both pass
//! through the identical [`Codegen`](oxc::codegen) configuration, formatting is
//! identical and only real program/AST differences surface.
//!
//! ## Oracle refs
//!
//! Each `tests/fixtures/hir/<name>.code` is the raw `result.code` from the TS
//! compiler under default config (`compilationMode: 'all'`), generated by the
//! all-stage oracle and **never hand-edited**. The harness canonicalizes them at
//! test time. Fixtures whose oracle output is empty (the compiler errored:
//! `compound_update`, `for-in-lval`, `for-of-lval`, `import_hook`) have no
//! `.code` ref. `useMemo-simple` is now included (manual memoization flows
//! through `dropManualMemoization`).
//!
//! ## Status
//!
//! The Rust Stage 7 emitter is fully ported and matches the oracle on **all**
//! stored `.code` refs under the canonical comparison — including the manual-memo
//! `useMemo-simple` fixture, whose `useMemo` the compiler re-derives into the
//! cache-slot memoization. The measured-parity test ([`codegen_parity_measured`])
//! asserts the full match and runs by default; the per-fixture `codegen_parity_*`
//! tests below pin each fixture so a regression names the offender.

use std::fs;
use std::path::{Path, PathBuf};

use react_compiler_oxc::{canonicalize, codegen};

/// No fixtures are excluded — `useMemo-simple` (manual memoization) is handled by
/// `dropManualMemoization` and is codegen'd like any other fixture.
const EXCLUDED: &[&str] = &[];

fn fixtures_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/hir")
}

/// Normalize CRLF + trailing whitespace so the harness is stable across OSes.
fn normalize(text: &str) -> String {
    text.replace("\r\n", "\n").trim_end().to_string()
}

struct Fixture {
    name: String,
    ext: String,
    source: String,
    /// The raw oracle `result.code` (the `.code` ref).
    oracle: String,
}

/// Collect the fixtures with a stored `.code` (oracle `result.code`) ref.
fn collect_fixtures() -> Vec<Fixture> {
    let dir = fixtures_dir();
    let mut entries: Vec<PathBuf> = fs::read_dir(&dir)
        .expect("fixtures dir exists")
        .filter_map(|e| e.ok().map(|e| e.path()))
        .filter(|p| {
            matches!(
                p.extension().and_then(|e| e.to_str()),
                Some("js" | "jsx" | "ts" | "tsx")
            )
        })
        .collect();
    entries.sort();

    entries
        .into_iter()
        .filter_map(|input| {
            let name = input.file_stem().unwrap().to_str().unwrap().to_string();
            if EXCLUDED.contains(&name.as_str()) {
                return None;
            }
            let reference_path = input.with_extension("code");
            if !reference_path.exists() {
                return None;
            }
            let ext = input
                .extension()
                .and_then(|e| e.to_str())
                .unwrap_or("tsx")
                .to_string();
            let source = fs::read_to_string(&input).expect("read fixture");
            let oracle = fs::read_to_string(&reference_path).expect("read .code ref");
            Some(Fixture {
                name,
                ext,
                source,
                oracle,
            })
        })
        .collect()
}

/// `(matched, total, mismatched_fixture_names)` under the canonical comparison.
fn tally() -> (usize, usize, Vec<String>) {
    let fixtures = collect_fixtures();
    let total = fixtures.len();
    let mut matched = 0usize;
    let mut mismatched = Vec::new();
    for fixture in &fixtures {
        let oracle_canonical = normalize(&canonicalize(&fixture.oracle));
        let rust_output = codegen(&fixture.source, &format!("{}.{}", fixture.name, fixture.ext));
        let rust_canonical = normalize(&canonicalize(&rust_output));
        if oracle_canonical == rust_canonical {
            matched += 1;
        } else {
            mismatched.push(fixture.name.clone());
        }
    }
    (matched, total, mismatched)
}

/// Measured Stage 7 parity under the canonical comparison. Run with
/// `--nocapture` to see the matched/total count.
///
/// The emitter is fully ported, so this asserts the full match (every stored
/// `.code` ref canonicalizes identically to the Rust output). A regression drops
/// the matched count below `total` and prints the offending fixtures.
#[test]
fn codegen_parity_measured() {
    let (matched, total, mismatched) = tally();
    eprintln!("\n=== Codegen canonical parity: {matched}/{total} fixtures matched ===");
    if !mismatched.is_empty() {
        eprintln!("  mismatched ({}): {}", mismatched.len(), mismatched.join(", "));
    }
    assert!(total >= 50, "expected >= 50 `.code` refs, found {total}");
    assert_eq!(
        matched, total,
        "{} fixture(s) regressed: {}",
        mismatched.len(),
        mismatched.join(", ")
    );
}

/// The oracle refs must all parse + round-trip cleanly through oxc (canonicalize
/// must not panic and must produce non-empty output for non-empty refs). This
/// guards the refs themselves — if a ref were corrupt or hand-edited into
/// invalid JS, canonicalization would drop it to empty.
///
/// Always runs (not ignored) so the refs stay valid even while the emitter is a
/// stub.
#[test]
fn oracle_refs_round_trip_cleanly() {
    let fixtures = collect_fixtures();
    assert!(
        fixtures.len() >= 50,
        "expected >= 50 `.code` refs, found {}",
        fixtures.len()
    );
    let mut failures = Vec::new();
    for fixture in &fixtures {
        let canonical = canonicalize(&fixture.oracle);
        if normalize(&canonical).is_empty() && !normalize(&fixture.oracle).is_empty() {
            failures.push(format!(
                "{}: canonicalize dropped a non-empty ref to empty (invalid JS?)",
                fixture.name
            ));
        }
    }
    assert!(
        failures.is_empty(),
        "{} oracle ref(s) failed to round-trip:\n{}",
        failures.len(),
        failures.join("\n")
    );
}

/// Prove canonicalization is idempotent on a representative ref:
///
/// ```text
/// canonicalize(x) == canonicalize(canonicalize(x))
/// ```
///
/// i.e. once normalized through oxc's parser+printer, re-running the pipeline is
/// a fixed point. This is the property the canonical comparison relies on — it
/// means the oracle and Rust sides land on the same normal form regardless of
/// their original (babel vs. oxc) formatting.
#[test]
fn canonicalization_is_idempotent() {
    // Use the spec's worked example (jsx_element) plus a no-memo fixture and a
    // control-flow fixture so the property is checked across shapes.
    for name in ["jsx_element", "member_call", "ssa-switch"] {
        let ref_path = fixtures_dir().join(format!("{name}.code"));
        if !ref_path.exists() {
            continue;
        }
        let raw = fs::read_to_string(&ref_path).expect("read .code ref");
        let once = canonicalize(&raw);
        let twice = canonicalize(&once);
        assert_eq!(
            normalize(&once),
            normalize(&twice),
            "canonicalization not idempotent for {name}"
        );
        assert!(
            !normalize(&once).is_empty(),
            "canonicalization produced empty output for {name}"
        );
    }
}

/// Smoke-test the canonical pipeline on the spec's worked example: the
/// `jsx_element` oracle ref must contain the memoization runtime and survive a
/// round-trip. This documents the expected oracle shape and guards the
/// `jsx_element.code` ref specifically.
#[test]
fn jsx_element_oracle_ref_shape() {
    let ref_path = fixtures_dir().join("jsx_element.code");
    let raw = fs::read_to_string(&ref_path).expect("jsx_element.code ref exists");
    assert!(
        raw.contains("from \"react/compiler-runtime\""),
        "jsx_element oracle ref should import the compiler runtime"
    );
    assert!(
        raw.contains("_c(3)"),
        "jsx_element oracle ref should size the cache to 3 slots"
    );
    let canonical = canonicalize(&raw);
    assert!(
        canonical.contains("react/compiler-runtime"),
        "canonicalized jsx_element should preserve the runtime import"
    );
    // Idempotent on this exact ref.
    assert_eq!(normalize(&canonicalize(&canonical)), normalize(&canonical));
}

/// A function with unreachable code that contains a hoisted function declaration
/// (`function bar()` after a `return`) is one the compiler declines to compile:
/// `HIRBuilder.build()` records the Todo `Support functions with unreachable code
/// that may contain hoisted declarations`, and `processFn` then leaves the
/// original source untouched. Under `@panicThreshold:"none"` (recoverable) the
/// emitted module is the source verbatim. This pins that bailout: the Rust output
/// must equal the oracle (source retained, no `_c` import, no memoization).
#[test]
fn unreachable_hoisted_function_bails_retaining_source() {
    let dir = fixtures_dir();
    let source = fs::read_to_string(dir.join("unreachable-hoisted-function.js"))
        .expect("unreachable-hoisted-function.js fixture exists");
    let oracle = fs::read_to_string(dir.join("unreachable-hoisted-function.code"))
        .expect("unreachable-hoisted-function.code ref exists");
    let rust = codegen(&source, "unreachable-hoisted-function.js");
    // The function bailed, so the emitter must not have inserted the runtime import.
    assert!(
        !rust.contains("react/compiler-runtime"),
        "a bailed function must not pull in the compiler runtime import"
    );
    assert_eq!(
        normalize(&canonicalize(&oracle)),
        normalize(&canonicalize(&rust)),
        "unreachable-hoisted-function: Rust output must match the oracle (source retained)"
    );
}

/// A `@script` source type makes the harness parse the file as a script
/// (`parseSourceType`), so `addImportsToProgram` emits the runtime cache import as
/// a `const { c: _c } = require("react/compiler-runtime")` destructure rather than
/// an ESM `import` declaration (`Imports.ts:291-313`). This pins that form.
///
/// The faithful oracle for `@script` is the corpus `.code` ref (generated by the
/// real harness with `sourceType: 'script'`); note `verify/capture-code.ts` cannot
/// reproduce it because it hardcodes `sourceType: 'module'`. The corpus ref differs
/// from the Rust output only by a babel-generator comment-attachment artifact (the
/// `// @script` docblock merges onto the require line in the oracle), so this test
/// compares the bodies after dropping the leading comment line on both sides.
#[test]
fn script_source_type_emits_require_cache_import() {
    let corpus = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/corpus");
    let source =
        fs::read_to_string(corpus.join("script-source-type.src.js")).expect("script fixture");
    let oracle =
        fs::read_to_string(corpus.join("script-source-type.code")).expect("script oracle ref");
    let rust = codegen(&source, "script-source-type.js");
    // The runtime cache import must be the `require(…)` destructure form, not an
    // ESM `import`.
    assert!(
        rust.contains("const { c: _c } = require(\"react/compiler-runtime\")"),
        "@script must emit the require-destructure cache import, got:\n{rust}"
    );
    assert!(
        !rust.contains("import { c as _c } from"),
        "@script must not emit an ESM import for the cache runtime"
    );
    // Compare the program bodies (dropping the leading docblock comment line, the
    // only divergence — a babel comment-attachment artifact).
    let drop_first_comment = |text: &str| -> String {
        let canon = normalize(&canonicalize(text));
        canon
            .lines()
            .filter(|l| !l.trim_start().starts_with("// @script"))
            .collect::<Vec<_>>()
            .join("\n")
    };
    assert_eq!(
        drop_first_comment(&oracle),
        drop_first_comment(&rust),
        "script-source-type: Rust body must match the oracle (require form)"
    );
}

/// When the program already binds/references `_c`, the memo-cache runtime import
/// must be aliased to a fresh name (`_c2`) instead of colliding with the user
/// binding. This ports `Imports.ts::addMemoCacheImport` → `newUid('_c')` →
/// `scope.generateUid('_c')` (which yields `_c`, `_c2`, `_c3`, …). The fixture
/// declares `const _c = props.a;`, so the runtime import — and every
/// `const $ = _c2(N)` cache preface — must use `_c2`. The oracle ref
/// (`conflicting-c-import-name.code`) was captured fresh from the TS compiler via
/// `verify/capture-code.ts`.
#[test]
fn memo_cache_import_avoids_existing_c_binding() {
    let dir = fixtures_dir();
    let source = fs::read_to_string(dir.join("conflicting-c-import-name.tsx"))
        .expect("conflicting-c-import-name.tsx fixture exists");
    let oracle = fs::read_to_string(dir.join("conflicting-c-import-name.code"))
        .expect("conflicting-c-import-name.code ref exists");
    let rust = codegen(&source, "conflicting-c-import-name.tsx");
    // The runtime import must be aliased to `_c2` (not `_c`, which the user binds).
    assert!(
        rust.contains("c as _c2") && rust.contains("_c2("),
        "runtime import must avoid the existing `_c` binding (expected `_c2`):\n{rust}"
    );
    assert!(
        !rust.contains("c as _c "),
        "runtime import must not collide with the user's `_c` binding"
    );
    assert_eq!(
        normalize(&canonicalize(&oracle)),
        normalize(&canonicalize(&rust)),
        "conflicting-c-import-name: Rust output must match the oracle (`_c2` alias)"
    );
}

/// The JSX-whitespace normalization (`trim_jsx_text` applied in the canonicalizer)
/// must collapse *insignificant* (newline-adjacent / inter-line) whitespace so a
/// prettier-rewrapped multi-line oracle and a single-line Rust emission compare
/// equal — while preserving *significant* (same-line) whitespace, which is part of
/// the rendered output. This is the property that makes the parity comparison
/// formatting-independent for JSX without hiding a real text difference.
#[test]
fn jsx_whitespace_insignificant_collapses_significant_preserved() {
    // Multi-line (prettier-style) vs single-line: the same element children.
    let multi = "const x = (\n  <div>\n    a {b}\n    {c} d\n  </div>\n);";
    let single = "const x = <div>a {b}{c} d</div>;";
    assert_eq!(
        normalize(&canonicalize(multi)),
        normalize(&canonicalize(single)),
        "newline-adjacent JSX whitespace must normalize identically across line-wrapping"
    );

    // Significant whitespace MUST be preserved: `{x} {y}` (a real space between two
    // expression containers on the same line) is NOT the same as `{x}{y}`.
    let with_space = "const x = <a>{p} {q}</a>;";
    let no_space = "const x = <a>{p}{q}</a>;";
    assert_ne!(
        normalize(&canonicalize(with_space)),
        normalize(&canonicalize(no_space)),
        "a same-line space between JSX expressions is significant and must not be dropped"
    );
    // …and the with-space form keeps its space verbatim through canonicalize.
    assert!(
        canonicalize(with_space).contains("{p} {q}"),
        "canonicalize must preserve the significant inter-expression space"
    );
}

/// FBT subtrees (`<fbt>`/`<fbs>`) preserve ALL whitespace verbatim (matching
/// `BuildHIR`'s `fbtDepth > 0` branch): the fbt transform has its own whitespace
/// rules, so the JSX trim must be skipped inside them. A multi-line `<fbt>` block
/// is therefore NOT collapsed to single-line.
#[test]
fn jsx_whitespace_preserved_inside_fbt() {
    let multi = "const x = (\n  <fbt desc=\"d\">\n    Hello\n    {name}\n  </fbt>\n);";
    // Inside fbt the text is preserved, so the multi-line form keeps its newlines
    // and does not collapse to the single-line form a non-fbt element would.
    let single = "const x = <fbt desc=\"d\">Hello{name}</fbt>;";
    assert_ne!(
        normalize(&canonicalize(multi)),
        normalize(&canonicalize(single)),
        "fbt whitespace must be preserved verbatim (not trimmed like normal JSX)"
    );
}

/// The JSX-trim normalization is itself idempotent: trimming an already-trimmed
/// JSX tree is a no-op, so `canonicalize` remains a fixed point even on inputs
/// that exercise the new normalization.
#[test]
fn jsx_whitespace_normalization_is_idempotent() {
    for src in [
        "const x = (\n  <div>\n    a {b}\n  </div>\n);",
        "const x = <a>{p} {q}</a>;",
        "const x = (\n  <fbt desc=\"d\">\n    Hello\n  </fbt>\n);",
        "const x = <>a {b}{\" \"}{c}</>;",
    ] {
        let once = canonicalize(src);
        let twice = canonicalize(&once);
        assert_eq!(
            normalize(&once),
            normalize(&twice),
            "canonicalize must be idempotent on `{src}`"
        );
    }
}

/// The `{" "}` JSX-space form (an expression container holding a single-space
/// string literal) is semantically identical to a literal JSX space: React renders
/// `<a>{" "}b</a>` and `<a> b</a>` the same. babel-generator emits the compiler's
/// `{" "}` verbatim while the prettier-formatted `.expect.md` rewrites it to a
/// literal space, so the canonicalizer must fold the container form into the text
/// form. This is exactly prettier's substitution and is restricted to a single
/// literal space, so it cannot hide a real difference.
#[test]
fn jsx_single_space_container_equals_literal_space() {
    // `{" "}` and a literal space between two expressions canonicalize identically.
    let container = "const x = <>{a}{\" \"}{b}</>;";
    let literal = "const x = <>{a} {b}</>;";
    assert_eq!(
        normalize(&canonicalize(container)),
        normalize(&canonicalize(literal)),
        "`{{\" \"}}` must canonicalize to the same form as a literal JSX space"
    );

    // A non-space string literal container is left as a container (it is not the
    // JSX-space form): `{"x"}` must NOT be folded into the bare text `x`, so it
    // stays distinct from authoring `x` as JSX text would be irrelevant here — the
    // point is the fold is whitespace-only. `{"  "}` (two spaces) is likewise left
    // alone (React renders it verbatim; prettier keeps it as a container too).
    let two_spaces = "const x = <>{a}{\"  \"}{b}</>;";
    assert!(
        canonicalize(two_spaces).contains("\"  \""),
        "a multi-space `{{\"  \"}}` container must be preserved verbatim, not folded"
    );

    // Inside fbt the fold is skipped (fbt preserves whitespace verbatim), so a
    // `{" "}` inside <fbt> stays a container.
    let fbt = "const x = <fbt desc=\"d\">{a}{\" \"}{b}</fbt>;";
    assert!(
        canonicalize(fbt).contains("{\" \"}"),
        "the `{{\" \"}}` fold must be skipped inside fbt subtrees"
    );
}

/// Pin the `jsx_fragment` fixture: a JSX fragment whose children include a `{' '}`
/// explicit-space marker between an expression and a nested element. The compiler
/// preserves `{" "}` verbatim (matching babel-generator); the canonicalizer folds
/// it to a literal space so the Rust emission matches the prettier-formatted
/// oracle ref. This locks the `{" "}`-fold fix against regression.
#[test]
fn jsx_fragment_explicit_space_matches_oracle() {
    let dir = fixtures_dir();
    let source =
        fs::read_to_string(dir.join("jsx_fragment.js")).expect("jsx_fragment.js fixture exists");
    let oracle =
        fs::read_to_string(dir.join("jsx_fragment.code")).expect("jsx_fragment.code ref exists");
    let rust = codegen(&source, "jsx_fragment.js");
    assert_eq!(
        normalize(&canonicalize(&oracle)),
        normalize(&canonicalize(&rust)),
        "jsx_fragment: Rust output must match the oracle ({{' '}} folded to a space)"
    );
}

/// Run one corpus fixture (`<name>.src.<ext>` + `<name>.code`) through codegen and
/// assert canonical equality with its oracle ref. Used to regression-lock the
/// config-gated codegen features (instrument-forget, hook-guards) at the exact
/// fixture granularity (in addition to the floored corpus tally).
fn assert_corpus_fixture_matches(name: &str, ext: &str) {
    let corpus = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/corpus");
    let source = fs::read_to_string(corpus.join(format!("{name}.src.{ext}")))
        .unwrap_or_else(|_| panic!("{name}.src.{ext} fixture exists"));
    let oracle = fs::read_to_string(corpus.join(format!("{name}.code")))
        .unwrap_or_else(|_| panic!("{name}.code ref exists"));
    let rust = codegen(&source, &format!("{name}.{ext}"));
    assert_eq!(
        normalize(&canonicalize(&oracle)),
        normalize(&canonicalize(&rust)),
        "{name}: Rust output must match the oracle"
    );
}

/// `@enableEmitInstrumentForget` (`CodegenReactiveFunction.ts:247-307`): each named
/// compiled function gets an `if (DEV && shouldInstrument) useRenderCounter("<id>",
/// "<filepath>");` at the top of its body, plus the sorted `react-compiler-runtime`
/// import. Locks the feature against regression.
#[test]
fn emit_instrument_forget_matches_oracle() {
    assert_corpus_fixture_matches("codegen-instrument-forget-test", "js");
}

/// The instrument-forget import-local names are `newUid`-resolved against the
/// program: `shouldInstrument` collides with the fixture's local bindings and is
/// aliased to `_shouldInstrument3`, while the hook-named `useRenderCounter` keeps
/// its name.
#[test]
fn emit_instrument_forget_resolves_name_collisions() {
    assert_corpus_fixture_matches("conflict-codegen-instrument-forget", "js");
}

/// Instrument-forget composes with `@gating`: the instrumentation `if` is emitted
/// inside each compiled (gated) branch, and the `react-compiler-runtime` import
/// sorts before both the `_c` and `ReactForgetFeatureFlag` imports.
#[test]
fn emit_instrument_forget_with_gating_matches_oracle() {
    assert_corpus_fixture_matches("gating__codegen-instrument-forget-gating-test", "js");
}

/// `@enableEmitHookGuards` (`CodegenReactiveFunction.ts:150-159,1352-1424`): the
/// whole body is wrapped in `try { $dispatcherGuard(0); … } finally {
/// $dispatcherGuard(1); }` and every hook call in a `(function () { try {
/// $dispatcherGuard(2); return <call>; } finally { $dispatcherGuard(3); } })()`
/// IIFE. Locks the feature against regression.
#[test]
fn emit_hook_guards_matches_oracle() {
    assert_corpus_fixture_matches("flag-enable-emit-hook-guards", "ts");
}
