import type { VideoContent } from "../types";

export const reactContent: VideoContent = {
  scanTitle: "Scan for React issues",
  fixPrompt: "fix my React code",
  scannedIssues: [
    { message: "Array index used as key", severity: "error", pointsLost: 5, file: "UserList.tsx:14" },
    { message: "Component defined inside component", severity: "error", pointsLost: 5, file: "Dashboard.tsx:87" },
    { message: "Derived state in useEffect", severity: "error", pointsLost: 5, file: "Cart.tsx:23" },
    { message: "Missing cleanup in useEffect", severity: "error", pointsLost: 5, file: "Chat.tsx:41" },
    { message: "setState in useEffect without deps", severity: "error", pointsLost: 5, file: "Feed.tsx:19" },
    { message: "New object created every render", severity: "warning", pointsLost: 2, file: "Theme.tsx:8" },
    { message: "Inline function as prop", severity: "warning", pointsLost: 2, file: "Button.tsx:32" },
    { message: "useState synced from prop", severity: "error", pointsLost: 5, file: "Modal.tsx:11" },
    { message: "Unnecessary re-render detected", severity: "warning", pointsLost: 2, file: "Sidebar.tsx:55" },
    { message: "Missing error boundary", severity: "warning", pointsLost: 2, file: "App.tsx:1" },
    { message: "Large component (300+ lines)", severity: "warning", pointsLost: 2, file: "Settings.tsx:1" },
    { message: "Direct DOM mutation in component", severity: "error", pointsLost: 5, file: "Canvas.tsx:67" },
    { message: "Fetch in useEffect without race guard", severity: "error", pointsLost: 5, file: "Profile.tsx:29" },
    { message: "Context provider re-renders all consumers", severity: "warning", pointsLost: 2, file: "AuthProvider.tsx:18" },
    { message: "Stale closure in event handler", severity: "error", pointsLost: 5, file: "Editor.tsx:104" },
    { message: "Proper use of useMemo", severity: "ok", pointsLost: 0, file: "Table.tsx:42" },
    { message: "Correct key usage in list", severity: "ok", pointsLost: 0, file: "NavBar.tsx:26" },
    { message: "Clean effect cleanup", severity: "ok", pointsLost: 0, file: "Timer.tsx:15" },
    { message: "Server action missing auth check", severity: "error", pointsLost: 5, file: "deleteUser.ts:3" },
    { message: "Prop drilling through 4+ levels", severity: "warning", pointsLost: 2, file: "Layout.tsx:12" },
    { message: "useCallback with empty deps", severity: "ok", pointsLost: 0, file: "Search.tsx:31" },
    { message: "Suspense boundary in place", severity: "ok", pointsLost: 0, file: "page.tsx:7" },
    { message: "Lazy loading configured", severity: "ok", pointsLost: 0, file: "routes.tsx:4" },
    { message: "Accessible form labels", severity: "ok", pointsLost: 0, file: "LoginForm.tsx:19" },
    { message: "State reset on unmount", severity: "ok", pointsLost: 0, file: "Wizard.tsx:38" },
    { message: "Ref used for non-reactive value", severity: "ok", pointsLost: 0, file: "Video.tsx:22" },
    { message: "useEffect runs on every render", severity: "error", pointsLost: 5, file: "Tooltip.tsx:9" },
    { message: "Spreading props without filtering", severity: "warning", pointsLost: 2, file: "Input.tsx:5" },
    { message: "forwardRef used correctly", severity: "ok", pointsLost: 0, file: "Select.tsx:14" },
    { message: "Event handler recreated each render", severity: "warning", pointsLost: 2, file: "Card.tsx:47" },
    { message: "Deeply nested ternary in JSX", severity: "warning", pointsLost: 2, file: "Status.tsx:33" },
    { message: "Missing loading state for async data", severity: "warning", pointsLost: 2, file: "Posts.tsx:21" },
    { message: "useReducer for complex state", severity: "ok", pointsLost: 0, file: "Form.tsx:8" },
    { message: "Mutable ref for interval ID", severity: "ok", pointsLost: 0, file: "Countdown.tsx:11" },
    { message: "setState called during render", severity: "error", pointsLost: 5, file: "Filter.tsx:28" },
    { message: "Large bundle from barrel import", severity: "warning", pointsLost: 2, file: "index.ts:1" },
    { message: "Uncontrolled to controlled switch", severity: "error", pointsLost: 5, file: "Toggle.tsx:16" },
    { message: "Layout thrashing in useLayoutEffect", severity: "error", pointsLost: 5, file: "Resize.tsx:39" },
    { message: "Proper Suspense fallback", severity: "ok", pointsLost: 0, file: "loading.tsx:3" },
    { message: "Memo comparison function correct", severity: "ok", pointsLost: 0, file: "Row.tsx:52" },
    { message: "Async setState after unmount", severity: "error", pointsLost: 5, file: "Upload.tsx:44" },
    { message: "Missing key in Fragment list", severity: "error", pointsLost: 5, file: "Tabs.tsx:20" },
    { message: "Unnecessary useEffect for transform", severity: "warning", pointsLost: 2, file: "Price.tsx:13" },
    { message: "Portal used for modal overlay", severity: "ok", pointsLost: 0, file: "Dialog.tsx:7" },
    { message: "Stable callback ref pattern", severity: "ok", pointsLost: 0, file: "Measure.tsx:25" },
    { message: "Duplicate provider in tree", severity: "warning", pointsLost: 2, file: "layout.tsx:31" },
    { message: "String ref instead of createRef", severity: "error", pointsLost: 5, file: "Legacy.tsx:58" },
    { message: "Correct use of flushSync", severity: "ok", pointsLost: 0, file: "Scroll.tsx:36" },
    { message: "Hydration mismatch detected", severity: "error", pointsLost: 5, file: "page.tsx:1" },
    { message: "Proper error boundary fallback", severity: "ok", pointsLost: 0, file: "error.tsx:5" },
    { message: "Infinite loop in useEffect", severity: "error", pointsLost: 5, file: "Poll.tsx:17" },
    { message: "Object spread in dependency array", severity: "error", pointsLost: 5, file: "useFilters.ts:24" },
    { message: "Unmemoized context value", severity: "warning", pointsLost: 2, file: "CartProvider.tsx:9" },
    { message: "Conditional hook call", severity: "error", pointsLost: 5, file: "UserCard.tsx:12" },
    { message: "Proper key on sibling elements", severity: "ok", pointsLost: 0, file: "Menu.tsx:41" },
    { message: "useRef for previous value", severity: "ok", pointsLost: 0, file: "Diff.tsx:18" },
    { message: "Render prop causes re-mount", severity: "error", pointsLost: 5, file: "DataGrid.tsx:73" },
    { message: "Missing displayName on memo", severity: "warning", pointsLost: 2, file: "Badge.tsx:4" },
    { message: "Controlled input without onChange", severity: "error", pointsLost: 5, file: "Checkout.tsx:56" },
    { message: "Proper use of startTransition", severity: "ok", pointsLost: 0, file: "Search.tsx:48" },
    { message: "Effect depends on unstable reference", severity: "error", pointsLost: 5, file: "useSync.ts:31" },
    { message: "Correct children prop type", severity: "ok", pointsLost: 0, file: "Container.tsx:6" },
    { message: "useId for accessible labels", severity: "ok", pointsLost: 0, file: "Field.tsx:10" },
    { message: "Mutation inside render function", severity: "error", pointsLost: 5, file: "Summary.tsx:27" },
    { message: "Promise not handled in effect", severity: "warning", pointsLost: 2, file: "useFetch.ts:15" },
    { message: "Proper default props pattern", severity: "ok", pointsLost: 0, file: "Avatar.tsx:3" },
    { message: "Excessive re-renders from context", severity: "warning", pointsLost: 2, file: "ThemeToggle.tsx:22" },
    { message: "Missing aria attributes on button", severity: "warning", pointsLost: 2, file: "IconBtn.tsx:8" },
    { message: "useLayoutEffect in SSR component", severity: "error", pointsLost: 5, file: "Header.tsx:34" },
    { message: "Stable ref callback", severity: "ok", pointsLost: 0, file: "Popover.tsx:19" },
    { message: "Non-serializable value in state", severity: "warning", pointsLost: 2, file: "useMap.ts:7" },
    { message: "Proper list virtualization", severity: "ok", pointsLost: 0, file: "Feed.tsx:62" },
    { message: "dangerouslySetInnerHTML used safely", severity: "ok", pointsLost: 0, file: "Markdown.tsx:14" },
    { message: "Effect cleanup prevents memory leak", severity: "ok", pointsLost: 0, file: "Socket.tsx:28" },
    { message: "Throwing in render without boundary", severity: "error", pointsLost: 5, file: "Detail.tsx:45" },
    { message: "Synthetic event accessed async", severity: "error", pointsLost: 5, file: "Dropdown.tsx:37" },
    { message: "Fragment avoids extra DOM node", severity: "ok", pointsLost: 0, file: "List.tsx:9" },
    { message: "Debounced input handler", severity: "ok", pointsLost: 0, file: "Autocomplete.tsx:53" },
    { message: "State update on unmounted component", severity: "error", pointsLost: 5, file: "Notification.tsx:41" },
    { message: "Proper use of React.lazy", severity: "ok", pointsLost: 0, file: "routes.tsx:18" },
    { message: "Missing alt text on image", severity: "warning", pointsLost: 2, file: "Gallery.tsx:25" },
    { message: "Unnecessary wrapper div", severity: "warning", pointsLost: 2, file: "Panel.tsx:11" },
    { message: "Computed value not memoized", severity: "warning", pointsLost: 2, file: "Stats.tsx:30" },
    { message: "Proper form submission handling", severity: "ok", pointsLost: 0, file: "Register.tsx:22" },
    { message: "Correct use of useImperativeHandle", severity: "ok", pointsLost: 0, file: "Player.tsx:46" },
    { message: "Timer not cleared on unmount", severity: "error", pointsLost: 5, file: "Toast.tsx:16" },
    { message: "Optimistic update pattern correct", severity: "ok", pointsLost: 0, file: "Like.tsx:8" },
    { message: "Prop type mismatch at boundary", severity: "warning", pointsLost: 2, file: "Wrapper.tsx:35" },
    { message: "Effect fires twice in StrictMode", severity: "warning", pointsLost: 2, file: "Analytics.tsx:20" },
    { message: "Proper use of useDeferredValue", severity: "ok", pointsLost: 0, file: "Results.tsx:39" },
  ],
};
