export const CHANGE_COMPLEXITY_MAX_TREE_EDIT_NODE_COUNT = 160;
export const CHANGE_COMPLEXITY_INSERTION_WEIGHT_FACTOR = 1;
export const CHANGE_COMPLEXITY_DELETION_WEIGHT_FACTOR = 0.75;
export const CHANGE_COMPLEXITY_RELABEL_WEIGHT_FACTOR = 1;

export const CHANGE_COMPLEXITY_FUNCTION_NODE_WEIGHT = 1;
export const CHANGE_COMPLEXITY_CONTROL_FLOW_NODE_WEIGHT = 6;
export const CHANGE_COMPLEXITY_JSX_NODE_WEIGHT = 5;
export const CHANGE_COMPLEXITY_HOOK_CALL_NODE_WEIGHT = 5;
export const CHANGE_COMPLEXITY_ASYNC_AWAIT_NODE_WEIGHT = 4;
export const CHANGE_COMPLEXITY_TRY_CATCH_NODE_WEIGHT = 4;
export const CHANGE_COMPLEXITY_CALL_NODE_WEIGHT = 1;
export const CHANGE_COMPLEXITY_LOGICAL_NODE_WEIGHT = 1;
export const CHANGE_COMPLEXITY_DEFAULT_NODE_WEIGHT = 0;

export const CHANGE_COMPLEXITY_CYCLOMATIC_WEIGHT = 1;
export const CHANGE_COMPLEXITY_COGNITIVE_WEIGHT = 1;
export const CHANGE_COMPLEXITY_NESTING_WEIGHT = 1;
export const CHANGE_COMPLEXITY_STRUCTURAL_RISK_WEIGHT = 1;
export const CHANGE_COMPLEXITY_ENTROPY_WEIGHT = 1;
